/* SPDX-License-Identifier: GPL-2.0-or-later
 *
 * Copyright (C) 2026 Phoenix Systems
 * Author: Witold Bołt
 *
 * Phoenix-RTOS platform backend for vkQuake (vkQuake is Copyright (C) id
 * Software, Inc. and the vkQuake developers, GPL-2.0-or-later). It implements
 * the vkQuake platform interface and is distributed under the same license as
 * the program it is built into; see COPYING in this directory.
 */
/*
 * vk_trampolines.c — GENERATED by gen-vk-trampolines.py. DO NOT EDIT BY HAND.
 *
 * Public vk* command symbols that vkQuake calls directly (it includes vulkan_core.h
 * without VK_NO_PROTOTYPES). A Mesa ICD does not export these; each forwards through
 * the ICD dispatch resolved via vkGetInstanceProcAddr (aliased to v3dv_GetInstanceProcAddr
 * in vk_icd_link.c). Global cmds: NULL instance. Instance/phys-dev cmds: g_vk_instance.
 * Device cmds (VkDevice/VkQueue/VkCommandBuffer first arg): MUST resolve via
 * vkGetDeviceProcAddr against g_vk_device — instance-proc-addr returns NULL for device
 * commands in a loader-less ICD (proven by v3dv_harness.c; calling NULL = pc=0 abort).
 *
 * 75 commands trampolined. Regenerate when the directly-called set changes.
 */
#include <vulkan/vulkan_core.h>
#include <string.h>

PFN_vkVoidFunction vkGetInstanceProcAddr(VkInstance instance, const char *pName);
/* Diagnostic for the NULL-fp guard below (UART/console-reaching print from the engine). */
extern void Sys_Printf(const char *fmt, ...);

/* Published by the Vulkan vid shim (pl_phoenix_vk_vid.c) right after vkCreateInstance /
 * vkCreateDevice so the trampolines can resolve their real entrypoints. */
VkInstance g_vk_instance = VK_NULL_HANDLE;
VkDevice   g_vk_device = VK_NULL_HANDLE;

/* Lazily resolved vkGetDeviceProcAddr (itself fetched via instance-proc-addr). */
static PFN_vkVoidFunction g_vkGetDeviceProcAddr(VkDevice dev, const char *name)
{
	static PFN_vkGetDeviceProcAddr fp = NULL;
	if (!fp)
		fp = (PFN_vkGetDeviceProcAddr)vkGetInstanceProcAddr(g_vk_instance, "vkGetDeviceProcAddr");
	return fp(dev, name);
}

VkResult vkAllocateCommandBuffers(VkDevice device, const VkCommandBufferAllocateInfo* pAllocateInfo, VkCommandBuffer* pCommandBuffers)
{
	static PFN_vkAllocateCommandBuffers fp = NULL;
	if (!fp) fp = (PFN_vkAllocateCommandBuffers)g_vkGetDeviceProcAddr(g_vk_device, "vkAllocateCommandBuffers");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkAllocateCommandBuffers\n"); return VK_ERROR_INITIALIZATION_FAILED; }
	return fp(device, pAllocateInfo, pCommandBuffers);
}

VkResult vkAllocateDescriptorSets(VkDevice device, const VkDescriptorSetAllocateInfo* pAllocateInfo, VkDescriptorSet* pDescriptorSets)
{
	static PFN_vkAllocateDescriptorSets fp = NULL;
	if (!fp) fp = (PFN_vkAllocateDescriptorSets)g_vkGetDeviceProcAddr(g_vk_device, "vkAllocateDescriptorSets");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkAllocateDescriptorSets\n"); return VK_ERROR_INITIALIZATION_FAILED; }
	return fp(device, pAllocateInfo, pDescriptorSets);
}

VkResult vkAllocateMemory(VkDevice device, const VkMemoryAllocateInfo* pAllocateInfo, const VkAllocationCallbacks* pAllocator, VkDeviceMemory* pMemory)
{
	static PFN_vkAllocateMemory fp = NULL;
	if (!fp) fp = (PFN_vkAllocateMemory)g_vkGetDeviceProcAddr(g_vk_device, "vkAllocateMemory");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkAllocateMemory\n"); return VK_ERROR_INITIALIZATION_FAILED; }
	return fp(device, pAllocateInfo, pAllocator, pMemory);
}

VkResult vkBeginCommandBuffer(VkCommandBuffer commandBuffer, const VkCommandBufferBeginInfo* pBeginInfo)
{
	static PFN_vkBeginCommandBuffer fp = NULL;
	if (!fp) fp = (PFN_vkBeginCommandBuffer)g_vkGetDeviceProcAddr(g_vk_device, "vkBeginCommandBuffer");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkBeginCommandBuffer\n"); return VK_ERROR_INITIALIZATION_FAILED; }
	return fp(commandBuffer, pBeginInfo);
}

VkResult vkBindBufferMemory(VkDevice device, VkBuffer buffer, VkDeviceMemory memory, VkDeviceSize memoryOffset)
{
	static PFN_vkBindBufferMemory fp = NULL;
	if (!fp) fp = (PFN_vkBindBufferMemory)g_vkGetDeviceProcAddr(g_vk_device, "vkBindBufferMemory");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkBindBufferMemory\n"); return VK_ERROR_INITIALIZATION_FAILED; }
	return fp(device, buffer, memory, memoryOffset);
}

VkResult vkBindImageMemory(VkDevice device, VkImage image, VkDeviceMemory memory, VkDeviceSize memoryOffset)
{
	static PFN_vkBindImageMemory fp = NULL;
	if (!fp) fp = (PFN_vkBindImageMemory)g_vkGetDeviceProcAddr(g_vk_device, "vkBindImageMemory");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkBindImageMemory\n"); return VK_ERROR_INITIALIZATION_FAILED; }
	return fp(device, image, memory, memoryOffset);
}

void vkCmdBeginRenderPass(VkCommandBuffer commandBuffer, const VkRenderPassBeginInfo* pRenderPassBegin, VkSubpassContents contents)
{
	static PFN_vkCmdBeginRenderPass fp = NULL;
	if (!fp) fp = (PFN_vkCmdBeginRenderPass)g_vkGetDeviceProcAddr(g_vk_device, "vkCmdBeginRenderPass");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkCmdBeginRenderPass\n"); return; }
	fp(commandBuffer, pRenderPassBegin, contents);
}

void vkCmdBindDescriptorSets(VkCommandBuffer commandBuffer, VkPipelineBindPoint pipelineBindPoint, VkPipelineLayout layout, uint32_t firstSet, uint32_t descriptorSetCount, const VkDescriptorSet* pDescriptorSets, uint32_t dynamicOffsetCount, const uint32_t* pDynamicOffsets)
{
	static PFN_vkCmdBindDescriptorSets fp = NULL;
	if (!fp) fp = (PFN_vkCmdBindDescriptorSets)g_vkGetDeviceProcAddr(g_vk_device, "vkCmdBindDescriptorSets");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkCmdBindDescriptorSets\n"); return; }
	fp(commandBuffer, pipelineBindPoint, layout, firstSet, descriptorSetCount, pDescriptorSets, dynamicOffsetCount, pDynamicOffsets);
}

void vkCmdBindIndexBuffer(VkCommandBuffer commandBuffer, VkBuffer buffer, VkDeviceSize offset, VkIndexType indexType)
{
	static PFN_vkCmdBindIndexBuffer fp = NULL;
	if (!fp) fp = (PFN_vkCmdBindIndexBuffer)g_vkGetDeviceProcAddr(g_vk_device, "vkCmdBindIndexBuffer");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkCmdBindIndexBuffer\n"); return; }
	fp(commandBuffer, buffer, offset, indexType);
}

void vkCmdBindVertexBuffers(VkCommandBuffer commandBuffer, uint32_t firstBinding, uint32_t bindingCount, const VkBuffer* pBuffers, const VkDeviceSize* pOffsets)
{
	static PFN_vkCmdBindVertexBuffers fp = NULL;
	if (!fp) fp = (PFN_vkCmdBindVertexBuffers)g_vkGetDeviceProcAddr(g_vk_device, "vkCmdBindVertexBuffers");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkCmdBindVertexBuffers\n"); return; }
	fp(commandBuffer, firstBinding, bindingCount, pBuffers, pOffsets);
}

void vkCmdBlitImage(VkCommandBuffer commandBuffer, VkImage srcImage, VkImageLayout srcImageLayout, VkImage dstImage, VkImageLayout dstImageLayout, uint32_t regionCount, const VkImageBlit* pRegions, VkFilter filter)
{
	static PFN_vkCmdBlitImage fp = NULL;
	if (!fp) fp = (PFN_vkCmdBlitImage)g_vkGetDeviceProcAddr(g_vk_device, "vkCmdBlitImage");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkCmdBlitImage\n"); return; }
	fp(commandBuffer, srcImage, srcImageLayout, dstImage, dstImageLayout, regionCount, pRegions, filter);
}

void vkCmdCopyBuffer(VkCommandBuffer commandBuffer, VkBuffer srcBuffer, VkBuffer dstBuffer, uint32_t regionCount, const VkBufferCopy* pRegions)
{
	static PFN_vkCmdCopyBuffer fp = NULL;
	if (!fp) fp = (PFN_vkCmdCopyBuffer)g_vkGetDeviceProcAddr(g_vk_device, "vkCmdCopyBuffer");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkCmdCopyBuffer\n"); return; }
	fp(commandBuffer, srcBuffer, dstBuffer, regionCount, pRegions);
}

void vkCmdCopyBufferToImage(VkCommandBuffer commandBuffer, VkBuffer srcBuffer, VkImage dstImage, VkImageLayout dstImageLayout, uint32_t regionCount, const VkBufferImageCopy* pRegions)
{
	static PFN_vkCmdCopyBufferToImage fp = NULL;
	if (!fp) fp = (PFN_vkCmdCopyBufferToImage)g_vkGetDeviceProcAddr(g_vk_device, "vkCmdCopyBufferToImage");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkCmdCopyBufferToImage\n"); return; }
	fp(commandBuffer, srcBuffer, dstImage, dstImageLayout, regionCount, pRegions);
}

void vkCmdCopyImageToBuffer(VkCommandBuffer commandBuffer, VkImage srcImage, VkImageLayout srcImageLayout, VkBuffer dstBuffer, uint32_t regionCount, const VkBufferImageCopy* pRegions)
{
	static PFN_vkCmdCopyImageToBuffer fp = NULL;
	if (!fp) fp = (PFN_vkCmdCopyImageToBuffer)g_vkGetDeviceProcAddr(g_vk_device, "vkCmdCopyImageToBuffer");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkCmdCopyImageToBuffer\n"); return; }
	fp(commandBuffer, srcImage, srcImageLayout, dstBuffer, regionCount, pRegions);
}

void vkCmdDispatch(VkCommandBuffer commandBuffer, uint32_t groupCountX, uint32_t groupCountY, uint32_t groupCountZ)
{
	static PFN_vkCmdDispatch fp = NULL;
	if (!fp) fp = (PFN_vkCmdDispatch)g_vkGetDeviceProcAddr(g_vk_device, "vkCmdDispatch");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkCmdDispatch\n"); return; }
	fp(commandBuffer, groupCountX, groupCountY, groupCountZ);
}

void vkCmdDraw(VkCommandBuffer commandBuffer, uint32_t vertexCount, uint32_t instanceCount, uint32_t firstVertex, uint32_t firstInstance)
{
	static PFN_vkCmdDraw fp = NULL;
	if (!fp) fp = (PFN_vkCmdDraw)g_vkGetDeviceProcAddr(g_vk_device, "vkCmdDraw");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkCmdDraw\n"); return; }
	fp(commandBuffer, vertexCount, instanceCount, firstVertex, firstInstance);
}

void vkCmdDrawIndexed(VkCommandBuffer commandBuffer, uint32_t indexCount, uint32_t instanceCount, uint32_t firstIndex, int32_t vertexOffset, uint32_t firstInstance)
{
	static PFN_vkCmdDrawIndexed fp = NULL;
	if (!fp) fp = (PFN_vkCmdDrawIndexed)g_vkGetDeviceProcAddr(g_vk_device, "vkCmdDrawIndexed");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkCmdDrawIndexed\n"); return; }
	fp(commandBuffer, indexCount, instanceCount, firstIndex, vertexOffset, firstInstance);
}

void vkCmdEndRenderPass(VkCommandBuffer commandBuffer)
{
	static PFN_vkCmdEndRenderPass fp = NULL;
	if (!fp) fp = (PFN_vkCmdEndRenderPass)g_vkGetDeviceProcAddr(g_vk_device, "vkCmdEndRenderPass");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkCmdEndRenderPass\n"); return; }
	fp(commandBuffer);
}

void vkCmdExecuteCommands(VkCommandBuffer commandBuffer, uint32_t commandBufferCount, const VkCommandBuffer* pCommandBuffers)
{
	static PFN_vkCmdExecuteCommands fp = NULL;
	if (!fp) fp = (PFN_vkCmdExecuteCommands)g_vkGetDeviceProcAddr(g_vk_device, "vkCmdExecuteCommands");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkCmdExecuteCommands\n"); return; }
	fp(commandBuffer, commandBufferCount, pCommandBuffers);
}

void vkCmdNextSubpass(VkCommandBuffer commandBuffer, VkSubpassContents contents)
{
	static PFN_vkCmdNextSubpass fp = NULL;
	if (!fp) fp = (PFN_vkCmdNextSubpass)g_vkGetDeviceProcAddr(g_vk_device, "vkCmdNextSubpass");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkCmdNextSubpass\n"); return; }
	fp(commandBuffer, contents);
}

void vkCmdPipelineBarrier(VkCommandBuffer commandBuffer, VkPipelineStageFlags srcStageMask, VkPipelineStageFlags dstStageMask, VkDependencyFlags dependencyFlags, uint32_t memoryBarrierCount, const VkMemoryBarrier* pMemoryBarriers, uint32_t bufferMemoryBarrierCount, const VkBufferMemoryBarrier* pBufferMemoryBarriers, uint32_t imageMemoryBarrierCount, const VkImageMemoryBarrier* pImageMemoryBarriers)
{
	static PFN_vkCmdPipelineBarrier fp = NULL;
	if (!fp) fp = (PFN_vkCmdPipelineBarrier)g_vkGetDeviceProcAddr(g_vk_device, "vkCmdPipelineBarrier");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkCmdPipelineBarrier\n"); return; }
	fp(commandBuffer, srcStageMask, dstStageMask, dependencyFlags, memoryBarrierCount, pMemoryBarriers, bufferMemoryBarrierCount, pBufferMemoryBarriers, imageMemoryBarrierCount, pImageMemoryBarriers);
}

void vkCmdSetDepthBias(VkCommandBuffer commandBuffer, float depthBiasConstantFactor, float depthBiasClamp, float depthBiasSlopeFactor)
{
	static PFN_vkCmdSetDepthBias fp = NULL;
	if (!fp) fp = (PFN_vkCmdSetDepthBias)g_vkGetDeviceProcAddr(g_vk_device, "vkCmdSetDepthBias");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkCmdSetDepthBias\n"); return; }
	fp(commandBuffer, depthBiasConstantFactor, depthBiasClamp, depthBiasSlopeFactor);
}

void vkCmdSetScissor(VkCommandBuffer commandBuffer, uint32_t firstScissor, uint32_t scissorCount, const VkRect2D* pScissors)
{
	static PFN_vkCmdSetScissor fp = NULL;
	if (!fp) fp = (PFN_vkCmdSetScissor)g_vkGetDeviceProcAddr(g_vk_device, "vkCmdSetScissor");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkCmdSetScissor\n"); return; }
	fp(commandBuffer, firstScissor, scissorCount, pScissors);
}

void vkCmdSetViewport(VkCommandBuffer commandBuffer, uint32_t firstViewport, uint32_t viewportCount, const VkViewport* pViewports)
{
	static PFN_vkCmdSetViewport fp = NULL;
	if (!fp) fp = (PFN_vkCmdSetViewport)g_vkGetDeviceProcAddr(g_vk_device, "vkCmdSetViewport");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkCmdSetViewport\n"); return; }
	fp(commandBuffer, firstViewport, viewportCount, pViewports);
}

VkResult vkCreateBuffer(VkDevice device, const VkBufferCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkBuffer* pBuffer)
{
	static PFN_vkCreateBuffer fp = NULL;
	if (!fp) fp = (PFN_vkCreateBuffer)g_vkGetDeviceProcAddr(g_vk_device, "vkCreateBuffer");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkCreateBuffer\n"); return VK_ERROR_INITIALIZATION_FAILED; }
	return fp(device, pCreateInfo, pAllocator, pBuffer);
}

VkResult vkCreateBufferView(VkDevice device, const VkBufferViewCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkBufferView* pView)
{
	static PFN_vkCreateBufferView fp = NULL;
	if (!fp) fp = (PFN_vkCreateBufferView)g_vkGetDeviceProcAddr(g_vk_device, "vkCreateBufferView");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkCreateBufferView\n"); return VK_ERROR_INITIALIZATION_FAILED; }
	return fp(device, pCreateInfo, pAllocator, pView);
}

VkResult vkCreateCommandPool(VkDevice device, const VkCommandPoolCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkCommandPool* pCommandPool)
{
	static PFN_vkCreateCommandPool fp = NULL;
	if (!fp) fp = (PFN_vkCreateCommandPool)g_vkGetDeviceProcAddr(g_vk_device, "vkCreateCommandPool");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkCreateCommandPool\n"); return VK_ERROR_INITIALIZATION_FAILED; }
	return fp(device, pCreateInfo, pAllocator, pCommandPool);
}

VkResult vkCreateComputePipelines(VkDevice device, VkPipelineCache pipelineCache, uint32_t createInfoCount, const VkComputePipelineCreateInfo* pCreateInfos, const VkAllocationCallbacks* pAllocator, VkPipeline* pPipelines)
{
	static PFN_vkCreateComputePipelines fp = NULL;
	if (!fp) fp = (PFN_vkCreateComputePipelines)g_vkGetDeviceProcAddr(g_vk_device, "vkCreateComputePipelines");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkCreateComputePipelines\n"); return VK_ERROR_INITIALIZATION_FAILED; }
	return fp(device, pipelineCache, createInfoCount, pCreateInfos, pAllocator, pPipelines);
}

VkResult vkCreateDescriptorPool(VkDevice device, const VkDescriptorPoolCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkDescriptorPool* pDescriptorPool)
{
	static PFN_vkCreateDescriptorPool fp = NULL;
	if (!fp) fp = (PFN_vkCreateDescriptorPool)g_vkGetDeviceProcAddr(g_vk_device, "vkCreateDescriptorPool");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkCreateDescriptorPool\n"); return VK_ERROR_INITIALIZATION_FAILED; }
	return fp(device, pCreateInfo, pAllocator, pDescriptorPool);
}

VkResult vkCreateDescriptorSetLayout(VkDevice device, const VkDescriptorSetLayoutCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkDescriptorSetLayout* pSetLayout)
{
	static PFN_vkCreateDescriptorSetLayout fp = NULL;
	if (!fp) fp = (PFN_vkCreateDescriptorSetLayout)g_vkGetDeviceProcAddr(g_vk_device, "vkCreateDescriptorSetLayout");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkCreateDescriptorSetLayout\n"); return VK_ERROR_INITIALIZATION_FAILED; }
	return fp(device, pCreateInfo, pAllocator, pSetLayout);
}

VkResult vkCreateDevice(VkPhysicalDevice physicalDevice, const VkDeviceCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkDevice* pDevice)
{
	static PFN_vkCreateDevice fp = NULL;
	if (!fp) fp = (PFN_vkCreateDevice)vkGetInstanceProcAddr(g_vk_instance, "vkCreateDevice");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkCreateDevice\n"); return VK_ERROR_INITIALIZATION_FAILED; }
	return fp(physicalDevice, pCreateInfo, pAllocator, pDevice);
}

VkResult vkCreateFence(VkDevice device, const VkFenceCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkFence* pFence)
{
	static PFN_vkCreateFence fp = NULL;
	if (!fp) fp = (PFN_vkCreateFence)g_vkGetDeviceProcAddr(g_vk_device, "vkCreateFence");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkCreateFence\n"); return VK_ERROR_INITIALIZATION_FAILED; }
	return fp(device, pCreateInfo, pAllocator, pFence);
}

VkResult vkCreateFramebuffer(VkDevice device, const VkFramebufferCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkFramebuffer* pFramebuffer)
{
	static PFN_vkCreateFramebuffer fp = NULL;
	if (!fp) fp = (PFN_vkCreateFramebuffer)g_vkGetDeviceProcAddr(g_vk_device, "vkCreateFramebuffer");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkCreateFramebuffer\n"); return VK_ERROR_INITIALIZATION_FAILED; }
	return fp(device, pCreateInfo, pAllocator, pFramebuffer);
}

VkResult vkCreateGraphicsPipelines(VkDevice device, VkPipelineCache pipelineCache, uint32_t createInfoCount, const VkGraphicsPipelineCreateInfo* pCreateInfos, const VkAllocationCallbacks* pAllocator, VkPipeline* pPipelines)
{
	static PFN_vkCreateGraphicsPipelines fp = NULL;
	if (!fp) fp = (PFN_vkCreateGraphicsPipelines)g_vkGetDeviceProcAddr(g_vk_device, "vkCreateGraphicsPipelines");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkCreateGraphicsPipelines\n"); return VK_ERROR_INITIALIZATION_FAILED; }
	return fp(device, pipelineCache, createInfoCount, pCreateInfos, pAllocator, pPipelines);
}

VkResult vkCreateImage(VkDevice device, const VkImageCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkImage* pImage)
{
	static PFN_vkCreateImage fp = NULL;
	if (!fp) fp = (PFN_vkCreateImage)g_vkGetDeviceProcAddr(g_vk_device, "vkCreateImage");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkCreateImage\n"); return VK_ERROR_INITIALIZATION_FAILED; }
	return fp(device, pCreateInfo, pAllocator, pImage);
}

VkResult vkCreateImageView(VkDevice device, const VkImageViewCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkImageView* pView)
{
	static PFN_vkCreateImageView fp = NULL;
	if (!fp) fp = (PFN_vkCreateImageView)g_vkGetDeviceProcAddr(g_vk_device, "vkCreateImageView");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkCreateImageView\n"); return VK_ERROR_INITIALIZATION_FAILED; }
	return fp(device, pCreateInfo, pAllocator, pView);
}

VkResult vkCreateInstance(const VkInstanceCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkInstance* pInstance)
{
	static PFN_vkCreateInstance fp = NULL;
	if (!fp) fp = (PFN_vkCreateInstance)vkGetInstanceProcAddr(NULL, "vkCreateInstance");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkCreateInstance\n"); return VK_ERROR_INITIALIZATION_FAILED; }
	return fp(pCreateInfo, pAllocator, pInstance);
}

VkResult vkCreatePipelineLayout(VkDevice device, const VkPipelineLayoutCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkPipelineLayout* pPipelineLayout)
{
	static PFN_vkCreatePipelineLayout fp = NULL;
	if (!fp) fp = (PFN_vkCreatePipelineLayout)g_vkGetDeviceProcAddr(g_vk_device, "vkCreatePipelineLayout");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkCreatePipelineLayout\n"); return VK_ERROR_INITIALIZATION_FAILED; }
	return fp(device, pCreateInfo, pAllocator, pPipelineLayout);
}

VkResult vkCreateRenderPass(VkDevice device, const VkRenderPassCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkRenderPass* pRenderPass)
{
	static PFN_vkCreateRenderPass fp = NULL;
	if (!fp) fp = (PFN_vkCreateRenderPass)g_vkGetDeviceProcAddr(g_vk_device, "vkCreateRenderPass");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkCreateRenderPass\n"); return VK_ERROR_INITIALIZATION_FAILED; }
	return fp(device, pCreateInfo, pAllocator, pRenderPass);
}

VkResult vkCreateSampler(VkDevice device, const VkSamplerCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkSampler* pSampler)
{
	static PFN_vkCreateSampler fp = NULL;
	if (!fp) fp = (PFN_vkCreateSampler)g_vkGetDeviceProcAddr(g_vk_device, "vkCreateSampler");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkCreateSampler\n"); return VK_ERROR_INITIALIZATION_FAILED; }
	return fp(device, pCreateInfo, pAllocator, pSampler);
}

VkResult vkCreateSemaphore(VkDevice device, const VkSemaphoreCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkSemaphore* pSemaphore)
{
	static PFN_vkCreateSemaphore fp = NULL;
	if (!fp) fp = (PFN_vkCreateSemaphore)g_vkGetDeviceProcAddr(g_vk_device, "vkCreateSemaphore");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkCreateSemaphore\n"); return VK_ERROR_INITIALIZATION_FAILED; }
	return fp(device, pCreateInfo, pAllocator, pSemaphore);
}

VkResult vkCreateShaderModule(VkDevice device, const VkShaderModuleCreateInfo* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkShaderModule* pShaderModule)
{
	static PFN_vkCreateShaderModule fp = NULL;
	if (!fp) fp = (PFN_vkCreateShaderModule)g_vkGetDeviceProcAddr(g_vk_device, "vkCreateShaderModule");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkCreateShaderModule\n"); return VK_ERROR_INITIALIZATION_FAILED; }
	return fp(device, pCreateInfo, pAllocator, pShaderModule);
}

void vkDestroyBuffer(VkDevice device, VkBuffer buffer, const VkAllocationCallbacks* pAllocator)
{
	static PFN_vkDestroyBuffer fp = NULL;
	if (!fp) fp = (PFN_vkDestroyBuffer)g_vkGetDeviceProcAddr(g_vk_device, "vkDestroyBuffer");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkDestroyBuffer\n"); return; }
	fp(device, buffer, pAllocator);
}

void vkDestroyFramebuffer(VkDevice device, VkFramebuffer framebuffer, const VkAllocationCallbacks* pAllocator)
{
	static PFN_vkDestroyFramebuffer fp = NULL;
	if (!fp) fp = (PFN_vkDestroyFramebuffer)g_vkGetDeviceProcAddr(g_vk_device, "vkDestroyFramebuffer");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkDestroyFramebuffer\n"); return; }
	fp(device, framebuffer, pAllocator);
}

void vkDestroyImage(VkDevice device, VkImage image, const VkAllocationCallbacks* pAllocator)
{
	static PFN_vkDestroyImage fp = NULL;
	if (!fp) fp = (PFN_vkDestroyImage)g_vkGetDeviceProcAddr(g_vk_device, "vkDestroyImage");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkDestroyImage\n"); return; }
	fp(device, image, pAllocator);
}

void vkDestroyImageView(VkDevice device, VkImageView imageView, const VkAllocationCallbacks* pAllocator)
{
	static PFN_vkDestroyImageView fp = NULL;
	if (!fp) fp = (PFN_vkDestroyImageView)g_vkGetDeviceProcAddr(g_vk_device, "vkDestroyImageView");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkDestroyImageView\n"); return; }
	fp(device, imageView, pAllocator);
}

void vkDestroyPipeline(VkDevice device, VkPipeline pipeline, const VkAllocationCallbacks* pAllocator)
{
	static PFN_vkDestroyPipeline fp = NULL;
	if (!fp) fp = (PFN_vkDestroyPipeline)g_vkGetDeviceProcAddr(g_vk_device, "vkDestroyPipeline");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkDestroyPipeline\n"); return; }
	fp(device, pipeline, pAllocator);
}

void vkDestroyRenderPass(VkDevice device, VkRenderPass renderPass, const VkAllocationCallbacks* pAllocator)
{
	static PFN_vkDestroyRenderPass fp = NULL;
	if (!fp) fp = (PFN_vkDestroyRenderPass)g_vkGetDeviceProcAddr(g_vk_device, "vkDestroyRenderPass");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkDestroyRenderPass\n"); return; }
	fp(device, renderPass, pAllocator);
}

void vkDestroySampler(VkDevice device, VkSampler sampler, const VkAllocationCallbacks* pAllocator)
{
	static PFN_vkDestroySampler fp = NULL;
	if (!fp) fp = (PFN_vkDestroySampler)g_vkGetDeviceProcAddr(g_vk_device, "vkDestroySampler");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkDestroySampler\n"); return; }
	fp(device, sampler, pAllocator);
}

void vkDestroySemaphore(VkDevice device, VkSemaphore semaphore, const VkAllocationCallbacks* pAllocator)
{
	static PFN_vkDestroySemaphore fp = NULL;
	if (!fp) fp = (PFN_vkDestroySemaphore)g_vkGetDeviceProcAddr(g_vk_device, "vkDestroySemaphore");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkDestroySemaphore\n"); return; }
	fp(device, semaphore, pAllocator);
}

void vkDestroyShaderModule(VkDevice device, VkShaderModule shaderModule, const VkAllocationCallbacks* pAllocator)
{
	static PFN_vkDestroyShaderModule fp = NULL;
	if (!fp) fp = (PFN_vkDestroyShaderModule)g_vkGetDeviceProcAddr(g_vk_device, "vkDestroyShaderModule");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkDestroyShaderModule\n"); return; }
	fp(device, shaderModule, pAllocator);
}

VkResult vkDeviceWaitIdle(VkDevice device)
{
	static PFN_vkDeviceWaitIdle fp = NULL;
	if (!fp) fp = (PFN_vkDeviceWaitIdle)g_vkGetDeviceProcAddr(g_vk_device, "vkDeviceWaitIdle");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkDeviceWaitIdle\n"); return VK_ERROR_INITIALIZATION_FAILED; }
	return fp(device);
}

VkResult vkEndCommandBuffer(VkCommandBuffer commandBuffer)
{
	static PFN_vkEndCommandBuffer fp = NULL;
	if (!fp) fp = (PFN_vkEndCommandBuffer)g_vkGetDeviceProcAddr(g_vk_device, "vkEndCommandBuffer");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkEndCommandBuffer\n"); return VK_ERROR_INITIALIZATION_FAILED; }
	return fp(commandBuffer);
}

VkResult vkEnumerateDeviceExtensionProperties(VkPhysicalDevice physicalDevice, const char* pLayerName, uint32_t* pPropertyCount, VkExtensionProperties* pProperties)
{
	static PFN_vkEnumerateDeviceExtensionProperties fp = NULL;
	if (!fp) fp = (PFN_vkEnumerateDeviceExtensionProperties)vkGetInstanceProcAddr(g_vk_instance, "vkEnumerateDeviceExtensionProperties");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkEnumerateDeviceExtensionProperties\n"); return VK_ERROR_INITIALIZATION_FAILED; }
	return fp(physicalDevice, pLayerName, pPropertyCount, pProperties);
}

VkResult vkEnumerateInstanceExtensionProperties(const char* pLayerName, uint32_t* pPropertyCount, VkExtensionProperties* pProperties)
{
	static PFN_vkEnumerateInstanceExtensionProperties fp = NULL;
	if (!fp) fp = (PFN_vkEnumerateInstanceExtensionProperties)vkGetInstanceProcAddr(NULL, "vkEnumerateInstanceExtensionProperties");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkEnumerateInstanceExtensionProperties\n"); return VK_ERROR_INITIALIZATION_FAILED; }
	return fp(pLayerName, pPropertyCount, pProperties);
}

VkResult vkEnumeratePhysicalDevices(VkInstance instance, uint32_t* pPhysicalDeviceCount, VkPhysicalDevice* pPhysicalDevices)
{
	static PFN_vkEnumeratePhysicalDevices fp = NULL;
	if (!fp) fp = (PFN_vkEnumeratePhysicalDevices)vkGetInstanceProcAddr(g_vk_instance, "vkEnumeratePhysicalDevices");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkEnumeratePhysicalDevices\n"); return VK_ERROR_INITIALIZATION_FAILED; }
	return fp(instance, pPhysicalDeviceCount, pPhysicalDevices);
}

VkResult vkFlushMappedMemoryRanges(VkDevice device, uint32_t memoryRangeCount, const VkMappedMemoryRange* pMemoryRanges)
{
	static PFN_vkFlushMappedMemoryRanges fp = NULL;
	if (!fp) fp = (PFN_vkFlushMappedMemoryRanges)g_vkGetDeviceProcAddr(g_vk_device, "vkFlushMappedMemoryRanges");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkFlushMappedMemoryRanges\n"); return VK_ERROR_INITIALIZATION_FAILED; }
	return fp(device, memoryRangeCount, pMemoryRanges);
}

VkResult vkFreeDescriptorSets(VkDevice device, VkDescriptorPool descriptorPool, uint32_t descriptorSetCount, const VkDescriptorSet* pDescriptorSets)
{
	static PFN_vkFreeDescriptorSets fp = NULL;
	if (!fp) fp = (PFN_vkFreeDescriptorSets)g_vkGetDeviceProcAddr(g_vk_device, "vkFreeDescriptorSets");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkFreeDescriptorSets\n"); return VK_ERROR_INITIALIZATION_FAILED; }
	return fp(device, descriptorPool, descriptorSetCount, pDescriptorSets);
}

void vkFreeMemory(VkDevice device, VkDeviceMemory memory, const VkAllocationCallbacks* pAllocator)
{
	static PFN_vkFreeMemory fp = NULL;
	if (!fp) fp = (PFN_vkFreeMemory)g_vkGetDeviceProcAddr(g_vk_device, "vkFreeMemory");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkFreeMemory\n"); return; }
	fp(device, memory, pAllocator);
}

void vkGetBufferMemoryRequirements(VkDevice device, VkBuffer buffer, VkMemoryRequirements* pMemoryRequirements)
{
	static PFN_vkGetBufferMemoryRequirements fp = NULL;
	if (!fp) fp = (PFN_vkGetBufferMemoryRequirements)g_vkGetDeviceProcAddr(g_vk_device, "vkGetBufferMemoryRequirements");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkGetBufferMemoryRequirements\n"); return; }
	fp(device, buffer, pMemoryRequirements);
}

void vkGetDeviceQueue(VkDevice device, uint32_t queueFamilyIndex, uint32_t queueIndex, VkQueue* pQueue)
{
	static PFN_vkGetDeviceQueue fp = NULL;
	if (!fp) fp = (PFN_vkGetDeviceQueue)g_vkGetDeviceProcAddr(g_vk_device, "vkGetDeviceQueue");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkGetDeviceQueue\n"); return; }
	fp(device, queueFamilyIndex, queueIndex, pQueue);
}

void vkGetImageMemoryRequirements(VkDevice device, VkImage image, VkMemoryRequirements* pMemoryRequirements)
{
	static PFN_vkGetImageMemoryRequirements fp = NULL;
	if (!fp) fp = (PFN_vkGetImageMemoryRequirements)g_vkGetDeviceProcAddr(g_vk_device, "vkGetImageMemoryRequirements");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkGetImageMemoryRequirements\n"); return; }
	fp(device, image, pMemoryRequirements);
}

void vkGetPhysicalDeviceFeatures(VkPhysicalDevice physicalDevice, VkPhysicalDeviceFeatures* pFeatures)
{
	static PFN_vkGetPhysicalDeviceFeatures fp = NULL;
	if (!fp) fp = (PFN_vkGetPhysicalDeviceFeatures)vkGetInstanceProcAddr(g_vk_instance, "vkGetPhysicalDeviceFeatures");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkGetPhysicalDeviceFeatures\n"); return; }
	fp(physicalDevice, pFeatures);
}

void vkGetPhysicalDeviceFormatProperties(VkPhysicalDevice physicalDevice, VkFormat format, VkFormatProperties* pFormatProperties)
{
	static PFN_vkGetPhysicalDeviceFormatProperties fp = NULL;
	if (!fp) fp = (PFN_vkGetPhysicalDeviceFormatProperties)vkGetInstanceProcAddr(g_vk_instance, "vkGetPhysicalDeviceFormatProperties");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkGetPhysicalDeviceFormatProperties\n"); return; }
	fp(physicalDevice, format, pFormatProperties);
}

VkResult vkGetPhysicalDeviceImageFormatProperties(VkPhysicalDevice physicalDevice, VkFormat format, VkImageType type, VkImageTiling tiling, VkImageUsageFlags usage, VkImageCreateFlags flags, VkImageFormatProperties* pImageFormatProperties)
{
	static PFN_vkGetPhysicalDeviceImageFormatProperties fp = NULL;
	if (!fp) fp = (PFN_vkGetPhysicalDeviceImageFormatProperties)vkGetInstanceProcAddr(g_vk_instance, "vkGetPhysicalDeviceImageFormatProperties");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkGetPhysicalDeviceImageFormatProperties\n"); return VK_ERROR_INITIALIZATION_FAILED; }
	return fp(physicalDevice, format, type, tiling, usage, flags, pImageFormatProperties);
}

void vkGetPhysicalDeviceMemoryProperties(VkPhysicalDevice physicalDevice, VkPhysicalDeviceMemoryProperties* pMemoryProperties)
{
	static PFN_vkGetPhysicalDeviceMemoryProperties fp = NULL;
	if (!fp) fp = (PFN_vkGetPhysicalDeviceMemoryProperties)vkGetInstanceProcAddr(g_vk_instance, "vkGetPhysicalDeviceMemoryProperties");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkGetPhysicalDeviceMemoryProperties\n"); return; }
	fp(physicalDevice, pMemoryProperties);
}

void vkGetPhysicalDeviceProperties(VkPhysicalDevice physicalDevice, VkPhysicalDeviceProperties* pProperties)
{
	static PFN_vkGetPhysicalDeviceProperties fp = NULL;
	if (!fp) fp = (PFN_vkGetPhysicalDeviceProperties)vkGetInstanceProcAddr(g_vk_instance, "vkGetPhysicalDeviceProperties");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkGetPhysicalDeviceProperties\n"); return; }
	fp(physicalDevice, pProperties);
}

void vkGetPhysicalDeviceQueueFamilyProperties(VkPhysicalDevice physicalDevice, uint32_t* pQueueFamilyPropertyCount, VkQueueFamilyProperties* pQueueFamilyProperties)
{
	static PFN_vkGetPhysicalDeviceQueueFamilyProperties fp = NULL;
	if (!fp) fp = (PFN_vkGetPhysicalDeviceQueueFamilyProperties)vkGetInstanceProcAddr(g_vk_instance, "vkGetPhysicalDeviceQueueFamilyProperties");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkGetPhysicalDeviceQueueFamilyProperties\n"); return; }
	fp(physicalDevice, pQueueFamilyPropertyCount, pQueueFamilyProperties);
}

VkResult vkInvalidateMappedMemoryRanges(VkDevice device, uint32_t memoryRangeCount, const VkMappedMemoryRange* pMemoryRanges)
{
	static PFN_vkInvalidateMappedMemoryRanges fp = NULL;
	if (!fp) fp = (PFN_vkInvalidateMappedMemoryRanges)g_vkGetDeviceProcAddr(g_vk_device, "vkInvalidateMappedMemoryRanges");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkInvalidateMappedMemoryRanges\n"); return VK_ERROR_INITIALIZATION_FAILED; }
	return fp(device, memoryRangeCount, pMemoryRanges);
}

VkResult vkMapMemory(VkDevice device, VkDeviceMemory memory, VkDeviceSize offset, VkDeviceSize size, VkMemoryMapFlags flags, void** ppData)
{
	static PFN_vkMapMemory fp = NULL;
	if (!fp) fp = (PFN_vkMapMemory)g_vkGetDeviceProcAddr(g_vk_device, "vkMapMemory");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkMapMemory\n"); return VK_ERROR_INITIALIZATION_FAILED; }
	return fp(device, memory, offset, size, flags, ppData);
}

VkResult vkQueueSubmit(VkQueue queue, uint32_t submitCount, const VkSubmitInfo* pSubmits, VkFence fence)
{
	static PFN_vkQueueSubmit fp = NULL;
	if (!fp) fp = (PFN_vkQueueSubmit)g_vkGetDeviceProcAddr(g_vk_device, "vkQueueSubmit");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkQueueSubmit\n"); return VK_ERROR_INITIALIZATION_FAILED; }
	return fp(queue, submitCount, pSubmits, fence);
}

VkResult vkResetFences(VkDevice device, uint32_t fenceCount, const VkFence* pFences)
{
	static PFN_vkResetFences fp = NULL;
	if (!fp) fp = (PFN_vkResetFences)g_vkGetDeviceProcAddr(g_vk_device, "vkResetFences");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkResetFences\n"); return VK_ERROR_INITIALIZATION_FAILED; }
	return fp(device, fenceCount, pFences);
}

void vkUnmapMemory(VkDevice device, VkDeviceMemory memory)
{
	static PFN_vkUnmapMemory fp = NULL;
	if (!fp) fp = (PFN_vkUnmapMemory)g_vkGetDeviceProcAddr(g_vk_device, "vkUnmapMemory");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkUnmapMemory\n"); return; }
	fp(device, memory);
}

void vkUpdateDescriptorSets(VkDevice device, uint32_t descriptorWriteCount, const VkWriteDescriptorSet* pDescriptorWrites, uint32_t descriptorCopyCount, const VkCopyDescriptorSet* pDescriptorCopies)
{
	static PFN_vkUpdateDescriptorSets fp = NULL;
	if (!fp) fp = (PFN_vkUpdateDescriptorSets)g_vkGetDeviceProcAddr(g_vk_device, "vkUpdateDescriptorSets");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkUpdateDescriptorSets\n"); return; }
	fp(device, descriptorWriteCount, pDescriptorWrites, descriptorCopyCount, pDescriptorCopies);
}

VkResult vkWaitForFences(VkDevice device, uint32_t fenceCount, const VkFence* pFences, VkBool32 waitAll, uint64_t timeout)
{
	static PFN_vkWaitForFences fp = NULL;
	if (!fp) fp = (PFN_vkWaitForFences)g_vkGetDeviceProcAddr(g_vk_device, "vkWaitForFences");
	if (!fp) { Sys_Printf("vktramp: UNRESOLVED vkWaitForFences\n"); return VK_ERROR_INITIALIZATION_FAILED; }
	return fp(device, fenceCount, pFences, waitAll, timeout);
}
