/*
 * v3dv_harness.c — Vulkan Tier-0 link-closure + first-runtime-contact harness.
 *
 * The Vulkan analog of harness_screen_create.c (GL Path-C Phase 2). It drives the
 * V3DV ICD through the standard Vulkan entry sequence:
 *     vkCreateInstance -> vkEnumeratePhysicalDevices -> vkCreateDevice
 * resolving every entrypoint through vkGetInstanceProcAddr (aliased to
 * v3dv_GetInstanceProcAddr in vk_icd_link.c), exactly as a loader-less client (and
 * later vkQuake) would.
 *
 * Tier 0 GOAL = this links to an aarch64-phoenix ELF with 0 undefined symbols.
 * Tier 1 (main agent, on HW) = it actually runs and prints "vkCreateDevice OK, V3D 4.2".
 *
 * PRECONDITION (HW, Tier 1): the V3D must be powered on (v3d_phoenix_powerOn) before
 * the winsys touches MMIO — wired in the on-device launcher, not this link/smoke build.
 * Device enumeration's drmGetDevices2 scan is bypassed by the mesa-phoenix-port patch
 * (enumerate_devices -> create_physical_device with a FAKE_FD), see the Tier-0 doc.
 *
 * Copyright 2026 Phoenix Systems  %LICENSE%
 */
#include <stdio.h>
#include <string.h>
#include <fcntl.h>
#include <unistd.h>
#include <stdint.h>
#include <sys/ioctl.h>
#include <sys/mman.h>
#include <phoenix/fbcon.h>   /* FBCONSETMODE / FBCON_DISABLED — stop console overdraw of the fb */
#include <vulkan/vulkan.h>
#include "triangle_spirv.h"   /* GENERATED by gen-triangle-spirv.py: triangle_{vert,frag}_spirv[] */
#include "texprobe/texprobe_spirv.h"  /* glslang: texprobe_{vert,frag}_spirv[] — fullscreen-tri UV0..4 + sampler2D */

/* The one symbol the loader-less client needs; vk_icd_link.c aliases it to
 * v3dv_GetInstanceProcAddr (the generated dispatch root). */
PFN_vkVoidFunction vkGetInstanceProcAddr(VkInstance instance, const char *pName);

/* #67 binner-determinism diagnostic getter (winsys, env V3D_BIN_CRC=1). Returns the capture
 * sequence; fills the last bin's tile_alloc (gpuva,size) + CRC32. See v3d_phoenix_winsys.c. */
extern uint32_t v3d_phoenix_last_bin_crc(uint32_t *qma, uint32_t *qms, uint32_t *crc);
#include <stdlib.h>   /* getenv, strtoul, setenv */

/* CRC32 (same poly as the winsys) for the scanout-band render signature (#67 Stage 2). */
static uint32_t h_crc32(const void *buf, uint32_t len)
{
	const uint8_t *p = (const uint8_t *)buf;
	uint32_t crc = 0xffffffffu;
	for (uint32_t i = 0; i < len; i++) {
		crc ^= p[i];
		for (int k = 0; k < 8; k++)
			crc = (crc >> 1) ^ (0xedb88320u & (uint32_t)(-(int32_t)(crc & 1u)));
	}
	return ~crc;
}

#define GIPA(inst, name) ((PFN_##name)vkGetInstanceProcAddr((inst), #name))

int main(void)
{
	/* Unbuffered: a fault must not eat buffered output over the captured UART path. */
	setvbuf(stdout, NULL, _IONBF, 0);
	/* #67 experiment: enable the winsys tile_alloc CRC capture from within this diagnostic
	 * binary (the winsys reads V3D_BIN_CRC lazily on its first submit), so the DET loop works
	 * without depending on psh propagating environ to the spawned child. Harmless (one CRC per
	 * submit). Override V3D_DET_ITERS via psh export if it propagates; else the loop defaults. */
	setenv("V3D_BIN_CRC", "1", 1);
	/* #67 Stage-2 confound removal: disable the HDMI text console (pl011-tty fbcon) so the
	 * async klog/psh mirror cannot overdraw the fb between our render and our band read-back
	 * (it targets the same /dev/fb0). Mirrors quakespasm console_setmode(FBCON_DISABLED). Our
	 * printf still reaches UART (separate from fbcon), so the CHURN lines are still captured. */
	int g_ttyfd = open("/dev/tty0", O_RDWR);
	if (g_ttyfd < 0) g_ttyfd = open("/dev/console", O_RDWR);
	if (g_ttyfd >= 0) {
		if (ioctl(g_ttyfd, FBCONSETMODE, FBCON_DISABLED) == 0)
			printf("v3dv-harness: fbcon DISABLED (no console overdraw)\n");
		else
			printf("v3dv-harness: FBCONSETMODE(DISABLED) failed (console may overdraw!)\n");
	}
	printf("v3dv-harness: start\n");

	PFN_vkCreateInstance pCreateInstance = GIPA(NULL, vkCreateInstance);
	if (!pCreateInstance) {
		printf("v3dv-harness: vkGetInstanceProcAddr(vkCreateInstance) NULL\n");
		return 1;
	}

	const char *exts[] = { "VK_KHR_surface" };
	VkApplicationInfo app = {
		.sType = VK_STRUCTURE_TYPE_APPLICATION_INFO,
		.pApplicationName = "v3dv-tier0",
		.apiVersion = VK_API_VERSION_1_1,
	};
	VkInstanceCreateInfo ici = {
		.sType = VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO,
		.pApplicationInfo = &app,
		/* keep extension count 0 for first-light; surface ext is advertised but the
		 * custom fb0 swapchain is Tier 4. Listed here for reference, not enabled. */
		.enabledExtensionCount = 0,
		.ppEnabledExtensionNames = exts,
	};
	VkInstance inst = VK_NULL_HANDLE;
	VkResult r = pCreateInstance(&ici, NULL, &inst);
	printf("v3dv-harness: vkCreateInstance -> %d\n", (int)r);
	if (r != VK_SUCCESS)
		return 2;

	PFN_vkEnumeratePhysicalDevices pEnum = GIPA(inst, vkEnumeratePhysicalDevices);
	PFN_vkGetPhysicalDeviceProperties pProps = GIPA(inst, vkGetPhysicalDeviceProperties);
	PFN_vkCreateDevice pCreateDevice = GIPA(inst, vkCreateDevice);
	if (!pEnum || !pCreateDevice) {
		printf("v3dv-harness: missing enum/createdevice proc\n");
		return 3;
	}

	uint32_t n = 0;
	r = pEnum(inst, &n, NULL);
	printf("v3dv-harness: vkEnumeratePhysicalDevices -> %d count=%u\n", (int)r, n);
	if (r != VK_SUCCESS || n == 0)
		return 4;

	VkPhysicalDevice phys = VK_NULL_HANDLE;
	n = 1;
	r = pEnum(inst, &n, &phys);
	if (r < 0)
		return 5;

	/* NOTE: vkGetPhysicalDeviceProperties (the vk_common trampoline) dispatches to the
	 * physical-device table's GetPhysicalDeviceProperties2 slot, which is currently NULL
	 * on this build -> instruction abort (pc=0). That is a physical-device-dispatch-table
	 * gap (cosmetic name print), independent of vkCreateDevice (an instance entrypoint
	 * dispatched straight to v3dv_CreateDevice). Skip the name print to reach the real
	 * Tier-1 milestone; the dispatch gap is tracked separately. */
	(void)pProps;
	printf("v3dv-harness: (skipping vkGetPhysicalDeviceProperties name print -- phys-dispatch Properties2 is NULL)\n");

	float prio = 1.0f;
	VkDeviceQueueCreateInfo qci = {
		.sType = VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO,
		.queueFamilyIndex = 0,
		.queueCount = 1,
		.pQueuePriorities = &prio,
	};
	VkPhysicalDeviceFeatures devfeat = { .samplerAnisotropy = VK_TRUE }; /* for the MIPCOL aniso probe (vkQuake enables it) */
	VkDeviceCreateInfo dci = {
		.sType = VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO,
		.queueCreateInfoCount = 1,
		.pQueueCreateInfos = &qci,
		.pEnabledFeatures = &devfeat,
	};
	VkDevice dev = VK_NULL_HANDLE;
	r = pCreateDevice(phys, &dci, NULL, &dev);
	printf("v3dv-harness: vkCreateDevice -> %d\n", (int)r);
	if (r != VK_SUCCESS)
		return 6;

	printf("v3dv-harness: device created OK\n");

	/* --- Tier 2: a real queue submit (empty primary command buffer). This exercises the
	 * V3DV queue -> winsys submit path (ioc_submit_cl, the same synchronous bin/render path
	 * Quake renders through) + the synchronous syncobj/fence stubs (work is done when
	 * ioc_submit_cl returns, so vkQueueWaitIdle returns immediately). Device-level procs
	 * resolve through vkGetDeviceProcAddr (NOT vkGetInstanceProcAddr: in a loader-less
	 * ICD link the latter hands back trampolines that deref a NULL device-dispatch slot
	 * -> pc=0 instruction-abort; GetDeviceProcAddr returns the real device entrypoint). --- */
	PFN_vkGetDeviceProcAddr pGDPA = GIPA(inst, vkGetDeviceProcAddr);
	if (!pGDPA) {
		printf("v3dv-harness: PASS (device created); no vkGetDeviceProcAddr\n");
		return 0;
	}
#define GDPA(d, name) ((PFN_##name)pGDPA((d), #name))
	/* CreateCommandPool / AllocateCommandBuffers / QueueSubmit are vk_common command-pool +
	 * synchronization FRAMEWORK entrypoints; they resolve NULL via vkGetDeviceProcAddr (a
	 * dispatch-table gate bug). The framework itself IS wired by v3dv (v3dv_queue_driver_submit
	 * + v3dv_cmd_buffer_ops), so we DECOUPLE the submit test from that lookup bug by calling the
	 * exported vk_common_* impls directly — exercising the real winsys submit path now. The
	 * dispatch-gate fix is tracked separately (docs/inprogress/2026-06-18-vulkan-v3dv-noop-job-rootcause.md). */
	extern VkResult vk_common_CreateCommandPool(VkDevice, const VkCommandPoolCreateInfo *,
		const VkAllocationCallbacks *, VkCommandPool *);
	extern VkResult vk_common_AllocateCommandBuffers(VkDevice, const VkCommandBufferAllocateInfo *,
		VkCommandBuffer *);
	extern VkResult vk_common_QueueSubmit(VkQueue, uint32_t, const VkSubmitInfo *, VkFence);
	PFN_vkGetDeviceQueue pGetQueue = GDPA(dev, vkGetDeviceQueue);
	PFN_vkCreateCommandPool pCreatePool = vk_common_CreateCommandPool;
	PFN_vkAllocateCommandBuffers pAllocCmd = vk_common_AllocateCommandBuffers;
	PFN_vkBeginCommandBuffer pBegin = GDPA(dev, vkBeginCommandBuffer);
	PFN_vkEndCommandBuffer pEnd = GDPA(dev, vkEndCommandBuffer);
	PFN_vkQueueSubmit pSubmit = vk_common_QueueSubmit;
	PFN_vkQueueWaitIdle pWaitIdle = GDPA(dev, vkQueueWaitIdle);
	printf("v3dv-harness: dproc GetDeviceQueue=%p CreateCommandPool=%p(direct) AllocCmdBufs=%p(direct) "
	       "Begin=%p End=%p QueueSubmit=%p(direct) QueueWaitIdle=%p\n",
	       (void *)pGetQueue, (void *)pCreatePool, (void *)pAllocCmd, (void *)pBegin,
	       (void *)pEnd, (void *)pSubmit, (void *)pWaitIdle);
	if (!pGetQueue || !pCreatePool || !pAllocCmd || !pBegin || !pEnd || !pSubmit || !pWaitIdle) {
		printf("v3dv-harness: PASS (device created); a Tier-2 device proc is NULL (see line above)\n");
		return 0;
	}

	VkQueue queue = VK_NULL_HANDLE;
	pGetQueue(dev, 0, 0, &queue);

	VkCommandPoolCreateInfo pci = {
		.sType = VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO,
		.queueFamilyIndex = 0,
	};
	VkCommandPool pool = VK_NULL_HANDLE;
	r = pCreatePool(dev, &pci, NULL, &pool);
	printf("v3dv-harness: vkCreateCommandPool -> %d\n", (int)r);
	if (r != VK_SUCCESS)
		return 7;

	VkCommandBufferAllocateInfo cbai = {
		.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO,
		.commandPool = pool,
		.level = VK_COMMAND_BUFFER_LEVEL_PRIMARY,
		.commandBufferCount = 1,
	};
	VkCommandBuffer cmd = VK_NULL_HANDLE;
	r = pAllocCmd(dev, &cbai, &cmd);
	printf("v3dv-harness: vkAllocateCommandBuffers -> %d\n", (int)r);
	if (r != VK_SUCCESS)
		return 8;

	/* --- Tier 3: record a REAL render command (vkCmdClearColorImage) so the submit executes
	 * actual GPU work (a clear) — not just the noop job. Image/memory/clear go via the exported
	 * v3dv_/vk_common_ impls directly (same decouple as Tier 2, bypassing the dispatch gate). --- */
	extern VkResult v3dv_CreateImage(VkDevice, const VkImageCreateInfo *, const VkAllocationCallbacks *, VkImage *);
	extern void vk_common_GetImageMemoryRequirements(VkDevice, VkImage, VkMemoryRequirements *);
	extern VkResult v3dv_AllocateMemory(VkDevice, const VkMemoryAllocateInfo *, const VkAllocationCallbacks *, VkDeviceMemory *);
	extern VkResult vk_common_BindImageMemory(VkDevice, VkImage, VkDeviceMemory, VkDeviceSize);
	extern void v3dv_CmdClearColorImage(VkCommandBuffer, VkImage, VkImageLayout, const VkClearColorValue *, uint32_t, const VkImageSubresourceRange *);

	VkImageCreateInfo imgci = {
		.sType = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO,
		.imageType = VK_IMAGE_TYPE_2D,
		.format = VK_FORMAT_R8G8B8A8_UNORM,
		.extent = { 64, 64, 1 },
		.mipLevels = 1,
		.arrayLayers = 1,
		.samples = VK_SAMPLE_COUNT_1_BIT,
		.tiling = VK_IMAGE_TILING_LINEAR,
		.usage = VK_IMAGE_USAGE_TRANSFER_DST_BIT,
		.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED,
	};
	VkImage image = VK_NULL_HANDLE;
	r = v3dv_CreateImage(dev, &imgci, NULL, &image);
	printf("v3dv-harness: vkCreateImage -> %d\n", (int)r);
	if (r != VK_SUCCESS)
		return 12;

	VkMemoryRequirements mreq;
	memset(&mreq, 0, sizeof(mreq));
	vk_common_GetImageMemoryRequirements(dev, image, &mreq);
	printf("v3dv-harness: image mem size=%u typeBits=0x%x\n",
	       (unsigned)mreq.size, (unsigned)mreq.memoryTypeBits);

	uint32_t memType = 0;
	for (uint32_t i = 0; i < 32; i++) {
		if (mreq.memoryTypeBits & (1u << i)) {
			memType = i;
			break;
		}
	}
	VkMemoryAllocateInfo mai = {
		.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO,
		.allocationSize = mreq.size ? mreq.size : (64u * 64u * 4u),
		.memoryTypeIndex = memType,
	};
	VkDeviceMemory mem = VK_NULL_HANDLE;
	r = v3dv_AllocateMemory(dev, &mai, NULL, &mem);
	printf("v3dv-harness: vkAllocateMemory -> %d\n", (int)r);
	if (r != VK_SUCCESS)
		return 13;
	r = vk_common_BindImageMemory(dev, image, mem, 0);
	printf("v3dv-harness: vkBindImageMemory -> %d\n", (int)r);
	if (r != VK_SUCCESS)
		return 14;

	/* --- Tier 4a: a VISIBLE-on-HDMI clear. Back a fullscreen image's memory with the HDMI scanout
	 * surface (winsys one-shot v3d_phoenix_set_next_scanout) so the GPU's clear paints the actual
	 * screen — verified via the HDMI auto-snapshot. Best-effort: if /dev/fb0 isn't available the
	 * offscreen Tier-3 clear above still stands. --- */
	extern void v3d_phoenix_set_scanout(uint32_t pa, uint32_t bytes);
	extern void v3d_phoenix_set_next_scanout(void);
	typedef struct {
		unsigned short width, height, bpp, pitch;
		unsigned long long smemlen, framebuffer;
	} rpi4fb_mode_h;
	VkImage scimg = VK_NULL_HANDLE;
	VkDeviceMemory scmem = VK_NULL_HANDLE;
	int fbfd = open("/dev/fb0", O_WRONLY);
	rpi4fb_mode_h fbmode;
	memset(&fbmode, 0, sizeof(fbmode));
	if (fbfd >= 0 && ioctl(fbfd, _IOR('g', 1, rpi4fb_mode_h), &fbmode) == 0 && fbmode.framebuffer != 0) {
		printf("v3dv-harness: fb0 %ux%u pitch=%u pa=0x%llx size=%llu\n",
		       fbmode.width, fbmode.height, fbmode.pitch,
		       (unsigned long long)fbmode.framebuffer, (unsigned long long)fbmode.smemlen);
		v3d_phoenix_set_scanout((uint32_t)fbmode.framebuffer, (uint32_t)fbmode.smemlen);
		VkImageCreateInfo sci = {
			.sType = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO,
			.imageType = VK_IMAGE_TYPE_2D,
			.format = VK_FORMAT_R8G8B8A8_UNORM,
			.extent = { fbmode.width, fbmode.height, 1 },
			.mipLevels = 1,
			.arrayLayers = 1,
			.samples = VK_SAMPLE_COUNT_1_BIT,
			.tiling = VK_IMAGE_TILING_LINEAR,
			.usage = VK_IMAGE_USAGE_TRANSFER_DST_BIT,
			.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED,
		};
		if (v3dv_CreateImage(dev, &sci, NULL, &scimg) == VK_SUCCESS) {
			VkMemoryRequirements scmreq;
			memset(&scmreq, 0, sizeof(scmreq));
			vk_common_GetImageMemoryRequirements(dev, scimg, &scmreq);
			VkMemoryAllocateInfo scmai = {
				.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO,
				.allocationSize = scmreq.size ? scmreq.size : (uint32_t)fbmode.smemlen,
				.memoryTypeIndex = memType,
			};
			v3d_phoenix_set_next_scanout();   /* the NEXT BO (this image's memory) backs the scanout */
			if (v3dv_AllocateMemory(dev, &scmai, NULL, &scmem) == VK_SUCCESS &&
			    vk_common_BindImageMemory(dev, scimg, scmem, 0) == VK_SUCCESS) {
				printf("v3dv-harness: scanout image %ux%u bound (mem=%u)\n",
				       fbmode.width, fbmode.height, (unsigned)scmreq.size);
			}
			else {
				scimg = VK_NULL_HANDLE;
				printf("v3dv-harness: scanout image alloc/bind FAILED\n");
			}
		}
		else {
			printf("v3dv-harness: scanout vkCreateImage FAILED\n");
		}
	}
	else {
		printf("v3dv-harness: fb0 GETMODE unavailable (offscreen clear only)\n");
	}
	if (fbfd >= 0)
		close(fbfd);

	/* ============================ TEXTURE-SAMPLE PROBE (bug 2) ============================
	 * Create a 256x256 RGBA8 OPTIMAL(UIF) source image, write a KNOWN gradient DIRECTLY into
	 * its BO in canonical UIF (via the same uif_pixel_off the winsys+mesa use — verified
	 * byte-exact), then scaling-blit it to the scanout. A SCALING blit forces v3dv's
	 * blit_shader (TMU sample) path, NOT the TFU. So the HDMI result is the TMU's read of
	 * KNOWN canonical data: a clean scaled gradient => the TMU read is CORRECT (bug is
	 * upstream in vkQuake's data prep); per-fragment noise => the TMU read corrupts known
	 * canonical data (read-side confirmed in isolation). Gated on env VKQ_TEXPROBE. */
	VkImage srcimg = VK_NULL_HANDLE; VkDeviceMemory srcmem = VK_NULL_HANDLE;
	int texprobe = 1; /* always-on probe binary */
	if (texprobe) {
		VkImageCreateInfo tci = {
			.sType = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO,
			.imageType = VK_IMAGE_TYPE_2D,
			.format = VK_FORMAT_R8G8B8A8_UNORM,
			.extent = { 256, 256, 1 }, .mipLevels = 1, .arrayLayers = 1,
			.samples = VK_SAMPLE_COUNT_1_BIT,
			.tiling = VK_IMAGE_TILING_OPTIMAL,
			.usage = VK_IMAGE_USAGE_SAMPLED_BIT | VK_IMAGE_USAGE_TRANSFER_SRC_BIT,
			.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED,
		};
		if (v3dv_CreateImage(dev, &tci, NULL, &srcimg) == VK_SUCCESS) {
			VkMemoryRequirements tmr; memset(&tmr, 0, sizeof(tmr));
			vk_common_GetImageMemoryRequirements(dev, srcimg, &tmr);
			VkMemoryAllocateInfo tmai = { .sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO,
				.allocationSize = tmr.size, .memoryTypeIndex = memType };
			if (v3dv_AllocateMemory(dev, &tmai, NULL, &srcmem) == VK_SUCCESS &&
			    vk_common_BindImageMemory(dev, srcimg, srcmem, 0) == VK_SUCCESS) {
				extern VkResult v3dv_MapMemory(VkDevice, VkDeviceMemory, VkDeviceSize, VkDeviceSize, VkMemoryMapFlags, void **);
				void *tmap = NULL;
				if (v3dv_MapMemory(dev, srcmem, 0, VK_WHOLE_SIZE, 0, &tmap) == VK_SUCCESS && tmap) {
					/* canonical UIF pixel offset (cpp=4), transcribed from mesa v3d_tiling.c;
					 * 256x256 => UIF_XOR (xor=1), padded_height=256. */
					uint32_t *bo = (uint32_t *)tmap;
					const uint32_t H = 256, W = 256; const int xr = 1;
					for (uint32_t y = 0; y < H; y++) for (uint32_t x = 0; x < W; x++) {
						uint32_t mbx = x >> 3, mby = y >> 3, px = x & 7, py = y & 7;
						uint32_t MBY = mby; if (xr && ((mbx / 4) & 1)) MBY ^= 0x10u;
						uint32_t mbh = (H + 7) >> 3;
						uint32_t mbid = ((mbx / 4) * ((mbh - 1) * 4)) + mbx + MBY * 4;
						uint32_t off = mbid * 256u + ((py < 4) ? 0u : 128u) + ((px < 4) ? 0u : 64u)
						             + ((px & 3) * 4u + (py & 3) * 16u);
						/* known COLORED HIGH-FREQ pattern (period 32, distinct channels):
						 * R=(x&31)<<3, G=(y&31)<<3, B=((x+y)&31)<<3, A=255. Exercises BUG2's
						 * variation-scaled static scramble on COLOURED data (mid-gray checker
						 * was CLEAN; vkQuake textures are coloured). Decodable per-fragment. */
						uint32_t Rv = (x & 0x1fu) << 3, Gv = (y & 0x1fu) << 3, Bv = ((x + y) & 0x1fu) << 3;
						bo[off / 4u] = Rv | (Gv << 8) | (Bv << 16) | (255u << 24);
					}
					__asm__ volatile("dsb sy" ::: "memory");
					printf("v3dv-harness: TEXPROBE wrote 256x256 UIF gradient to source BO\n");
				} else printf("v3dv-harness: TEXPROBE MapMemory FAILED\n");
			} else { srcimg = VK_NULL_HANDLE; printf("v3dv-harness: TEXPROBE alloc/bind FAILED\n"); }
		} else printf("v3dv-harness: TEXPROBE CreateImage FAILED\n");
	}
	/* offscreen LINEAR dst for a DETERMINISTIC CPU readback (avoids the scanout/#67 race) */
	VkImage dstimg = VK_NULL_HANDLE; VkDeviceMemory dstmem = VK_NULL_HANDLE;
	if (texprobe && srcimg != VK_NULL_HANDLE) {
		VkImageCreateInfo dci = {
			.sType = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO, .imageType = VK_IMAGE_TYPE_2D,
			.format = VK_FORMAT_R8G8B8A8_UNORM, .extent = { 512, 512, 1 },
			.mipLevels = 1, .arrayLayers = 1, .samples = VK_SAMPLE_COUNT_1_BIT,
			.tiling = VK_IMAGE_TILING_LINEAR,
			.usage = VK_IMAGE_USAGE_TRANSFER_DST_BIT,
			.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED,
		};
		if (v3dv_CreateImage(dev, &dci, NULL, &dstimg) == VK_SUCCESS) {
			VkMemoryRequirements dmr; memset(&dmr, 0, sizeof(dmr));
			vk_common_GetImageMemoryRequirements(dev, dstimg, &dmr);
			VkMemoryAllocateInfo dmai = { .sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO,
				.allocationSize = dmr.size, .memoryTypeIndex = memType };
			if (!(v3dv_AllocateMemory(dev, &dmai, NULL, &dstmem) == VK_SUCCESS &&
			      vk_common_BindImageMemory(dev, dstimg, dstmem, 0) == VK_SUCCESS)) {
				dstimg = VK_NULL_HANDLE; printf("v3dv-harness: TEXPROBE dst alloc/bind FAILED\n");
			} else printf("v3dv-harness: TEXPROBE offscreen dst 512x512 LINEAR bound\n");
		} else { dstimg = VK_NULL_HANDLE; printf("v3dv-harness: TEXPROBE dst CreateImage FAILED\n"); }
	}

	/* --- Tier 4b: a real GRAPHICS PIPELINE + triangle. A render pass (loadOp=CLEAR,
	 * storeOp=STORE) into the scanout-backed image, a graphics pipeline built from
	 * hand-authored SPIR-V vertex+fragment shaders (triangle_spirv.h, validated offline
	 * with spirv2nir) compiled by v3dv's spirv_to_nir -> v3d_compile (NIR->QPU) path, and
	 * a vertexless vkCmdDraw(3). If the V3D executes the user shaders, the triangle's
	 * interpolated R/G/B colors land on the scanout (over the magenta clear). This is the
	 * first user-shader GPU render through Vulkan on Phoenix — the vkQuake prerequisite.
	 *
	 * Everything goes through the exported v3dv_/vk_common_ impls directly (same decouple
	 * as Tiers 2/3, bypassing the GetDeviceProcAddr dispatch gate). --- */
	extern VkResult v3dv_CreateImageView(VkDevice, const VkImageViewCreateInfo *, const VkAllocationCallbacks *, VkImageView *);
	extern VkResult v3dv_CreateRenderPass2(VkDevice, const VkRenderPassCreateInfo2 *, const VkAllocationCallbacks *, VkRenderPass *);
	extern VkResult v3dv_CreateFramebuffer(VkDevice, const VkFramebufferCreateInfo *, const VkAllocationCallbacks *, VkFramebuffer *);
	extern VkResult vk_common_CreateShaderModule(VkDevice, const VkShaderModuleCreateInfo *, const VkAllocationCallbacks *, VkShaderModule *);
	extern VkResult v3dv_CreatePipelineLayout(VkDevice, const VkPipelineLayoutCreateInfo *, const VkAllocationCallbacks *, VkPipelineLayout *);
	extern VkResult v3dv_CreateGraphicsPipelines(VkDevice, VkPipelineCache, uint32_t, const VkGraphicsPipelineCreateInfo *, const VkAllocationCallbacks *, VkPipeline *);
	extern void v3dv_CmdBeginRenderPass2(VkCommandBuffer, const VkRenderPassBeginInfo *, const VkSubpassBeginInfo *);
	extern void v3dv_CmdEndRenderPass2(VkCommandBuffer, const VkSubpassEndInfo *);
	extern void v3dv_CmdBindPipeline(VkCommandBuffer, VkPipelineBindPoint, VkPipeline);
	extern void v3dv_CmdDraw(VkCommandBuffer, uint32_t, uint32_t, uint32_t, uint32_t);

	VkImageView scview = VK_NULL_HANDLE;
	VkRenderPass rpass = VK_NULL_HANDLE;
	VkFramebuffer fbobj = VK_NULL_HANDLE;
	VkPipeline pipeline = VK_NULL_HANDLE;
	int tri_ready = 0;
	if (scimg != VK_NULL_HANDLE) {
		do {
			VkImageViewCreateInfo vci = {
				.sType = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO,
				.image = scimg,
				.viewType = VK_IMAGE_VIEW_TYPE_2D,
				.format = VK_FORMAT_R8G8B8A8_UNORM,
				.subresourceRange = { VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, 1 },
			};
			if (v3dv_CreateImageView(dev, &vci, NULL, &scview) != VK_SUCCESS) {
				printf("v3dv-harness: CreateImageView FAILED\n"); break;
			}

			/* Single color attachment: CLEAR on load, STORE on end. loadOp=CLEAR is the
			 * same TLB clear Tier-4a proved; storeOp=STORE writes the RCL tile store to the
			 * (LINEAR/RASTER) scanout BO, the path the clear already proved lands. */
			VkAttachmentDescription2 att = {
				.sType = VK_STRUCTURE_TYPE_ATTACHMENT_DESCRIPTION_2,
				.format = VK_FORMAT_R8G8B8A8_UNORM,
				.samples = VK_SAMPLE_COUNT_1_BIT,
				.loadOp = VK_ATTACHMENT_LOAD_OP_CLEAR,
				.storeOp = VK_ATTACHMENT_STORE_OP_STORE,
				.stencilLoadOp = VK_ATTACHMENT_LOAD_OP_DONT_CARE,
				.stencilStoreOp = VK_ATTACHMENT_STORE_OP_DONT_CARE,
				.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED,
				.finalLayout = VK_IMAGE_LAYOUT_GENERAL,
			};
			VkAttachmentReference2 attref = {
				.sType = VK_STRUCTURE_TYPE_ATTACHMENT_REFERENCE_2,
				.attachment = 0,
				.layout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL,
			};
			VkSubpassDescription2 sub = {
				.sType = VK_STRUCTURE_TYPE_SUBPASS_DESCRIPTION_2,
				.pipelineBindPoint = VK_PIPELINE_BIND_POINT_GRAPHICS,
				.colorAttachmentCount = 1,
				.pColorAttachments = &attref,
			};
			VkRenderPassCreateInfo2 rpci = {
				.sType = VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO_2,
				.attachmentCount = 1,
				.pAttachments = &att,
				.subpassCount = 1,
				.pSubpasses = &sub,
			};
			if (v3dv_CreateRenderPass2(dev, &rpci, NULL, &rpass) != VK_SUCCESS) {
				printf("v3dv-harness: CreateRenderPass2 FAILED\n"); break;
			}

			VkFramebufferCreateInfo fbci = {
				.sType = VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO,
				.renderPass = rpass,
				.attachmentCount = 1,
				.pAttachments = &scview,
				.width = fbmode.width,
				.height = fbmode.height,
				.layers = 1,
			};
			if (v3dv_CreateFramebuffer(dev, &fbci, NULL, &fbobj) != VK_SUCCESS) {
				printf("v3dv-harness: CreateFramebuffer FAILED\n"); break;
			}

			/* shader modules from the hand-authored SPIR-V (spirv_to_nir -> v3d_compile) */
			VkShaderModuleCreateInfo vsci = {
				.sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO,
				.codeSize = sizeof(triangle_vert_spirv),
				.pCode = triangle_vert_spirv,
			};
			VkShaderModuleCreateInfo fsci = {
				.sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO,
				.codeSize = sizeof(triangle_frag_spirv),
				.pCode = triangle_frag_spirv,
			};
			VkShaderModule vsmod = VK_NULL_HANDLE, fsmod = VK_NULL_HANDLE;
			if (vk_common_CreateShaderModule(dev, &vsci, NULL, &vsmod) != VK_SUCCESS ||
			    vk_common_CreateShaderModule(dev, &fsci, NULL, &fsmod) != VK_SUCCESS) {
				printf("v3dv-harness: CreateShaderModule FAILED\n"); break;
			}
			printf("v3dv-harness: shader modules created (vs=%uB fs=%uB)\n",
			       (unsigned)sizeof(triangle_vert_spirv), (unsigned)sizeof(triangle_frag_spirv));

			VkPipelineLayoutCreateInfo plci = { .sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO };
			VkPipelineLayout playout = VK_NULL_HANDLE;
			if (v3dv_CreatePipelineLayout(dev, &plci, NULL, &playout) != VK_SUCCESS) {
				printf("v3dv-harness: CreatePipelineLayout FAILED\n"); break;
			}

			VkPipelineShaderStageCreateInfo stages[2] = {
				{ .sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO,
				  .stage = VK_SHADER_STAGE_VERTEX_BIT, .module = vsmod, .pName = "main" },
				{ .sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO,
				  .stage = VK_SHADER_STAGE_FRAGMENT_BIT, .module = fsmod, .pName = "main" },
			};
			/* vertexless: no bindings/attributes (VS uses gl_VertexIndex) */
			VkPipelineVertexInputStateCreateInfo vis = {
				.sType = VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO,
			};
			VkPipelineInputAssemblyStateCreateInfo ias = {
				.sType = VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO,
				.topology = VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST,
			};
			VkViewport vp = { 0.0f, 0.0f, (float)fbmode.width, (float)fbmode.height, 0.0f, 1.0f };
			VkRect2D sc = { { 0, 0 }, { fbmode.width, fbmode.height } };
			VkPipelineViewportStateCreateInfo vps = {
				.sType = VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO,
				.viewportCount = 1, .pViewports = &vp,
				.scissorCount = 1, .pScissors = &sc,
			};
			VkPipelineRasterizationStateCreateInfo rs = {
				.sType = VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO,
				.polygonMode = VK_POLYGON_MODE_FILL,
				.cullMode = VK_CULL_MODE_NONE,
				.frontFace = VK_FRONT_FACE_COUNTER_CLOCKWISE,
				.lineWidth = 1.0f,
			};
			VkPipelineMultisampleStateCreateInfo ms = {
				.sType = VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO,
				.rasterizationSamples = VK_SAMPLE_COUNT_1_BIT,
			};
			VkPipelineColorBlendAttachmentState cba = { .colorWriteMask = 0xf };
			VkPipelineColorBlendStateCreateInfo cb = {
				.sType = VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO,
				.attachmentCount = 1, .pAttachments = &cba,
			};
			VkGraphicsPipelineCreateInfo gpci = {
				.sType = VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO,
				.stageCount = 2, .pStages = stages,
				.pVertexInputState = &vis,
				.pInputAssemblyState = &ias,
				.pViewportState = &vps,
				.pRasterizationState = &rs,
				.pMultisampleState = &ms,
				.pColorBlendState = &cb,
				.layout = playout,
				.renderPass = rpass,
				.subpass = 0,
			};
			VkResult pr = v3dv_CreateGraphicsPipelines(dev, VK_NULL_HANDLE, 1, &gpci, NULL, &pipeline);
			printf("v3dv-harness: vkCreateGraphicsPipelines -> %d\n", (int)pr);
			if (pr != VK_SUCCESS) { pipeline = VK_NULL_HANDLE; break; }
			tri_ready = 1;
		} while (0);
	}

	VkCommandBufferBeginInfo bbi = {
		.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO,
		/* NOT ONE_TIME_SUBMIT: the #67 determinism loop below re-submits this identical
		 * recorded command buffer N times (a fixed scene) to check binner determinism. */
		.flags = 0,
	};
	r = pBegin(cmd, &bbi);
	if (r != VK_SUCCESS) {
		printf("v3dv-harness: vkBeginCommandBuffer -> %d\n", (int)r);
		return 9;
	}
	VkClearColorValue clearColor = { .float32 = { 0.0f, 0.5f, 1.0f, 1.0f } };
	VkImageSubresourceRange range = {
		.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT,
		.baseMipLevel = 0,
		.levelCount = 1,
		.baseArrayLayer = 0,
		.layerCount = 1,
	};
	v3dv_CmdClearColorImage(cmd, image, VK_IMAGE_LAYOUT_GENERAL, &clearColor, 1, &range);
	if (tri_ready) {
		/* The real Tier-4b path: a render pass whose loadOp=CLEAR paints the scanout
		 * attachment magenta, then the graphics pipeline draws the vertexless triangle.
		 * The VS+FS (hand-authored SPIR-V) are compiled spirv_to_nir -> v3d_compile
		 * (NIR->QPU) and EXECUTED on the V3D; storeOp=STORE writes the rendered tiles to
		 * the scanout BO -> an R/G/B-interpolated triangle over magenta on HDMI. This is
		 * the first user-shader GPU render through Vulkan on Phoenix. */
		VkClearValue cv = { .color = { .float32 = { 1.0f, 0.0f, 0.5f, 1.0f } } }; /* magenta */
		VkRenderPassBeginInfo rpbi = {
			.sType = VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO,
			.renderPass = rpass,
			.framebuffer = fbobj,
			.renderArea = { { 0, 0 }, { fbmode.width, fbmode.height } },
			.clearValueCount = 1,
			.pClearValues = &cv,
		};
		VkSubpassBeginInfo sbi = {
			.sType = VK_STRUCTURE_TYPE_SUBPASS_BEGIN_INFO,
			.contents = VK_SUBPASS_CONTENTS_INLINE,
		};
		VkSubpassEndInfo sei = { .sType = VK_STRUCTURE_TYPE_SUBPASS_END_INFO };
		v3dv_CmdBeginRenderPass2(cmd, &rpbi, &sbi);
		v3dv_CmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, pipeline);
		v3dv_CmdDraw(cmd, 3, 1, 0, 0); /* vertexless: VS builds 3 verts from gl_VertexIndex */
		v3dv_CmdEndRenderPass2(cmd, &sei);
		printf("v3dv-harness: recorded render pass + vertexless triangle draw (user VS+FS)\n");
	}
	else if (scimg != VK_NULL_HANDLE) {
		/* Fallback (pipeline build failed): plain scanout clear so HDMI still shows a
		 * deterministic Tier-4a result instead of a blank/garbage frame. */
		VkClearColorValue scColor = { .float32 = { 1.0f, 0.0f, 0.5f, 1.0f } }; /* magenta */
		v3dv_CmdClearColorImage(cmd, scimg, VK_IMAGE_LAYOUT_GENERAL, &scColor, 1, &range);
		printf("v3dv-harness: triangle pipeline not ready -> fallback magenta clear\n");
	}
	if (texprobe && srcimg != VK_NULL_HANDLE && dstimg != VK_NULL_HANDLE) {
		extern void v3dv_CmdPipelineBarrier2(VkCommandBuffer, const VkDependencyInfo *);
		extern void v3dv_CmdBlitImage2(VkCommandBuffer, const VkBlitImageInfo2 *);
		/* transition src + offscreen dst UNDEFINED->GENERAL */
		VkImageMemoryBarrier2 b[2] = {
			{ .sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER_2,
			  .srcStageMask = VK_PIPELINE_STAGE_2_ALL_COMMANDS_BIT, .dstStageMask = VK_PIPELINE_STAGE_2_ALL_COMMANDS_BIT,
			  .dstAccessMask = VK_ACCESS_2_SHADER_SAMPLED_READ_BIT | VK_ACCESS_2_TRANSFER_READ_BIT,
			  .oldLayout = VK_IMAGE_LAYOUT_UNDEFINED, .newLayout = VK_IMAGE_LAYOUT_GENERAL,
			  .image = srcimg, .subresourceRange = { VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, 1 } },
			{ .sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER_2,
			  .srcStageMask = VK_PIPELINE_STAGE_2_ALL_COMMANDS_BIT, .dstStageMask = VK_PIPELINE_STAGE_2_ALL_COMMANDS_BIT,
			  .dstAccessMask = VK_ACCESS_2_TRANSFER_WRITE_BIT,
			  .oldLayout = VK_IMAGE_LAYOUT_UNDEFINED, .newLayout = VK_IMAGE_LAYOUT_GENERAL,
			  .image = dstimg, .subresourceRange = { VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, 1 } },
		};
		VkDependencyInfo dep = { .sType = VK_STRUCTURE_TYPE_DEPENDENCY_INFO,
			.imageMemoryBarrierCount = 2, .pImageMemoryBarriers = b };
		v3dv_CmdPipelineBarrier2(cmd, &dep);
		/* MINIFYING blit 256->64 (4x downscale = HIGH texcoord derivative, the vkQuake-wall
		 * regime; source is COLORED HIGH-FREQ). NEAREST: dst(dx,dy) samples src(dx*4+2,dy*4+2).
		 * Per-fragment RGB check (below, minified expected) tests BUG2 on high-deriv coloured
		 * sampling — the one regime the clean magnify/1:1 probes never exercised. */
		VkImageBlit2 region = {
			.sType = VK_STRUCTURE_TYPE_IMAGE_BLIT_2,
			.srcSubresource = { VK_IMAGE_ASPECT_COLOR_BIT, 0, 0, 1 },
			.srcOffsets = { { 0, 0, 0 }, { 256, 256, 1 } },
			.dstSubresource = { VK_IMAGE_ASPECT_COLOR_BIT, 0, 0, 1 },
			.dstOffsets = { { 0, 0, 0 }, { 64, 64, 1 } },
		};
		VkBlitImageInfo2 bi = {
			.sType = VK_STRUCTURE_TYPE_BLIT_IMAGE_INFO_2,
			.srcImage = srcimg, .srcImageLayout = VK_IMAGE_LAYOUT_GENERAL,
			.dstImage = dstimg, .dstImageLayout = VK_IMAGE_LAYOUT_GENERAL,
			.regionCount = 1, .pRegions = &region, .filter = VK_FILTER_NEAREST,
		};
		v3dv_CmdBlitImage2(cmd, &bi);
		printf("v3dv-harness: TEXPROBE recorded scaling blit 256->512 to offscreen (TMU sample)\n");
	}

	r = pEnd(cmd);
	printf("v3dv-harness: record clear cmd buffer -> %d\n", (int)r);
	if (r != VK_SUCCESS)
		return 9;

	VkSubmitInfo si = {
		.sType = VK_STRUCTURE_TYPE_SUBMIT_INFO,
		.commandBufferCount = 1,
		.pCommandBuffers = &cmd,
	};
	r = pSubmit(queue, 1, &si, VK_NULL_HANDLE);
	printf("v3dv-harness: vkQueueSubmit -> %d\n", (int)r);
	if (r != VK_SUCCESS)
		return 10;

	r = pWaitIdle(queue);
	printf("v3dv-harness: vkQueueWaitIdle -> %d\n", (int)r);
	if (r != VK_SUCCESS)
		return 11;

	/* Tier 3 verification: the image memory (type 0) is HOST_VISIBLE + the winsys BO is uncached,
	 * so map it and read pixel 0 — it must hold the clear color. R8G8B8A8_UNORM {0,0.5,1,1} stores
	 * bytes ~00 80 ff ff (or bgra ff 80 00 ff). A non-trivial pattern proves the GPU actually wrote
	 * the clear (not just executed without fault). */
	extern VkResult v3dv_MapMemory(VkDevice, VkDeviceMemory, VkDeviceSize, VkDeviceSize, VkMemoryMapFlags, void **);
	void *mapped = NULL;
	r = v3dv_MapMemory(dev, mem, 0, VK_WHOLE_SIZE, 0, &mapped);
	if (r == VK_SUCCESS && mapped != NULL) {
		const unsigned char *px = (const unsigned char *)mapped;
		printf("v3dv-harness: clear readback px0 = %02x %02x %02x %02x (expect ~00 80 ff ff / bgra ff 80 00 ff)\n",
		       px[0], px[1], px[2], px[3]);
	}
	else {
		printf("v3dv-harness: clear readback skipped (vkMapMemory -> %d)\n", (int)r);
	}

	/* Tier 4a verification (deterministic, independent of fbcon overdraw / snapshot timing): read the
	 * LIVE scanout framebuffer's physical memory. If the GPU's scanout clear landed, pixel 0 holds the
	 * magenta clear {1,0,0.5,1} = bytes ff 00 80 ff (R8G8B8A8). The HDMI auto-snapshot may also show it. */
	if (scimg != VK_NULL_HANDLE && fbmode.framebuffer != 0) {
		volatile unsigned char *fb = mmap(NULL, 4096, PROT_READ,
			MAP_PHYSMEM | MAP_UNCACHED | MAP_ANONYMOUS, -1, (off_t)fbmode.framebuffer);
		if (fb != MAP_FAILED) {
			/* px0 is the top-left CORNER, outside the centered triangle -> it holds the
			 * magenta clear (ff 00 80 ff) whether or not the triangle drew. The triangle
			 * itself (R/G/B interpolated, center screen) is verified via the HDMI snapshot;
			 * the vkCreateGraphicsPipelines/QueueSubmit/WaitIdle return codes above prove the
			 * shader compiled + the render pass executed without fault. */
			printf("v3dv-harness: scanout fb px0(corner) = %02x %02x %02x %02x (expect magenta ff 00 80 ff = clear; "
			       "triangle is center-screen -> check HDMI snapshot)\n",
			       fb[0], fb[1], fb[2], fb[3]);
			munmap((void *)fb, 4096);
		}
		/* (deterministic offscreen TEXPROBE readback is below, independent of the scanout/HDMI/binner) */
	}

	/* TEXPROBE deterministic offscreen readback (no scanout/HDMI/binner race): the blit scaled the
	 * 256x256 UIF gradient (src texel (x,y) -> R=x,G=y,B=128) to the 512x512 LINEAR dst. Map the dst
	 * and CPU-compare a grid: dst pixel (dx,dy) sampled src texel (dx/2,dy/2) => expect R=dx/2,G=dy/2.
	 * 0 mismatch => the TMU read of known UIF data is CORRECT (bug is UPSTREAM of the read, in vkQuake's
	 * real texture-data prep); many => the TMU read itself corrupts known UIF data (read-side confirmed). */
	if (texprobe && dstimg != VK_NULL_HANDLE && dstmem != VK_NULL_HANDLE) {
		extern void vk_common_GetImageSubresourceLayout(VkDevice, VkImage,
			const VkImageSubresource *, VkSubresourceLayout *);
		VkImageSubresource sub = { VK_IMAGE_ASPECT_COLOR_BIT, 0, 0 };
		VkSubresourceLayout lay = { 0 };
		vk_common_GetImageSubresourceLayout(dev, dstimg, &sub, &lay);
		void *dmap = NULL;
		r = v3dv_MapMemory(dev, dstmem, 0, VK_WHOLE_SIZE, 0, &dmap);
		if (r == VK_SUCCESS && dmap != NULL) {
			const unsigned char *base = (const unsigned char *)dmap + (size_t)lay.offset;
			uint32_t pitch = (uint32_t)lay.rowPitch;
			uint32_t chk = 0, mm = 0, rsum = 0;
			char ex[256]; int el = 0;
			for (uint32_t dy = 2; dy < 64; dy += 4)
				for (uint32_t dx = 2; dx < 64; dx += 4) {
					uint32_t sx = dx * 4u + 2u, sy = dy * 4u + 2u;   /* 256->64 NEAREST minify: src texel */
					/* COLORED HIGH-FREQ expected (matches the source fill formula) */
					uint32_t eR = (sx & 0x1fu) << 3, eG = (sy & 0x1fu) << 3, eB = ((sx + sy) & 0x1fu) << 3;
					const unsigned char *p = base + (size_t)dy * pitch + (size_t)dx * 4u;
					int dr = (int)p[0] - (int)eR, dg = (int)p[1] - (int)eG, db = (int)p[2] - (int)eB;
					chk++; rsum += p[0];
					if (dr < -12 || dr > 12 || dg < -12 || dg > 12 || db < -12 || db > 12) {
						mm++;
						if (el < 200) el += snprintf(ex + el, sizeof(ex) - el,
							" (%u,%u:exp %u,%u,%u got %u,%u,%u)", dx, dy, eR, eG, eB, p[0], p[1], p[2]);
					}
				}
			printf("v3dv-harness: TEXPROBE OFFSCREEN %s  mismatch=%u/%u meanR=%u pitch=%u off=%u%s\n",
			       mm == 0 ? "CLEAN(read-correct)" : "NOISE(read-corrupt)",
			       mm, chk, chk ? rsum / chk : 0, pitch, (uint32_t)lay.offset, mm ? ex : "");

			/* DYNPROBE-MINIFY (2026-07-30): re-submit the SAME cmd buffer (contains the 256->64
			 * MINIFYING TMU blit = high texcoord derivative) 4x and byte-compare the 64x64 written
			 * region to iter0. This exercises the high-dUV regime the 1:1 checker did not. Differing
			 * bytes across identical submits == per-frame race reproduced in the minified/high-deriv
			 * path (the vkQuake-wall regime). Identical == minification alone is not the trigger. */
			{
				const uint32_t RW = 64, RH = 64;
				size_t rgnbytes = (size_t)RH * (size_t)RW * 4u;
				unsigned char *snap = malloc(rgnbytes);
				if (snap) {
					for (uint32_t yy = 0; yy < RH; yy++)
						memcpy(snap + (size_t)yy*RW*4u, base + (size_t)yy*pitch, (size_t)RW*4u);
					for (int it = 1; it <= 4; it++) {
						VkSubmitInfo sM = { .sType = VK_STRUCTURE_TYPE_SUBMIT_INFO,
							.commandBufferCount = 1, .pCommandBuffers = &cmd };
						pSubmit(queue, 1, &sM, VK_NULL_HANDLE);
						pWaitIdle(queue);
						__asm__ volatile("dsb sy" ::: "memory");
						uint32_t diff = 0, maxd = 0;
						for (uint32_t yy = 0; yy < RH; yy++)
							for (uint32_t xx = 0; xx < RW*4u; xx++) {
								int d = (int)base[(size_t)yy*pitch+xx] - (int)snap[(size_t)yy*RW*4u+xx];
								if (d < 0) d = -d;
								if (d) { diff++; if ((uint32_t)d > maxd) maxd = d; }
							}
						printf("v3dv-harness: DYNPROBE-MINIFY iter %d vs 0: %u/%zu bytes differ (maxd=%u) => %s\n",
						       it, diff, rgnbytes, maxd,
						       diff ? "NONDETERMINISTIC (race reproduced in minified/high-deriv path)"
						            : "deterministic");
					}
					free(snap);
				}
			}
		}
		else {
			printf("v3dv-harness: TEXPROBE offscreen readback skipped (vkMapMemory -> %d)\n", (int)r);
		}
	}

	/* ============ TEXPROBE HIGH-FREQUENCY CHECKERBOARD 1:1 (discriminating read-side probe #4) ============
	 * Probes #1-3 all came back CLEAN, but all used LOW-FREQUENCY data (gradient / solid / smooth ramp).
	 * The durable observation is the speckle SCALES WITH texel-to-texel VARIATION -> a coordinate/lane
	 * permutation whose error is proportional to local variation makes SMOOTH output on smooth input BY
	 * CONSTRUCTION. So the variation-scaled hypothesis was untested. This probe uses a HIGH-CONTRAST
	 * 1-texel CHECKERBOARD (0x00 <-> 0xff) sampled 1:1 with NEAREST/NEAREST at LOD 0 (no aliasing, no
	 * LINEAR blur): the fullscreen tri makes the VISIBLE UV range 0..2 over the viewport (tri extends to
	 * NDC 3), so a 128^2 source over a 256^2 dst gives unnormalized coord dx+0.5 -> texel (dx mod 128), a
	 * true 1:1 map (checker period 1px != 2x2-quad period 2px, so a quad-coord-collapse bug is VISIBLE as
	 * 2x2 blocks; a 64^2 source would 2x-magnify and HIDE it). A correct checkerboard ALTERNATES with
	 * every one of its 4 neighbors; a per-fragment coordinate/addressing permutation samples a wrong-parity
	 * texel and creates EQUAL-neighbor DEFECTS. Detection = count interior px matching ANY 4-neighbor
	 * (robust to a harmless global shift/inversion, which preserves alternation). DEFECT-FREE => the
	 * high-frequency read is CLEAN too => sample/data path genuinely exonerated (go to vkQuake's specific
	 * multi-texture draw / gallium-vs-v3dv diff). DEFECTS => standalone read-side repro with full data
	 * control (bisect from here). Also report black/white split + mean (all-gray => unexpected LINEAR blur). */
	if (texprobe) do {
		const uint32_t MSZ = 256, MLEVELS = 9, DSTW = 512, DSTH = 512;   /* 256^2 => UIF_XOR tiling */
		extern VkResult v3dv_CreateSampler(VkDevice, const VkSamplerCreateInfo *, const VkAllocationCallbacks *, VkSampler *);
		extern VkResult v3dv_CreateDescriptorSetLayout(VkDevice, const VkDescriptorSetLayoutCreateInfo *, const VkAllocationCallbacks *, VkDescriptorSetLayout *);
		extern VkResult v3dv_CreateDescriptorPool(VkDevice, const VkDescriptorPoolCreateInfo *, const VkAllocationCallbacks *, VkDescriptorPool *);
		extern VkResult v3dv_AllocateDescriptorSets(VkDevice, const VkDescriptorSetAllocateInfo *, VkDescriptorSet *);
		extern void v3dv_UpdateDescriptorSets(VkDevice, uint32_t, const VkWriteDescriptorSet *, uint32_t, const VkCopyDescriptorSet *);
		extern void v3dv_CmdBindDescriptorSets(VkCommandBuffer, VkPipelineBindPoint, VkPipelineLayout, uint32_t, uint32_t, const VkDescriptorSet *, uint32_t, const uint32_t *);
		extern void vk_common_CmdCopyBufferToImage(VkCommandBuffer, VkBuffer, VkImage, VkImageLayout, uint32_t, const VkBufferImageCopy *);
		extern VkResult v3dv_CreateBuffer(VkDevice, const VkBufferCreateInfo *, const VkAllocationCallbacks *, VkBuffer *);
		extern void vk_common_GetBufferMemoryRequirements(VkDevice, VkBuffer, VkMemoryRequirements *);
		extern VkResult vk_common_BindBufferMemory(VkDevice, VkBuffer, VkDeviceMemory, VkDeviceSize);
		extern void v3dv_CmdPipelineBarrier2(VkCommandBuffer, const VkDependencyInfo *);
		extern void vk_common_GetImageSubresourceLayout(VkDevice, VkImage, const VkImageSubresource *, VkSubresourceLayout *);

		/* 1) mip-chained SAMPLED source */
		VkImage mipsrc = VK_NULL_HANDLE; VkDeviceMemory mipmem = VK_NULL_HANDLE;
		VkImageCreateInfo mici = {
			.sType = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO, .imageType = VK_IMAGE_TYPE_2D,
			.format = VK_FORMAT_R8G8B8A8_UNORM, .extent = { MSZ, MSZ, 1 },
			.mipLevels = MLEVELS, .arrayLayers = 1, .samples = VK_SAMPLE_COUNT_1_BIT,
			.tiling = VK_IMAGE_TILING_OPTIMAL,
			.usage = VK_IMAGE_USAGE_SAMPLED_BIT | VK_IMAGE_USAGE_TRANSFER_DST_BIT,
			.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED,
		};
		if (v3dv_CreateImage(dev, &mici, NULL, &mipsrc) != VK_SUCCESS) { printf("MIPCOL: CreateImage src FAIL\n"); break; }
		VkMemoryRequirements mmr; memset(&mmr, 0, sizeof(mmr));
		vk_common_GetImageMemoryRequirements(dev, mipsrc, &mmr);
		/* TEXPROBE: bind at a NON-ZERO heap-style offset (= reported alignment), like vkQuake's
		 * GL_HeapAllocate sub-allocation, instead of offset 0. If v3dv under-reports the alignment a
		 * UIF-tiled image needs, this misaligns the tiling => the TMU reads shifted rows (striping). */
		/* bind at 4096-aligned but NOT 16KB(page-cache)-aligned offset: for a UIF_XOR image this
		 * violates the XOR macroblock base-alignment if v3dv under-reports alignment (hardcoded 4096). */
		VkDeviceSize texoff = 4096;
		VkMemoryAllocateInfo mmai = { .sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO, .allocationSize = mmr.size + texoff, .memoryTypeIndex = memType };
		printf("v3dv-harness: MIPCOL src memReq size=%llu align=%llu -> binding at offset=%llu\n",
		       (unsigned long long)mmr.size, (unsigned long long)mmr.alignment, (unsigned long long)texoff);
		if (v3dv_AllocateMemory(dev, &mmai, NULL, &mipmem) != VK_SUCCESS || vk_common_BindImageMemory(dev, mipsrc, mipmem, texoff) != VK_SUCCESS) { printf("MIPCOL: src mem FAIL\n"); break; }

		/* 2) staging buffer: each level a 1-texel CHECKERBOARD (0x00 <-> 0xff). NON-64-aligned base
		 * offset (68, 4-aligned) mimics vkQuake's R_StagingAllocate(align=4) shared-ring sub-offset —
		 * tests whether v3dv's TFU buffer->image copy mis-tiles an unaligned/arbitrary source offset. */
		const uint32_t STAGEOFF = 0;   /* isolate the XOR bind-offset variable */
		uint32_t moff[9], mw[9], mh[9], total = STAGEOFF;
		for (uint32_t L = 0; L < MLEVELS; L++) { mw[L] = (MSZ >> L) ? (MSZ >> L) : 1; mh[L] = mw[L]; moff[L] = total; total += mw[L] * mh[L] * 4u; }
		VkBuffer stg = VK_NULL_HANDLE; VkDeviceMemory stgmem = VK_NULL_HANDLE;
		VkBufferCreateInfo bci = { .sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO, .size = total, .usage = VK_BUFFER_USAGE_TRANSFER_SRC_BIT, .sharingMode = VK_SHARING_MODE_EXCLUSIVE };
		if (v3dv_CreateBuffer(dev, &bci, NULL, &stg) != VK_SUCCESS) { printf("MIPCOL: CreateBuffer FAIL\n"); break; }
		VkMemoryRequirements bmr; memset(&bmr, 0, sizeof(bmr)); vk_common_GetBufferMemoryRequirements(dev, stg, &bmr);
		VkMemoryAllocateInfo bmai = { .sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO, .allocationSize = bmr.size ? bmr.size : total, .memoryTypeIndex = memType };
		if (v3dv_AllocateMemory(dev, &bmai, NULL, &stgmem) != VK_SUCCESS || vk_common_BindBufferMemory(dev, stg, stgmem, 0) != VK_SUCCESS) { printf("MIPCOL: stg mem FAIL\n"); break; }
		void *smap = NULL;
		if (v3dv_MapMemory(dev, stgmem, 0, VK_WHOLE_SIZE, 0, &smap) != VK_SUCCESS || !smap) { printf("MIPCOL: stg map FAIL\n"); break; }
		for (uint32_t L = 0; L < MLEVELS; L++) {
			unsigned char *d = (unsigned char *)smap + moff[L];
			for (uint32_t y = 0; y < mh[L]; y++)
				for (uint32_t x = 0; x < mw[L]; x++) {
					/* MID-GRAYSCALE checker (0x55/0xAA) — intermediate values like real conchars, unlike
					 * the 0x00/0xFF extremes that survive a return-size/packing (out32) corruption. */
					unsigned char v = ((x + y) & 1u) ? 0xAA : 0x55;
					unsigned char *p = d + (y * mw[L] + x) * 4u;
					p[0] = v; p[1] = v; p[2] = v; p[3] = 255;   /* grayscale: R==G==B */
				}
		}

		/* 3) sampler = NEAREST/NEAREST/mip-NEAREST, REPEAT, no aniso, LOD clamped to 0 (mip0, 1:1, no blur) */
		VkSampler samp = VK_NULL_HANDLE;
		VkSamplerCreateInfo sci2 = { .sType = VK_STRUCTURE_TYPE_SAMPLER_CREATE_INFO,
			.magFilter = VK_FILTER_NEAREST, .minFilter = VK_FILTER_NEAREST,
			.mipmapMode = VK_SAMPLER_MIPMAP_MODE_NEAREST,
			.addressModeU = VK_SAMPLER_ADDRESS_MODE_REPEAT, .addressModeV = VK_SAMPLER_ADDRESS_MODE_REPEAT, .addressModeW = VK_SAMPLER_ADDRESS_MODE_REPEAT,
			.mipLodBias = 0.0f, .minLod = 0.0f, .maxLod = 0.0f, .borderColor = VK_BORDER_COLOR_INT_OPAQUE_BLACK };
		if (v3dv_CreateSampler(dev, &sci2, NULL, &samp) != VK_SUCCESS) { printf("MIPCOL: CreateSampler FAIL\n"); break; }
		VkImageView mipview = VK_NULL_HANDLE;
		VkImageViewCreateInfo mvci = { .sType = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO, .image = mipsrc, .viewType = VK_IMAGE_VIEW_TYPE_2D,
			.format = VK_FORMAT_R8G8B8A8_UNORM, .subresourceRange = { VK_IMAGE_ASPECT_COLOR_BIT, 0, MLEVELS, 0, 1 } };
		if (v3dv_CreateImageView(dev, &mvci, NULL, &mipview) != VK_SUCCESS) { printf("MIPCOL: view FAIL\n"); break; }
		VkDescriptorSetLayoutBinding dslb = { .binding = 0, .descriptorType = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, .descriptorCount = 1, .stageFlags = VK_SHADER_STAGE_FRAGMENT_BIT };
		VkDescriptorSetLayout dsl = VK_NULL_HANDLE;
		VkDescriptorSetLayoutCreateInfo dslci = { .sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO, .bindingCount = 1, .pBindings = &dslb };
		if (v3dv_CreateDescriptorSetLayout(dev, &dslci, NULL, &dsl) != VK_SUCCESS) { printf("MIPCOL: DSL FAIL\n"); break; }
		VkDescriptorPoolSize dps = { .type = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, .descriptorCount = 1 };
		VkDescriptorPool dpool = VK_NULL_HANDLE;
		VkDescriptorPoolCreateInfo dpci = { .sType = VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO, .maxSets = 1, .poolSizeCount = 1, .pPoolSizes = &dps };
		if (v3dv_CreateDescriptorPool(dev, &dpci, NULL, &dpool) != VK_SUCCESS) { printf("MIPCOL: DPOOL FAIL\n"); break; }
		VkDescriptorSet dset = VK_NULL_HANDLE;
		VkDescriptorSetAllocateInfo dsai = { .sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO, .descriptorPool = dpool, .descriptorSetCount = 1, .pSetLayouts = &dsl };
		if (v3dv_AllocateDescriptorSets(dev, &dsai, &dset) != VK_SUCCESS) { printf("MIPCOL: DSET FAIL\n"); break; }
		VkDescriptorImageInfo dii = { .sampler = samp, .imageView = mipview, .imageLayout = VK_IMAGE_LAYOUT_GENERAL };
		VkWriteDescriptorSet wds = { .sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET, .dstSet = dset, .dstBinding = 0, .descriptorCount = 1,
			.descriptorType = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, .pImageInfo = &dii };
		v3dv_UpdateDescriptorSets(dev, 1, &wds, 0, NULL);

		/* 4) offscreen RT (128x16 WIDE LINEAR color attachment -> anisotropic footprint; mappable) + RP + FB */
		VkImage rt = VK_NULL_HANDLE; VkDeviceMemory rtmem = VK_NULL_HANDLE;
		VkImageCreateInfo rci = { .sType = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO, .imageType = VK_IMAGE_TYPE_2D, .format = VK_FORMAT_R8G8B8A8_UNORM,
			.extent = { DSTW, DSTH, 1 }, .mipLevels = 1, .arrayLayers = 1, .samples = VK_SAMPLE_COUNT_1_BIT,
			.tiling = VK_IMAGE_TILING_LINEAR, .usage = VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT, .initialLayout = VK_IMAGE_LAYOUT_UNDEFINED };
		if (v3dv_CreateImage(dev, &rci, NULL, &rt) != VK_SUCCESS) { printf("MIPCOL: RT img FAIL\n"); break; }
		VkMemoryRequirements rmr; memset(&rmr, 0, sizeof(rmr)); vk_common_GetImageMemoryRequirements(dev, rt, &rmr);
		VkMemoryAllocateInfo rmai = { .sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO, .allocationSize = rmr.size, .memoryTypeIndex = memType };
		if (v3dv_AllocateMemory(dev, &rmai, NULL, &rtmem) != VK_SUCCESS || vk_common_BindImageMemory(dev, rt, rtmem, 0) != VK_SUCCESS) { printf("MIPCOL: RT mem FAIL\n"); break; }
		VkImageView rtview = VK_NULL_HANDLE;
		VkImageViewCreateInfo rvci = { .sType = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO, .image = rt, .viewType = VK_IMAGE_VIEW_TYPE_2D,
			.format = VK_FORMAT_R8G8B8A8_UNORM, .subresourceRange = { VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, 1 } };
		if (v3dv_CreateImageView(dev, &rvci, NULL, &rtview) != VK_SUCCESS) { printf("MIPCOL: RT view FAIL\n"); break; }
		VkAttachmentDescription2 att2 = { .sType = VK_STRUCTURE_TYPE_ATTACHMENT_DESCRIPTION_2, .format = VK_FORMAT_R8G8B8A8_UNORM,
			.samples = VK_SAMPLE_COUNT_1_BIT, .loadOp = VK_ATTACHMENT_LOAD_OP_CLEAR, .storeOp = VK_ATTACHMENT_STORE_OP_STORE,
			.stencilLoadOp = VK_ATTACHMENT_LOAD_OP_DONT_CARE, .stencilStoreOp = VK_ATTACHMENT_STORE_OP_DONT_CARE,
			.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED, .finalLayout = VK_IMAGE_LAYOUT_GENERAL };
		VkAttachmentReference2 aref2 = { .sType = VK_STRUCTURE_TYPE_ATTACHMENT_REFERENCE_2, .attachment = 0, .layout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL };
		VkSubpassDescription2 sub2 = { .sType = VK_STRUCTURE_TYPE_SUBPASS_DESCRIPTION_2, .pipelineBindPoint = VK_PIPELINE_BIND_POINT_GRAPHICS, .colorAttachmentCount = 1, .pColorAttachments = &aref2 };
		VkRenderPassCreateInfo2 rpci2 = { .sType = VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO_2, .attachmentCount = 1, .pAttachments = &att2, .subpassCount = 1, .pSubpasses = &sub2 };
		VkRenderPass rpass2 = VK_NULL_HANDLE;
		if (v3dv_CreateRenderPass2(dev, &rpci2, NULL, &rpass2) != VK_SUCCESS) { printf("MIPCOL: RP FAIL\n"); break; }
		VkFramebufferCreateInfo fbci2 = { .sType = VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO, .renderPass = rpass2, .attachmentCount = 1, .pAttachments = &rtview, .width = DSTW, .height = DSTH, .layers = 1 };
		VkFramebuffer fbobj2 = VK_NULL_HANDLE;
		if (v3dv_CreateFramebuffer(dev, &fbci2, NULL, &fbobj2) != VK_SUCCESS) { printf("MIPCOL: FB FAIL\n"); break; }

		/* 5) textured pipeline (tex.vert/tex.frag, layout = dsl, viewport DSTD) */
		/* MULTI-VARYING variant: VS computes 3 varyings (texcoord+color+fog) like vkQuake basic */
		/* EXACT vkQuake basic.vert + basic.frag (multi-attr VB + cross-stage push-const + FS reads fog uniform) */
		VkShaderModuleCreateInfo tvsci = { .sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO, .codeSize = sizeof(texprobe_basicvert_spirv), .pCode = texprobe_basicvert_spirv };
		VkShaderModuleCreateInfo tfsci = { .sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO, .codeSize = sizeof(texprobe_basicfrag_spirv), .pCode = texprobe_basicfrag_spirv };
		VkShaderModule tvs = VK_NULL_HANDLE, tfs = VK_NULL_HANDLE;
		if (vk_common_CreateShaderModule(dev, &tvsci, NULL, &tvs) != VK_SUCCESS || vk_common_CreateShaderModule(dev, &tfsci, NULL, &tfs) != VK_SUCCESS) { printf("MIPCOL: shader FAIL\n"); break; }
		/* basic push-const block: mat4 mvp @0 + vec3 fog_color @64 + float fog_density @76 = 80B, both stages */
		VkPushConstantRange tpcr = { .stageFlags = VK_SHADER_STAGE_VERTEX_BIT | VK_SHADER_STAGE_FRAGMENT_BIT, .offset = 0, .size = 80 };
		VkPipelineLayoutCreateInfo plci2 = { .sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO, .setLayoutCount = 1, .pSetLayouts = &dsl,
			.pushConstantRangeCount = 1, .pPushConstantRanges = &tpcr };
		VkPipelineLayout playout2 = VK_NULL_HANDLE;
		if (v3dv_CreatePipelineLayout(dev, &plci2, NULL, &playout2) != VK_SUCCESS) { printf("MIPCOL: PL FAIL\n"); break; }
		VkPipelineShaderStageCreateInfo tstages[2] = {
			{ .sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO, .stage = VK_SHADER_STAGE_VERTEX_BIT, .module = tvs, .pName = "main" },
			{ .sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO, .stage = VK_SHADER_STAGE_FRAGMENT_BIT, .module = tfs, .pName = "main" } };
		/* MULTI-ATTRIBUTE VB: pos.xy@0, uv.xy@8, color.rgba@16 — stride 32 (like vkQuake basic) */
		VkVertexInputBindingDescription vbind = { .binding = 0, .stride = 32, .inputRate = VK_VERTEX_INPUT_RATE_VERTEX };
		VkVertexInputAttributeDescription vattr[3] = {
			{ .location = 0, .binding = 0, .format = VK_FORMAT_R32G32_SFLOAT, .offset = 0 },
			{ .location = 1, .binding = 0, .format = VK_FORMAT_R32G32_SFLOAT, .offset = 8 },
			{ .location = 2, .binding = 0, .format = VK_FORMAT_R32G32B32A32_SFLOAT, .offset = 16 } };
		VkPipelineVertexInputStateCreateInfo tvis = { .sType = VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO,
			.vertexBindingDescriptionCount = 1, .pVertexBindingDescriptions = &vbind,
			.vertexAttributeDescriptionCount = 3, .pVertexAttributeDescriptions = vattr };
		VkPipelineInputAssemblyStateCreateInfo tias = { .sType = VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO, .topology = VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST };
		VkViewport tvp = { 0.0f, 0.0f, (float)DSTW, (float)DSTH, 0.0f, 1.0f };
		VkRect2D tsc = { { 0, 0 }, { DSTW, DSTH } };
		VkPipelineViewportStateCreateInfo tvps = { .sType = VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO, .viewportCount = 1, .pViewports = &tvp, .scissorCount = 1, .pScissors = &tsc };
		VkPipelineRasterizationStateCreateInfo trs = { .sType = VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO, .polygonMode = VK_POLYGON_MODE_FILL, .cullMode = VK_CULL_MODE_NONE, .frontFace = VK_FRONT_FACE_COUNTER_CLOCKWISE, .lineWidth = 1.0f };
		VkPipelineMultisampleStateCreateInfo tms = { .sType = VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO, .rasterizationSamples = VK_SAMPLE_COUNT_1_BIT };
		VkPipelineColorBlendAttachmentState tcba = { .colorWriteMask = 0xf };
		VkPipelineColorBlendStateCreateInfo tcb = { .sType = VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO, .attachmentCount = 1, .pAttachments = &tcba };
		VkGraphicsPipelineCreateInfo tgpci = { .sType = VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO, .stageCount = 2, .pStages = tstages,
			.pVertexInputState = &tvis, .pInputAssemblyState = &tias, .pViewportState = &tvps, .pRasterizationState = &trs,
			.pMultisampleState = &tms, .pColorBlendState = &tcb, .layout = playout2, .renderPass = rpass2, .subpass = 0 };
		VkPipeline tpipe = VK_NULL_HANDLE;
		if (v3dv_CreateGraphicsPipelines(dev, VK_NULL_HANDLE, 1, &tgpci, NULL, &tpipe) != VK_SUCCESS) { printf("MIPCOL: pipeline FAIL\n"); break; }

		/* 5b) multi-attribute vertex buffer: 3 verts x {pos.xy, uv.xy, color.rgba} (stride 32).
		 * pos = fullscreen tri; uv 0..4 => visible 0..2 => 1:1 with 128^2; color = white. */
		static const float VBDATA[3][8] = {
			{ -1.0f, -1.0f,  0.0f, 0.0f,  1.0f, 1.0f, 1.0f, 1.0f },
			{  3.0f, -1.0f,  4.0f, 0.0f,  1.0f, 1.0f, 1.0f, 1.0f },
			{ -1.0f,  3.0f,  0.0f, 4.0f,  1.0f, 1.0f, 1.0f, 1.0f } };
		VkBuffer vbuf = VK_NULL_HANDLE; VkDeviceMemory vbmem = VK_NULL_HANDLE;
		VkBufferCreateInfo vbci = { .sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO, .size = sizeof(VBDATA),
			.usage = VK_BUFFER_USAGE_VERTEX_BUFFER_BIT, .sharingMode = VK_SHARING_MODE_EXCLUSIVE };
		if (v3dv_CreateBuffer(dev, &vbci, NULL, &vbuf) != VK_SUCCESS) { printf("MIPCOL: VB create FAIL\n"); break; }
		VkMemoryRequirements vbmr; memset(&vbmr, 0, sizeof(vbmr)); vk_common_GetBufferMemoryRequirements(dev, vbuf, &vbmr);
		VkMemoryAllocateInfo vbmai = { .sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO, .allocationSize = vbmr.size ? vbmr.size : sizeof(VBDATA), .memoryTypeIndex = memType };
		if (v3dv_AllocateMemory(dev, &vbmai, NULL, &vbmem) != VK_SUCCESS || vk_common_BindBufferMemory(dev, vbuf, vbmem, 0) != VK_SUCCESS) { printf("MIPCOL: VB mem FAIL\n"); break; }
		void *vbmap = NULL;
		if (v3dv_MapMemory(dev, vbmem, 0, VK_WHOLE_SIZE, 0, &vbmap) != VK_SUCCESS || !vbmap) { printf("MIPCOL: VB map FAIL\n"); break; }
		memcpy(vbmap, VBDATA, sizeof(VBDATA));

		/* 6) record: fill mips via vkCmdCopyBufferToImage (real vkQuake upload), then textured draw */
		VkCommandBufferAllocateInfo cbai2 = { .sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO, .commandPool = pool, .level = VK_COMMAND_BUFFER_LEVEL_PRIMARY, .commandBufferCount = 1 };
		VkCommandBuffer cmd2 = VK_NULL_HANDLE;
		if (pAllocCmd(dev, &cbai2, &cmd2) != VK_SUCCESS) { printf("MIPCOL: cmd alloc FAIL\n"); break; }
		VkCommandBufferBeginInfo bbi2 = { .sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO, .flags = 0 };
		if (pBegin(cmd2, &bbi2) != VK_SUCCESS) { printf("MIPCOL: cmd begin FAIL\n"); break; }
		VkImageMemoryBarrier2 tb = { .sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER_2,
			.srcStageMask = VK_PIPELINE_STAGE_2_ALL_COMMANDS_BIT, .dstStageMask = VK_PIPELINE_STAGE_2_ALL_COMMANDS_BIT,
			.dstAccessMask = VK_ACCESS_2_TRANSFER_WRITE_BIT, .oldLayout = VK_IMAGE_LAYOUT_UNDEFINED, .newLayout = VK_IMAGE_LAYOUT_GENERAL,
			.image = mipsrc, .subresourceRange = { VK_IMAGE_ASPECT_COLOR_BIT, 0, MLEVELS, 0, 1 } };
		VkDependencyInfo tdep = { .sType = VK_STRUCTURE_TYPE_DEPENDENCY_INFO, .imageMemoryBarrierCount = 1, .pImageMemoryBarriers = &tb };
		v3dv_CmdPipelineBarrier2(cmd2, &tdep);
		for (uint32_t L = 0; L < MLEVELS; L++) {
			VkBufferImageCopy bic = { .bufferOffset = moff[L], .bufferRowLength = 0, .bufferImageHeight = 0,
				.imageSubresource = { VK_IMAGE_ASPECT_COLOR_BIT, L, 0, 1 }, .imageOffset = { 0, 0, 0 }, .imageExtent = { mw[L], mh[L], 1 } };
			vk_common_CmdCopyBufferToImage(cmd2, stg, mipsrc, VK_IMAGE_LAYOUT_GENERAL, 1, &bic);
		}
		VkImageMemoryBarrier2 tb2 = { .sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER_2,
			.srcStageMask = VK_PIPELINE_STAGE_2_ALL_COMMANDS_BIT, .dstStageMask = VK_PIPELINE_STAGE_2_ALL_COMMANDS_BIT,
			.srcAccessMask = VK_ACCESS_2_TRANSFER_WRITE_BIT, .dstAccessMask = VK_ACCESS_2_SHADER_SAMPLED_READ_BIT,
			.oldLayout = VK_IMAGE_LAYOUT_GENERAL, .newLayout = VK_IMAGE_LAYOUT_GENERAL,
			.image = mipsrc, .subresourceRange = { VK_IMAGE_ASPECT_COLOR_BIT, 0, MLEVELS, 0, 1 } };
		VkDependencyInfo tdep2 = { .sType = VK_STRUCTURE_TYPE_DEPENDENCY_INFO, .imageMemoryBarrierCount = 1, .pImageMemoryBarriers = &tb2 };
		v3dv_CmdPipelineBarrier2(cmd2, &tdep2);
		VkClearValue cv2 = { .color = { .float32 = { 0.0f, 0.0f, 0.0f, 1.0f } } };
		VkRenderPassBeginInfo rpbi2 = { .sType = VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO, .renderPass = rpass2, .framebuffer = fbobj2,
			.renderArea = { { 0, 0 }, { DSTW, DSTH } }, .clearValueCount = 1, .pClearValues = &cv2 };
		VkSubpassBeginInfo sbi2 = { .sType = VK_STRUCTURE_TYPE_SUBPASS_BEGIN_INFO, .contents = VK_SUBPASS_CONTENTS_INLINE };
		VkSubpassEndInfo sei2 = { .sType = VK_STRUCTURE_TYPE_SUBPASS_END_INFO };
		extern void vk_common_CmdBindVertexBuffers(VkCommandBuffer, uint32_t, uint32_t, const VkBuffer *, const VkDeviceSize *);
		extern void v3dv_CmdPushConstants(VkCommandBuffer, VkPipelineLayout, VkShaderStageFlags, uint32_t, uint32_t, const void *);
		static const float BASICPC[20] = { 1,0,0,0, 0,1,0,0, 0,0,1,0, 0,0,0,1,  /* identity mvp */
			0,0,0,  0 };   /* fog_color=0, fog_density=0 => fog=exp(0)=1 (no-op) */
		VkDeviceSize vboff = 0;
		v3dv_CmdBeginRenderPass2(cmd2, &rpbi2, &sbi2);
		v3dv_CmdBindPipeline(cmd2, VK_PIPELINE_BIND_POINT_GRAPHICS, tpipe);
		/* MULTI-DRAW: 8 draws with per-draw descriptor/VB/push-const rebinds in ONE command buffer,
		 * like vkQuake's many 2D draws. Tests whether v3dv leaks TMU/uniform/VPM state between draws
		 * (single-draw probes were all clean). All 8 write the same RT; if the accumulated result
		 * stripes => multi-draw state leak reproduced. */
		for (int di = 0; di < 8; di++) {
			v3dv_CmdBindDescriptorSets(cmd2, VK_PIPELINE_BIND_POINT_GRAPHICS, playout2, 0, 1, &dset, 0, NULL);
			vk_common_CmdBindVertexBuffers(cmd2, 0, 1, &vbuf, &vboff);
			v3dv_CmdPushConstants(cmd2, playout2, VK_SHADER_STAGE_VERTEX_BIT | VK_SHADER_STAGE_FRAGMENT_BIT, 0, 80, BASICPC);
			v3dv_CmdDraw(cmd2, 3, 1, 0, 0);
		}
		v3dv_CmdEndRenderPass2(cmd2, &sei2);
		if (pEnd(cmd2) != VK_SUCCESS) { printf("MIPCOL: cmd end FAIL\n"); break; }
		VkSubmitInfo si2 = { .sType = VK_STRUCTURE_TYPE_SUBMIT_INFO, .commandBufferCount = 1, .pCommandBuffers = &cmd2 };
		VkResult sr2 = pSubmit(queue, 1, &si2, VK_NULL_HANDLE);
		VkResult wr2 = pWaitIdle(queue);
		printf("v3dv-harness: CHECKPROBE submit=%d waitidle=%d (256^2 UIF_XOR checker, 512x512 dst, bound at 4096 offset (NOT 16KB-aligned))\n", (int)sr2, (int)wr2);
		if (sr2 != VK_SUCCESS || wr2 != VK_SUCCESS) break;

		/* 7) read back the 256x256 RT + STRUCTURAL checkerboard-defect detection. A correct 1-texel
		 * checker ALTERNATES with all 4 neighbors; a coordinate/addressing permutation samples a
		 * wrong-parity texel -> an interior px EQUALS a neighbor it should differ from = a DEFECT.
		 * Robust to a harmless global shift/inversion (those keep alternation). Also count black/white
		 * (a mid-gray count => unexpected LINEAR blur, would invalidate the exact-alternation premise). */
		VkImageSubresource rsub = { VK_IMAGE_ASPECT_COLOR_BIT, 0, 0 };
		VkSubresourceLayout rlay = { 0 };
		vk_common_GetImageSubresourceLayout(dev, rt, &rsub, &rlay);
		void *rmap = NULL;
		if (v3dv_MapMemory(dev, rtmem, 0, VK_WHOLE_SIZE, 0, &rmap) != VK_SUCCESS || !rmap) { printf("MIPCOL: RT map FAIL\n"); break; }
		const unsigned char *rbase = (const unsigned char *)rmap + (size_t)rlay.offset;
		uint32_t interior = 0, defects = 0, npx = 0, colourdef = 0, v55 = 0, vAA = 0, vother = 0;
		char ex[200]; int el = 0;
		for (uint32_t y = 0; y < DSTH; y++)
			for (uint32_t x = 0; x < DSTW; x++) {
				const unsigned char *p = rbase + (size_t)y * rlay.rowPitch + (size_t)x * 4u;
				npx++;
				int dRG = (int)p[0] - p[1], dGB = (int)p[1] - p[2];
				if (dRG < -16 || dRG > 16 || dGB < -16 || dGB > 16) colourdef++;   /* grayscale in => R==G==B out */
				if (p[0] >= 0x45 && p[0] <= 0x65) v55++; else if (p[0] >= 0x9A && p[0] <= 0xBA) vAA++; else vother++;
			}
		/* aligned-2x2-quad uniformity: clean 1:1 checker => 0% uniform; a 2x2-quad coord-collapse => ~100% */
		uint32_t quads = 0, quniform = 0;
		for (uint32_t qy = 0; qy + 1 < DSTH; qy += 2)
			for (uint32_t qx = 0; qx + 1 < DSTW; qx += 2) {
				const unsigned char *q = rbase + (size_t)qy * rlay.rowPitch + (size_t)qx * 4u;
				unsigned char a = q[0], b = q[4], c2 = q[rlay.rowPitch], d2 = q[rlay.rowPitch + 4];
				quads++;
				if (a == b && a == c2 && a == d2) quniform++;
			}
		for (uint32_t y = 1; y + 1 < DSTH; y++)
			for (uint32_t x = 1; x + 1 < DSTW; x++) {
				const unsigned char *c = rbase + (size_t)y * rlay.rowPitch + (size_t)x * 4u;
				unsigned char cv = c[0];
				unsigned char lv = c[-4], rv = c[4], uv = c[-rlay.rowPitch], dv = c[rlay.rowPitch];
				interior++;
				/* correct: cv differs from ALL 4 neighbors (checker). defect = matches any (same parity). */
				if (cv == lv || cv == rv || cv == uv || cv == dv) {
					defects++;
					if (el < 150) el += snprintf(ex + el, sizeof(ex) - el, " (%u,%u:%02x|L%02x R%02x U%02x D%02x)", x, y, cv, lv, rv, uv, dv);
				}
			}
		uint32_t ppm = interior ? defects * 1000u / interior : 0;
		uint32_t qpm = quads ? quniform * 1000u / quads : 0;
		uint32_t cpm = npx ? colourdef * 1000u / npx : 0;
		printf("v3dv-harness: CHECKPROBE RESULT %s  defects=%u/%u (%u.%u%%) quadUniform=%u/%u colourDef=%u/%u (%u.%u%%) v55=%u vAA=%u vother=%u px0=%02x%02x%02x pitch=%u%s\n",
		       (colourdef > npx / 50u) ? "COLOUR(grayscale-in => coloured-out: return-size/out32 read corruption REPRODUCED)" :
		       (defects == 0) ? "CLEAN(hi-freq 1:1 mid-gray read correct -> read path exonerated even for mid values)" :
		       (qpm > 800) ? "QUAD-COLLAPSE(2x2 quad shares ONE coord)" :
		       (ppm < 20) ? "NEAR-CLEAN(a few defects, inspect)" :
		       "DEFECTS(READ-SIDE REPRODUCED on hi-freq mid-gray data -> standalone repro; bisect)",
		       defects, interior, ppm / 10u, ppm % 10u, quniform, quads, colourdef, npx, cpm / 10u, cpm % 10u, v55, vAA, vother,
		       rbase[0], rbase[1], rbase[2], (uint32_t)rlay.rowPitch, defects ? ex : "");

		/* DYNPROBE (2026-07-30): the DYNAMIC-race axis every prior single-frame probe missed.
		 * vkQuake's speckle was proven to CHANGE frame-to-frame at a static camera reading static
		 * texture data (same-pose HDMI frame-diff) => a per-frame GPU read RACE, not a static
		 * addressing/decode error. Test it here in ISOLATION: re-submit this identical textured-draw
		 * command buffer N times and byte-compare the offscreen RT to iteration 0. Scene/BOs/CL are
		 * byte-identical, so a correct pipeline MUST produce identical output every frame. Differing
		 * bytes across identical submits == the race reproduced with NO Quake and NO HDMI (byte-exact),
		 * turning the whole investigation into a fast, Phoenix-glue-debuggable minimal repro. */
		{
			size_t rbytes = (size_t)DSTH * (size_t)rlay.rowPitch;
			unsigned char *snap = malloc(rbytes);
			if (snap) {
				memcpy(snap, rbase, rbytes);
				for (int it = 1; it <= 4; it++) {
					VkSubmitInfo sN = { .sType = VK_STRUCTURE_TYPE_SUBMIT_INFO,
						.commandBufferCount = 1, .pCommandBuffers = &cmd2 };
					pSubmit(queue, 1, &sN, VK_NULL_HANDLE);
					pWaitIdle(queue);
					__asm__ volatile("dsb sy" ::: "memory");
					uint32_t diff = 0, maxd = 0; size_t firstoff = 0;
					for (size_t i = 0; i < rbytes; i++) {
						int d = (int)rbase[i] - (int)snap[i]; if (d < 0) d = -d;
						if (d) { if (!diff) firstoff = i; diff++; if ((uint32_t)d > maxd) maxd = d; }
					}
					printf("v3dv-harness: DYNPROBE iter %d vs 0: %u/%zu bytes differ (maxd=%u firstoff=%zu) => %s\n",
					       it, diff, rbytes, maxd, firstoff,
					       diff ? "NONDETERMINISTIC (per-frame RACE reproduced in isolation)"
					            : "deterministic (identical)");
				}
				free(snap);
			} else printf("v3dv-harness: DYNPROBE malloc(%zu) FAILED\n", rbytes);
		}
	} while (0);

	/* --- #67 binner-determinism experiment ---------------------------------------------------
	 * If V3D_DET_ITERS=N is set, re-submit the SAME recorded command buffer N times. The scene,
	 * BOs and CL are byte-identical every iteration, so a DETERMINISTIC binner must produce a
	 * byte-identical tile_alloc every time -> identical CRC. Varying CRC = the binner itself is
	 * non-deterministic (the #67 root-cause split). Requires V3D_BIN_CRC=1 for the winsys to
	 * capture the CRC (else seq stays 0). Also samples the live scanout to catch a varying RENDER
	 * output even when the tile list is stable (that would indict CT1's read path, not the binner). */
	extern void vk_common_FreeCommandBuffers(VkDevice, VkCommandPool, uint32_t, const VkCommandBuffer *);

	/* #67 Stage-4: build a vertex buffer of MESH_TRIS DISTINCT small triangles laid out in a
	 * G x G grid (each triangle lands in a DIFFERENT screen tile) + a pipeline whose VS reads
	 * the vec2 position attribute (mesh_vert_spirv). This is the one axis Stages 1-3 never
	 * exercised: spatially-distributed VARIED geometry, exactly what Quake models are. */
	extern VkResult v3dv_CreateBuffer(VkDevice, const VkBufferCreateInfo *, const VkAllocationCallbacks *, VkBuffer *);
	extern void vk_common_GetBufferMemoryRequirements(VkDevice, VkBuffer, VkMemoryRequirements *);
	extern VkResult vk_common_BindBufferMemory(VkDevice, VkBuffer, VkDeviceMemory, VkDeviceSize);
	extern void vk_common_CmdBindVertexBuffers(VkCommandBuffer, uint32_t, uint32_t, const VkBuffer *, const VkDeviceSize *);
#define MESH_TRIS 1024u
#define MESH_GRID 32u
	VkPipeline mesh_pipeline = VK_NULL_HANDLE;
	VkBuffer vbuf = VK_NULL_HANDLE;
	int mesh_ready = 0;
	if (tri_ready && scimg != VK_NULL_HANDLE) do {
		VkBufferCreateInfo bci = {
			.sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO,
			.size = (VkDeviceSize)(MESH_TRIS * 3u * 2u * sizeof(float)),
			.usage = VK_BUFFER_USAGE_VERTEX_BUFFER_BIT, .sharingMode = VK_SHARING_MODE_EXCLUSIVE,
		};
		if (v3dv_CreateBuffer(dev, &bci, NULL, &vbuf) != VK_SUCCESS) { printf("v3dv-harness: mesh CreateBuffer FAIL\n"); break; }
		VkMemoryRequirements bmreq; memset(&bmreq, 0, sizeof(bmreq));
		vk_common_GetBufferMemoryRequirements(dev, vbuf, &bmreq);
		VkMemoryAllocateInfo bmai = {
			.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO,
			.allocationSize = bmreq.size ? bmreq.size : bci.size, .memoryTypeIndex = memType,
		};
		VkDeviceMemory bmem = VK_NULL_HANDLE;
		if (v3dv_AllocateMemory(dev, &bmai, NULL, &bmem) != VK_SUCCESS) { printf("v3dv-harness: mesh AllocMem FAIL\n"); break; }
		if (vk_common_BindBufferMemory(dev, vbuf, bmem, 0) != VK_SUCCESS) { printf("v3dv-harness: mesh BindBufMem FAIL\n"); break; }
		void *vp = NULL;
		if (v3dv_MapMemory(dev, bmem, 0, VK_WHOLE_SIZE, 0, &vp) != VK_SUCCESS || vp == NULL) { printf("v3dv-harness: mesh MapMem FAIL\n"); break; }
		float *vd = (float *)vp;
		for (unsigned t = 0; t < MESH_TRIS; t++) {
			/* Bit-reverse t over 10 bits (MESH_TRIS=1024=2^10) to pick the grid cell, so ANY
			 * prefix of the buffer (a low triangle-count draw) is spatially SCATTERED across the
			 * whole screen — the center band the coverage guard reads is populated at every N,
			 * not just when the sequential fill finally reaches the middle rows. */
			unsigned cell = 0, tt = t;
			for (int b = 0; b < 10; b++) { cell = (cell << 1) | (tt & 1u); tt >>= 1; }
			unsigned gx = cell % MESH_GRID, gy = cell / MESH_GRID;
			float cx = -1.0f + ((float)gx + 0.5f) * (2.0f / (float)MESH_GRID);
			float cy = -1.0f + ((float)gy + 0.5f) * (2.0f / (float)MESH_GRID);
			float h = (2.0f / (float)MESH_GRID) * 0.4f;
			vd[t*6+0] = cx;     vd[t*6+1] = cy - h;
			vd[t*6+2] = cx + h; vd[t*6+3] = cy + h;
			vd[t*6+4] = cx - h; vd[t*6+5] = cy + h;
		}
		VkShaderModuleCreateInfo mvsci = { .sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO, .codeSize = sizeof(mesh_vert_spirv), .pCode = mesh_vert_spirv };
		VkShaderModuleCreateInfo mfsci = { .sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO, .codeSize = sizeof(triangle_frag_spirv), .pCode = triangle_frag_spirv };
		VkShaderModule mvsmod = VK_NULL_HANDLE, mfsmod = VK_NULL_HANDLE;
		if (vk_common_CreateShaderModule(dev, &mvsci, NULL, &mvsmod) != VK_SUCCESS ||
		    vk_common_CreateShaderModule(dev, &mfsci, NULL, &mfsmod) != VK_SUCCESS) { printf("v3dv-harness: mesh shader FAIL\n"); break; }
		VkPipelineLayoutCreateInfo mplci = { .sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO };
		VkPipelineLayout mplayout = VK_NULL_HANDLE;
		if (v3dv_CreatePipelineLayout(dev, &mplci, NULL, &mplayout) != VK_SUCCESS) { printf("v3dv-harness: mesh layout FAIL\n"); break; }
		VkPipelineShaderStageCreateInfo mstages[2] = {
			{ .sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO, .stage = VK_SHADER_STAGE_VERTEX_BIT, .module = mvsmod, .pName = "main" },
			{ .sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO, .stage = VK_SHADER_STAGE_FRAGMENT_BIT, .module = mfsmod, .pName = "main" },
		};
		VkVertexInputBindingDescription vib = { .binding = 0, .stride = 2u * sizeof(float), .inputRate = VK_VERTEX_INPUT_RATE_VERTEX };
		VkVertexInputAttributeDescription via = { .location = 0, .binding = 0, .format = VK_FORMAT_R32G32_SFLOAT, .offset = 0 };
		VkPipelineVertexInputStateCreateInfo mvin = {
			.sType = VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO,
			.vertexBindingDescriptionCount = 1, .pVertexBindingDescriptions = &vib,
			.vertexAttributeDescriptionCount = 1, .pVertexAttributeDescriptions = &via,
		};
		VkPipelineInputAssemblyStateCreateInfo mias = { .sType = VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO, .topology = VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST };
		VkViewport mvp = { 0.0f, 0.0f, (float)fbmode.width, (float)fbmode.height, 0.0f, 1.0f };
		VkRect2D msc = { { 0, 0 }, { fbmode.width, fbmode.height } };
		VkPipelineViewportStateCreateInfo mvps = { .sType = VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO, .viewportCount = 1, .pViewports = &mvp, .scissorCount = 1, .pScissors = &msc };
		VkPipelineRasterizationStateCreateInfo mrs = { .sType = VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO, .polygonMode = VK_POLYGON_MODE_FILL, .cullMode = VK_CULL_MODE_NONE, .frontFace = VK_FRONT_FACE_COUNTER_CLOCKWISE, .lineWidth = 1.0f };
		VkPipelineMultisampleStateCreateInfo mms = { .sType = VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO, .rasterizationSamples = VK_SAMPLE_COUNT_1_BIT };
		VkPipelineColorBlendAttachmentState mcba = { .colorWriteMask = 0xf };
		VkPipelineColorBlendStateCreateInfo mcb = { .sType = VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO, .attachmentCount = 1, .pAttachments = &mcba };
		VkGraphicsPipelineCreateInfo mgpci = {
			.sType = VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO, .stageCount = 2, .pStages = mstages,
			.pVertexInputState = &mvin, .pInputAssemblyState = &mias, .pViewportState = &mvps,
			.pRasterizationState = &mrs, .pMultisampleState = &mms, .pColorBlendState = &mcb,
			.layout = mplayout, .renderPass = rpass, .subpass = 0,
		};
		VkResult mpr = v3dv_CreateGraphicsPipelines(dev, VK_NULL_HANDLE, 1, &mgpci, NULL, &mesh_pipeline);
		printf("v3dv-harness: mesh vkCreateGraphicsPipelines -> %d (%u distinct tris, %ux%u grid)\n",
		       (int)mpr, MESH_TRIS, MESH_GRID, MESH_GRID);
		if (mpr != VK_SUCCESS) { mesh_pipeline = VK_NULL_HANDLE; break; }
		mesh_ready = 1;
	} while (0);

	const char *deten = getenv("V3D_DET_ITERS");
	if (tri_ready) {
		unsigned iters = deten ? (unsigned)strtoul(deten, NULL, 10) : 64;
		if (iters == 0) iters = 64;

		/* Map the whole live scanout fb read-only; CRC a CENTER band each iteration as the
		 * render signature. Unlike Stage-1's row-0 samples (which only saw the CLEAR color),
		 * a center band crosses the drawn triangle. Prove that: compare the band CRC to the
		 * CRC of an all-CLEAR band (magenta R8G8B8A8 = ff 00 80 ff) — if they differ, the band
		 * genuinely covers rendered geometry, so a VARYING band CRC = a real render divergence. */
		volatile unsigned char *fb = NULL;
		uint32_t band_off = 0, band_len = 0, clear_crc = 0;
		if (fbmode.framebuffer != 0 && fbmode.smemlen > 0) {
			fb = mmap(NULL, (size_t)fbmode.smemlen, PROT_READ,
				MAP_PHYSMEM | MAP_UNCACHED | MAP_ANONYMOUS, -1, (off_t)fbmode.framebuffer);
			if (fb != MAP_FAILED) {
				uint32_t rows = 64;
				band_off = (uint32_t)(fbmode.height / 2 - rows / 2) * fbmode.pitch;
				band_len = rows * fbmode.pitch;
				if ((unsigned long long)band_off + band_len > fbmode.smemlen)
					band_len = (uint32_t)fbmode.smemlen - band_off;
				/* reference: a band-sized buffer full of the magenta clear pattern */
				unsigned char *ref = (unsigned char *)malloc(band_len);
				if (ref != NULL) {
					for (uint32_t i = 0; i < band_len; i += 4) {
						ref[i] = 0xff;
						if (i+1<band_len) ref[i+1]=0x00;
						if (i+2<band_len) ref[i+2]=0x80;
						if (i+3<band_len) ref[i+3]=0xff;
					}
					clear_crc = h_crc32(ref, band_len);
					free(ref);
				}
			} else {
				fb = NULL;
			}
		}
		printf("v3dv-harness: #67 CHURN loop iters=%u band_off=%u band_len=%u clear_crc=0x%08x\n",
		       iters, band_off, band_len, clear_crc);

		/* #67 Stage-3 DENSITY sweep: vkCmdDraw(3, N) draws N instances of the triangle, so the
		 * binner bins N primitives into every covered tile and runs 3N coordinate-shader
		 * invocations — stressing binner tile-list DENSITY + the QPU coordinate-shader load
		 * (the QRMAXCNT starvation axis) WITHOUT a vertex buffer. Each count is also churned
		 * (fresh cmd buffer + VA recycle per iter) so density and churn are exercised together.
		 * Watch whether band-CRC divergence appears/scales with N and whether qms grows. */
		/* Stage-4: sweep the number of DISTINCT triangles drawn from the mesh vertex buffer
		 * (spatially-distributed varied geometry across many tiles). Falls back to instance
		 * overdraw of the single vertexless triangle if the mesh pipeline didn't build. */
		unsigned mesh_counts[] = { 64u, 256u, 1024u, 1024u };
		unsigned inst_counts[] = { 1u, 16u, 64u, 256u };
		unsigned *counts = mesh_ready ? mesh_counts : inst_counts;
		unsigned ncounts = 4u;
		VkCommandBuffer prev = VK_NULL_HANDLE;
		VkDeviceSize voff = 0;
		(void)iters;
		for (unsigned cix = 0; cix < ncounts; cix++) {
			unsigned ninst = counts[cix];
			unsigned inner = 8u;
			uint32_t band0 = 0, band_distinct = 0, band_last = 0;
			uint32_t qma_first = 0, qma_moved = 0, coverage_ok = 0, qms_max = 0;
			for (unsigned it = 0; it < inner; it++) {
				VkCommandBuffer ci = VK_NULL_HANDLE;
				VkCommandBufferAllocateInfo cbai2 = {
					.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO,
					.commandPool = pool, .level = VK_COMMAND_BUFFER_LEVEL_PRIMARY, .commandBufferCount = 1,
				};
				if (pAllocCmd(dev, &cbai2, &ci) != VK_SUCCESS) { printf("v3dv-harness: CHURN[N=%u][%u] alloc FAIL\n", ninst, it); break; }
				VkCommandBufferBeginInfo bbi2 = { .sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO, .flags = 0 };
				if (pBegin(ci, &bbi2) != VK_SUCCESS) { printf("v3dv-harness: CHURN[N=%u][%u] begin FAIL\n", ninst, it); break; }
				VkClearValue cv2 = { .color = { .float32 = { 1.0f, 0.0f, 0.5f, 1.0f } } };
				VkRenderPassBeginInfo rpbi2 = {
					.sType = VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO, .renderPass = rpass, .framebuffer = fbobj,
					.renderArea = { { 0, 0 }, { fbmode.width, fbmode.height } }, .clearValueCount = 1, .pClearValues = &cv2,
				};
				VkSubpassBeginInfo sbi2 = { .sType = VK_STRUCTURE_TYPE_SUBPASS_BEGIN_INFO, .contents = VK_SUBPASS_CONTENTS_INLINE };
				VkSubpassEndInfo sei2 = { .sType = VK_STRUCTURE_TYPE_SUBPASS_END_INFO };
				v3dv_CmdBeginRenderPass2(ci, &rpbi2, &sbi2);
				if (mesh_ready) {
					/* varied geometry: ninst DISTINCT triangles from the vertex buffer, each in
					 * a different tile (3*ninst distinct vertices, no instancing). */
					v3dv_CmdBindPipeline(ci, VK_PIPELINE_BIND_POINT_GRAPHICS, mesh_pipeline);
					vk_common_CmdBindVertexBuffers(ci, 0, 1, &vbuf, &voff);
					v3dv_CmdDraw(ci, 3u * ninst, 1, 0, 0);
				} else {
					/* fallback: ninst instances of the single vertexless triangle (overdraw). */
					v3dv_CmdBindPipeline(ci, VK_PIPELINE_BIND_POINT_GRAPHICS, pipeline);
					v3dv_CmdDraw(ci, 3, ninst, 0, 0);
				}
				v3dv_CmdEndRenderPass2(ci, &sei2);
				if (pEnd(ci) != VK_SUCCESS) { printf("v3dv-harness: CHURN[N=%u][%u] end FAIL\n", ninst, it); break; }

				VkSubmitInfo dsi = { .sType = VK_STRUCTURE_TYPE_SUBMIT_INFO, .commandBufferCount = 1, .pCommandBuffers = &ci };
				VkResult dr = pSubmit(queue, 1, &dsi, VK_NULL_HANDLE);
				if (dr != VK_SUCCESS) { printf("v3dv-harness: CHURN[N=%u][%u] submit -> %d ABORT\n", ninst, it, (int)dr); break; }
				dr = pWaitIdle(queue);
				if (dr != VK_SUCCESS) { printf("v3dv-harness: CHURN[N=%u][%u] waitidle -> %d ABORT\n", ninst, it, (int)dr); break; }

				uint32_t qma = 0, qms = 0, tcrc = 0;
				(void)v3d_phoenix_last_bin_crc(&qma, &qms, &tcrc);
				uint32_t bcrc = (fb != NULL && band_len) ? h_crc32((const void *)(fb + band_off), band_len) : 0;
				if (it == 0) {
					band0 = band_last = bcrc; band_distinct = 1; qma_first = qma;
					coverage_ok = (bcrc != clear_crc);
				} else {
					if (qma != qma_first) qma_moved = 1;
					if (bcrc != band_last) { band_distinct++; band_last = bcrc; }
				}
				if (qms > qms_max) qms_max = qms;
				printf("v3dv-harness: CHURN[N=%u][%u] qma=0x%08x qms=%u tile_crc=0x%08x band_crc=0x%08x%s\n",
				       ninst, it, qma, qms, tcrc, bcrc, (bcrc != band0) ? "  <-- RENDER DIVERGED" : "");

				if (prev != VK_NULL_HANDLE) vk_common_FreeCommandBuffers(dev, pool, 1, &prev);
				prev = ci;
			}
			printf("v3dv-harness: #67 CHURN result N=%u: render %s | churn %s | coverage %s | qms_max=%u "
			       "(band-CRC transitions=%u over %u iters)\n",
			       ninst, (band_distinct <= 1) ? "STABLE" : "DIVERGED (glitch reproduced!)",
			       qma_moved ? "REAL" : "none", coverage_ok ? "OK" : "VACUOUS", qms_max,
			       band_distinct, inner);
		}
		if (prev != VK_NULL_HANDLE) vk_common_FreeCommandBuffers(dev, pool, 1, &prev);
		if (fb != NULL) munmap((void *)fb, (size_t)fbmode.smemlen);
	}

	if (g_ttyfd >= 0) {
		ioctl(g_ttyfd, FBCONSETMODE, FBCON_ENABLED);   /* restore the HDMI text console */
		close(g_ttyfd);
	}
	printf("v3dv-harness: PASS (clear+readback; render-pass+triangle draw if fb0; fb readback) -- Tier 3/4a/4b\n");
	return 0;
}
