/*
 * v3dv_harness.c — Vulkan Tier-0 link-closure + first-runtime-contact harness.
 *
 * The Vulkan analog of harness_screen_create.c (GL Path-C Phase 2). It drives the
 * V3DV ICD through the standard Vulkan entry sequence:
 *     vkCreateInstance -> vkEnumeratePhysicalDevices -> vkCreateDevice
 * resolving every entrypoint through vkGetInstanceProcAddr (aliased to
 * v3dv_GetInstanceProcAddr in vk_icd_link.c), exactly as a loader-less client (and
 * later vkQuake) would.
 *
 * Tier 0 GOAL = this links to an aarch64-phoenix ELF with 0 undefined symbols.
 * Tier 1 (main agent, on HW) = it actually runs and prints "vkCreateDevice OK, V3D 4.2".
 *
 * PRECONDITION (HW, Tier 1): the V3D must be powered on (v3d_phoenix_powerOn) before
 * the winsys touches MMIO — wired in the on-device launcher, not this link/smoke build.
 * Device enumeration's drmGetDevices2 scan is bypassed by the mesa-phoenix-port patch
 * (enumerate_devices -> create_physical_device with a FAKE_FD), see the Tier-0 doc.
 *
 * Copyright 2026 Phoenix Systems  %LICENSE%
 */
#include <stdio.h>
#include <string.h>
#include <fcntl.h>
#include <unistd.h>
#include <stdint.h>
#include <sys/ioctl.h>
#include <sys/mman.h>
#include <vulkan/vulkan.h>
#include "triangle_spirv.h"   /* GENERATED by gen-triangle-spirv.py: triangle_{vert,frag}_spirv[] */

/* The one symbol the loader-less client needs; vk_icd_link.c aliases it to
 * v3dv_GetInstanceProcAddr (the generated dispatch root). */
PFN_vkVoidFunction vkGetInstanceProcAddr(VkInstance instance, const char *pName);

#define GIPA(inst, name) ((PFN_##name)vkGetInstanceProcAddr((inst), #name))

int main(void)
{
	/* Unbuffered: a fault must not eat buffered output over the captured UART path. */
	setvbuf(stdout, NULL, _IONBF, 0);
	printf("v3dv-harness: start\n");

	PFN_vkCreateInstance pCreateInstance = GIPA(NULL, vkCreateInstance);
	if (!pCreateInstance) {
		printf("v3dv-harness: vkGetInstanceProcAddr(vkCreateInstance) NULL\n");
		return 1;
	}

	const char *exts[] = { "VK_KHR_surface" };
	VkApplicationInfo app = {
		.sType = VK_STRUCTURE_TYPE_APPLICATION_INFO,
		.pApplicationName = "v3dv-tier0",
		.apiVersion = VK_API_VERSION_1_1,
	};
	VkInstanceCreateInfo ici = {
		.sType = VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO,
		.pApplicationInfo = &app,
		/* keep extension count 0 for first-light; surface ext is advertised but the
		 * custom fb0 swapchain is Tier 4. Listed here for reference, not enabled. */
		.enabledExtensionCount = 0,
		.ppEnabledExtensionNames = exts,
	};
	VkInstance inst = VK_NULL_HANDLE;
	VkResult r = pCreateInstance(&ici, NULL, &inst);
	printf("v3dv-harness: vkCreateInstance -> %d\n", (int)r);
	if (r != VK_SUCCESS)
		return 2;

	PFN_vkEnumeratePhysicalDevices pEnum = GIPA(inst, vkEnumeratePhysicalDevices);
	PFN_vkGetPhysicalDeviceProperties pProps = GIPA(inst, vkGetPhysicalDeviceProperties);
	PFN_vkCreateDevice pCreateDevice = GIPA(inst, vkCreateDevice);
	if (!pEnum || !pCreateDevice) {
		printf("v3dv-harness: missing enum/createdevice proc\n");
		return 3;
	}

	uint32_t n = 0;
	r = pEnum(inst, &n, NULL);
	printf("v3dv-harness: vkEnumeratePhysicalDevices -> %d count=%u\n", (int)r, n);
	if (r != VK_SUCCESS || n == 0)
		return 4;

	VkPhysicalDevice phys = VK_NULL_HANDLE;
	n = 1;
	r = pEnum(inst, &n, &phys);
	if (r < 0)
		return 5;

	/* NOTE: vkGetPhysicalDeviceProperties (the vk_common trampoline) dispatches to the
	 * physical-device table's GetPhysicalDeviceProperties2 slot, which is currently NULL
	 * on this build -> instruction abort (pc=0). That is a physical-device-dispatch-table
	 * gap (cosmetic name print), independent of vkCreateDevice (an instance entrypoint
	 * dispatched straight to v3dv_CreateDevice). Skip the name print to reach the real
	 * Tier-1 milestone; the dispatch gap is tracked separately. */
	(void)pProps;
	printf("v3dv-harness: (skipping vkGetPhysicalDeviceProperties name print -- phys-dispatch Properties2 is NULL)\n");

	float prio = 1.0f;
	VkDeviceQueueCreateInfo qci = {
		.sType = VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO,
		.queueFamilyIndex = 0,
		.queueCount = 1,
		.pQueuePriorities = &prio,
	};
	VkDeviceCreateInfo dci = {
		.sType = VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO,
		.queueCreateInfoCount = 1,
		.pQueueCreateInfos = &qci,
	};
	VkDevice dev = VK_NULL_HANDLE;
	r = pCreateDevice(phys, &dci, NULL, &dev);
	printf("v3dv-harness: vkCreateDevice -> %d\n", (int)r);
	if (r != VK_SUCCESS)
		return 6;

	printf("v3dv-harness: device created OK\n");

	/* --- Tier 2: a real queue submit (empty primary command buffer). This exercises the
	 * V3DV queue -> winsys submit path (ioc_submit_cl, the same synchronous bin/render path
	 * Quake renders through) + the synchronous syncobj/fence stubs (work is done when
	 * ioc_submit_cl returns, so vkQueueWaitIdle returns immediately). Device-level procs
	 * resolve through vkGetDeviceProcAddr (NOT vkGetInstanceProcAddr: in a loader-less
	 * ICD link the latter hands back trampolines that deref a NULL device-dispatch slot
	 * -> pc=0 instruction-abort; GetDeviceProcAddr returns the real device entrypoint). --- */
	PFN_vkGetDeviceProcAddr pGDPA = GIPA(inst, vkGetDeviceProcAddr);
	if (!pGDPA) {
		printf("v3dv-harness: PASS (device created); no vkGetDeviceProcAddr\n");
		return 0;
	}
#define GDPA(d, name) ((PFN_##name)pGDPA((d), #name))
	/* CreateCommandPool / AllocateCommandBuffers / QueueSubmit are vk_common command-pool +
	 * synchronization FRAMEWORK entrypoints; they resolve NULL via vkGetDeviceProcAddr (a
	 * dispatch-table gate bug). The framework itself IS wired by v3dv (v3dv_queue_driver_submit
	 * + v3dv_cmd_buffer_ops), so we DECOUPLE the submit test from that lookup bug by calling the
	 * exported vk_common_* impls directly — exercising the real winsys submit path now. The
	 * dispatch-gate fix is tracked separately (docs/inprogress/2026-06-18-vulkan-v3dv-noop-job-rootcause.md). */
	extern VkResult vk_common_CreateCommandPool(VkDevice, const VkCommandPoolCreateInfo *,
		const VkAllocationCallbacks *, VkCommandPool *);
	extern VkResult vk_common_AllocateCommandBuffers(VkDevice, const VkCommandBufferAllocateInfo *,
		VkCommandBuffer *);
	extern VkResult vk_common_QueueSubmit(VkQueue, uint32_t, const VkSubmitInfo *, VkFence);
	PFN_vkGetDeviceQueue pGetQueue = GDPA(dev, vkGetDeviceQueue);
	PFN_vkCreateCommandPool pCreatePool = vk_common_CreateCommandPool;
	PFN_vkAllocateCommandBuffers pAllocCmd = vk_common_AllocateCommandBuffers;
	PFN_vkBeginCommandBuffer pBegin = GDPA(dev, vkBeginCommandBuffer);
	PFN_vkEndCommandBuffer pEnd = GDPA(dev, vkEndCommandBuffer);
	PFN_vkQueueSubmit pSubmit = vk_common_QueueSubmit;
	PFN_vkQueueWaitIdle pWaitIdle = GDPA(dev, vkQueueWaitIdle);
	printf("v3dv-harness: dproc GetDeviceQueue=%p CreateCommandPool=%p(direct) AllocCmdBufs=%p(direct) "
	       "Begin=%p End=%p QueueSubmit=%p(direct) QueueWaitIdle=%p\n",
	       (void *)pGetQueue, (void *)pCreatePool, (void *)pAllocCmd, (void *)pBegin,
	       (void *)pEnd, (void *)pSubmit, (void *)pWaitIdle);
	if (!pGetQueue || !pCreatePool || !pAllocCmd || !pBegin || !pEnd || !pSubmit || !pWaitIdle) {
		printf("v3dv-harness: PASS (device created); a Tier-2 device proc is NULL (see line above)\n");
		return 0;
	}

	VkQueue queue = VK_NULL_HANDLE;
	pGetQueue(dev, 0, 0, &queue);

	VkCommandPoolCreateInfo pci = {
		.sType = VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO,
		.queueFamilyIndex = 0,
	};
	VkCommandPool pool = VK_NULL_HANDLE;
	r = pCreatePool(dev, &pci, NULL, &pool);
	printf("v3dv-harness: vkCreateCommandPool -> %d\n", (int)r);
	if (r != VK_SUCCESS)
		return 7;

	VkCommandBufferAllocateInfo cbai = {
		.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO,
		.commandPool = pool,
		.level = VK_COMMAND_BUFFER_LEVEL_PRIMARY,
		.commandBufferCount = 1,
	};
	VkCommandBuffer cmd = VK_NULL_HANDLE;
	r = pAllocCmd(dev, &cbai, &cmd);
	printf("v3dv-harness: vkAllocateCommandBuffers -> %d\n", (int)r);
	if (r != VK_SUCCESS)
		return 8;

	/* --- Tier 3: record a REAL render command (vkCmdClearColorImage) so the submit executes
	 * actual GPU work (a clear) — not just the noop job. Image/memory/clear go via the exported
	 * v3dv_/vk_common_ impls directly (same decouple as Tier 2, bypassing the dispatch gate). --- */
	extern VkResult v3dv_CreateImage(VkDevice, const VkImageCreateInfo *, const VkAllocationCallbacks *, VkImage *);
	extern void vk_common_GetImageMemoryRequirements(VkDevice, VkImage, VkMemoryRequirements *);
	extern VkResult v3dv_AllocateMemory(VkDevice, const VkMemoryAllocateInfo *, const VkAllocationCallbacks *, VkDeviceMemory *);
	extern VkResult vk_common_BindImageMemory(VkDevice, VkImage, VkDeviceMemory, VkDeviceSize);
	extern void v3dv_CmdClearColorImage(VkCommandBuffer, VkImage, VkImageLayout, const VkClearColorValue *, uint32_t, const VkImageSubresourceRange *);

	VkImageCreateInfo imgci = {
		.sType = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO,
		.imageType = VK_IMAGE_TYPE_2D,
		.format = VK_FORMAT_R8G8B8A8_UNORM,
		.extent = { 64, 64, 1 },
		.mipLevels = 1,
		.arrayLayers = 1,
		.samples = VK_SAMPLE_COUNT_1_BIT,
		.tiling = VK_IMAGE_TILING_LINEAR,
		.usage = VK_IMAGE_USAGE_TRANSFER_DST_BIT,
		.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED,
	};
	VkImage image = VK_NULL_HANDLE;
	r = v3dv_CreateImage(dev, &imgci, NULL, &image);
	printf("v3dv-harness: vkCreateImage -> %d\n", (int)r);
	if (r != VK_SUCCESS)
		return 12;

	VkMemoryRequirements mreq;
	memset(&mreq, 0, sizeof(mreq));
	vk_common_GetImageMemoryRequirements(dev, image, &mreq);
	printf("v3dv-harness: image mem size=%u typeBits=0x%x\n",
	       (unsigned)mreq.size, (unsigned)mreq.memoryTypeBits);

	uint32_t memType = 0;
	for (uint32_t i = 0; i < 32; i++) {
		if (mreq.memoryTypeBits & (1u << i)) {
			memType = i;
			break;
		}
	}
	VkMemoryAllocateInfo mai = {
		.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO,
		.allocationSize = mreq.size ? mreq.size : (64u * 64u * 4u),
		.memoryTypeIndex = memType,
	};
	VkDeviceMemory mem = VK_NULL_HANDLE;
	r = v3dv_AllocateMemory(dev, &mai, NULL, &mem);
	printf("v3dv-harness: vkAllocateMemory -> %d\n", (int)r);
	if (r != VK_SUCCESS)
		return 13;
	r = vk_common_BindImageMemory(dev, image, mem, 0);
	printf("v3dv-harness: vkBindImageMemory -> %d\n", (int)r);
	if (r != VK_SUCCESS)
		return 14;

	/* --- Tier 4a: a VISIBLE-on-HDMI clear. Back a fullscreen image's memory with the HDMI scanout
	 * surface (winsys one-shot v3d_phoenix_set_next_scanout) so the GPU's clear paints the actual
	 * screen — verified via the HDMI auto-snapshot. Best-effort: if /dev/fb0 isn't available the
	 * offscreen Tier-3 clear above still stands. --- */
	extern void v3d_phoenix_set_scanout(uint32_t pa, uint32_t bytes);
	extern void v3d_phoenix_set_next_scanout(void);
	typedef struct {
		unsigned short width, height, bpp, pitch;
		unsigned long long smemlen, framebuffer;
	} rpi4fb_mode_h;
	VkImage scimg = VK_NULL_HANDLE;
	VkDeviceMemory scmem = VK_NULL_HANDLE;
	int fbfd = open("/dev/fb0", O_WRONLY);
	rpi4fb_mode_h fbmode;
	memset(&fbmode, 0, sizeof(fbmode));
	if (fbfd >= 0 && ioctl(fbfd, _IOR('g', 1, rpi4fb_mode_h), &fbmode) == 0 && fbmode.framebuffer != 0) {
		printf("v3dv-harness: fb0 %ux%u pitch=%u pa=0x%llx size=%llu\n",
		       fbmode.width, fbmode.height, fbmode.pitch,
		       (unsigned long long)fbmode.framebuffer, (unsigned long long)fbmode.smemlen);
		v3d_phoenix_set_scanout((uint32_t)fbmode.framebuffer, (uint32_t)fbmode.smemlen);
		VkImageCreateInfo sci = {
			.sType = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO,
			.imageType = VK_IMAGE_TYPE_2D,
			.format = VK_FORMAT_R8G8B8A8_UNORM,
			.extent = { fbmode.width, fbmode.height, 1 },
			.mipLevels = 1,
			.arrayLayers = 1,
			.samples = VK_SAMPLE_COUNT_1_BIT,
			.tiling = VK_IMAGE_TILING_LINEAR,
			.usage = VK_IMAGE_USAGE_TRANSFER_DST_BIT,
			.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED,
		};
		if (v3dv_CreateImage(dev, &sci, NULL, &scimg) == VK_SUCCESS) {
			VkMemoryRequirements scmreq;
			memset(&scmreq, 0, sizeof(scmreq));
			vk_common_GetImageMemoryRequirements(dev, scimg, &scmreq);
			VkMemoryAllocateInfo scmai = {
				.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO,
				.allocationSize = scmreq.size ? scmreq.size : (uint32_t)fbmode.smemlen,
				.memoryTypeIndex = memType,
			};
			v3d_phoenix_set_next_scanout();   /* the NEXT BO (this image's memory) backs the scanout */
			if (v3dv_AllocateMemory(dev, &scmai, NULL, &scmem) == VK_SUCCESS &&
			    vk_common_BindImageMemory(dev, scimg, scmem, 0) == VK_SUCCESS) {
				printf("v3dv-harness: scanout image %ux%u bound (mem=%u)\n",
				       fbmode.width, fbmode.height, (unsigned)scmreq.size);
			}
			else {
				scimg = VK_NULL_HANDLE;
				printf("v3dv-harness: scanout image alloc/bind FAILED\n");
			}
		}
		else {
			printf("v3dv-harness: scanout vkCreateImage FAILED\n");
		}
	}
	else {
		printf("v3dv-harness: fb0 GETMODE unavailable (offscreen clear only)\n");
	}
	if (fbfd >= 0)
		close(fbfd);

	/* --- Tier 4b: a real GRAPHICS PIPELINE + triangle. A render pass (loadOp=CLEAR,
	 * storeOp=STORE) into the scanout-backed image, a graphics pipeline built from
	 * hand-authored SPIR-V vertex+fragment shaders (triangle_spirv.h, validated offline
	 * with spirv2nir) compiled by v3dv's spirv_to_nir -> v3d_compile (NIR->QPU) path, and
	 * a vertexless vkCmdDraw(3). If the V3D executes the user shaders, the triangle's
	 * interpolated R/G/B colors land on the scanout (over the magenta clear). This is the
	 * first user-shader GPU render through Vulkan on Phoenix — the vkQuake prerequisite.
	 *
	 * Everything goes through the exported v3dv_/vk_common_ impls directly (same decouple
	 * as Tiers 2/3, bypassing the GetDeviceProcAddr dispatch gate). --- */
	extern VkResult v3dv_CreateImageView(VkDevice, const VkImageViewCreateInfo *, const VkAllocationCallbacks *, VkImageView *);
	extern VkResult v3dv_CreateRenderPass2(VkDevice, const VkRenderPassCreateInfo2 *, const VkAllocationCallbacks *, VkRenderPass *);
	extern VkResult v3dv_CreateFramebuffer(VkDevice, const VkFramebufferCreateInfo *, const VkAllocationCallbacks *, VkFramebuffer *);
	extern VkResult vk_common_CreateShaderModule(VkDevice, const VkShaderModuleCreateInfo *, const VkAllocationCallbacks *, VkShaderModule *);
	extern VkResult v3dv_CreatePipelineLayout(VkDevice, const VkPipelineLayoutCreateInfo *, const VkAllocationCallbacks *, VkPipelineLayout *);
	extern VkResult v3dv_CreateGraphicsPipelines(VkDevice, VkPipelineCache, uint32_t, const VkGraphicsPipelineCreateInfo *, const VkAllocationCallbacks *, VkPipeline *);
	extern void v3dv_CmdBeginRenderPass2(VkCommandBuffer, const VkRenderPassBeginInfo *, const VkSubpassBeginInfo *);
	extern void v3dv_CmdEndRenderPass2(VkCommandBuffer, const VkSubpassEndInfo *);
	extern void v3dv_CmdBindPipeline(VkCommandBuffer, VkPipelineBindPoint, VkPipeline);
	extern void v3dv_CmdDraw(VkCommandBuffer, uint32_t, uint32_t, uint32_t, uint32_t);

	VkImageView scview = VK_NULL_HANDLE;
	VkRenderPass rpass = VK_NULL_HANDLE;
	VkFramebuffer fbobj = VK_NULL_HANDLE;
	VkPipeline pipeline = VK_NULL_HANDLE;
	int tri_ready = 0;
	if (scimg != VK_NULL_HANDLE) {
		do {
			VkImageViewCreateInfo vci = {
				.sType = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO,
				.image = scimg,
				.viewType = VK_IMAGE_VIEW_TYPE_2D,
				.format = VK_FORMAT_R8G8B8A8_UNORM,
				.subresourceRange = { VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, 1 },
			};
			if (v3dv_CreateImageView(dev, &vci, NULL, &scview) != VK_SUCCESS) {
				printf("v3dv-harness: CreateImageView FAILED\n"); break;
			}

			/* Single color attachment: CLEAR on load, STORE on end. loadOp=CLEAR is the
			 * same TLB clear Tier-4a proved; storeOp=STORE writes the RCL tile store to the
			 * (LINEAR/RASTER) scanout BO, the path the clear already proved lands. */
			VkAttachmentDescription2 att = {
				.sType = VK_STRUCTURE_TYPE_ATTACHMENT_DESCRIPTION_2,
				.format = VK_FORMAT_R8G8B8A8_UNORM,
				.samples = VK_SAMPLE_COUNT_1_BIT,
				.loadOp = VK_ATTACHMENT_LOAD_OP_CLEAR,
				.storeOp = VK_ATTACHMENT_STORE_OP_STORE,
				.stencilLoadOp = VK_ATTACHMENT_LOAD_OP_DONT_CARE,
				.stencilStoreOp = VK_ATTACHMENT_STORE_OP_DONT_CARE,
				.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED,
				.finalLayout = VK_IMAGE_LAYOUT_GENERAL,
			};
			VkAttachmentReference2 attref = {
				.sType = VK_STRUCTURE_TYPE_ATTACHMENT_REFERENCE_2,
				.attachment = 0,
				.layout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL,
			};
			VkSubpassDescription2 sub = {
				.sType = VK_STRUCTURE_TYPE_SUBPASS_DESCRIPTION_2,
				.pipelineBindPoint = VK_PIPELINE_BIND_POINT_GRAPHICS,
				.colorAttachmentCount = 1,
				.pColorAttachments = &attref,
			};
			VkRenderPassCreateInfo2 rpci = {
				.sType = VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO_2,
				.attachmentCount = 1,
				.pAttachments = &att,
				.subpassCount = 1,
				.pSubpasses = &sub,
			};
			if (v3dv_CreateRenderPass2(dev, &rpci, NULL, &rpass) != VK_SUCCESS) {
				printf("v3dv-harness: CreateRenderPass2 FAILED\n"); break;
			}

			VkFramebufferCreateInfo fbci = {
				.sType = VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO,
				.renderPass = rpass,
				.attachmentCount = 1,
				.pAttachments = &scview,
				.width = fbmode.width,
				.height = fbmode.height,
				.layers = 1,
			};
			if (v3dv_CreateFramebuffer(dev, &fbci, NULL, &fbobj) != VK_SUCCESS) {
				printf("v3dv-harness: CreateFramebuffer FAILED\n"); break;
			}

			/* shader modules from the hand-authored SPIR-V (spirv_to_nir -> v3d_compile) */
			VkShaderModuleCreateInfo vsci = {
				.sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO,
				.codeSize = sizeof(triangle_vert_spirv),
				.pCode = triangle_vert_spirv,
			};
			VkShaderModuleCreateInfo fsci = {
				.sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO,
				.codeSize = sizeof(triangle_frag_spirv),
				.pCode = triangle_frag_spirv,
			};
			VkShaderModule vsmod = VK_NULL_HANDLE, fsmod = VK_NULL_HANDLE;
			if (vk_common_CreateShaderModule(dev, &vsci, NULL, &vsmod) != VK_SUCCESS ||
			    vk_common_CreateShaderModule(dev, &fsci, NULL, &fsmod) != VK_SUCCESS) {
				printf("v3dv-harness: CreateShaderModule FAILED\n"); break;
			}
			printf("v3dv-harness: shader modules created (vs=%uB fs=%uB)\n",
			       (unsigned)sizeof(triangle_vert_spirv), (unsigned)sizeof(triangle_frag_spirv));

			VkPipelineLayoutCreateInfo plci = { .sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO };
			VkPipelineLayout playout = VK_NULL_HANDLE;
			if (v3dv_CreatePipelineLayout(dev, &plci, NULL, &playout) != VK_SUCCESS) {
				printf("v3dv-harness: CreatePipelineLayout FAILED\n"); break;
			}

			VkPipelineShaderStageCreateInfo stages[2] = {
				{ .sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO,
				  .stage = VK_SHADER_STAGE_VERTEX_BIT, .module = vsmod, .pName = "main" },
				{ .sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO,
				  .stage = VK_SHADER_STAGE_FRAGMENT_BIT, .module = fsmod, .pName = "main" },
			};
			/* vertexless: no bindings/attributes (VS uses gl_VertexIndex) */
			VkPipelineVertexInputStateCreateInfo vis = {
				.sType = VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO,
			};
			VkPipelineInputAssemblyStateCreateInfo ias = {
				.sType = VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO,
				.topology = VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST,
			};
			VkViewport vp = { 0.0f, 0.0f, (float)fbmode.width, (float)fbmode.height, 0.0f, 1.0f };
			VkRect2D sc = { { 0, 0 }, { fbmode.width, fbmode.height } };
			VkPipelineViewportStateCreateInfo vps = {
				.sType = VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO,
				.viewportCount = 1, .pViewports = &vp,
				.scissorCount = 1, .pScissors = &sc,
			};
			VkPipelineRasterizationStateCreateInfo rs = {
				.sType = VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO,
				.polygonMode = VK_POLYGON_MODE_FILL,
				.cullMode = VK_CULL_MODE_NONE,
				.frontFace = VK_FRONT_FACE_COUNTER_CLOCKWISE,
				.lineWidth = 1.0f,
			};
			VkPipelineMultisampleStateCreateInfo ms = {
				.sType = VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO,
				.rasterizationSamples = VK_SAMPLE_COUNT_1_BIT,
			};
			VkPipelineColorBlendAttachmentState cba = { .colorWriteMask = 0xf };
			VkPipelineColorBlendStateCreateInfo cb = {
				.sType = VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO,
				.attachmentCount = 1, .pAttachments = &cba,
			};
			VkGraphicsPipelineCreateInfo gpci = {
				.sType = VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO,
				.stageCount = 2, .pStages = stages,
				.pVertexInputState = &vis,
				.pInputAssemblyState = &ias,
				.pViewportState = &vps,
				.pRasterizationState = &rs,
				.pMultisampleState = &ms,
				.pColorBlendState = &cb,
				.layout = playout,
				.renderPass = rpass,
				.subpass = 0,
			};
			VkResult pr = v3dv_CreateGraphicsPipelines(dev, VK_NULL_HANDLE, 1, &gpci, NULL, &pipeline);
			printf("v3dv-harness: vkCreateGraphicsPipelines -> %d\n", (int)pr);
			if (pr != VK_SUCCESS) { pipeline = VK_NULL_HANDLE; break; }
			tri_ready = 1;
		} while (0);
	}

	VkCommandBufferBeginInfo bbi = {
		.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO,
		.flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT,
	};
	r = pBegin(cmd, &bbi);
	if (r != VK_SUCCESS) {
		printf("v3dv-harness: vkBeginCommandBuffer -> %d\n", (int)r);
		return 9;
	}
	VkClearColorValue clearColor = { .float32 = { 0.0f, 0.5f, 1.0f, 1.0f } };
	VkImageSubresourceRange range = {
		.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT,
		.baseMipLevel = 0,
		.levelCount = 1,
		.baseArrayLayer = 0,
		.layerCount = 1,
	};
	v3dv_CmdClearColorImage(cmd, image, VK_IMAGE_LAYOUT_GENERAL, &clearColor, 1, &range);
	if (tri_ready) {
		/* The real Tier-4b path: a render pass whose loadOp=CLEAR paints the scanout
		 * attachment magenta, then the graphics pipeline draws the vertexless triangle.
		 * The VS+FS (hand-authored SPIR-V) are compiled spirv_to_nir -> v3d_compile
		 * (NIR->QPU) and EXECUTED on the V3D; storeOp=STORE writes the rendered tiles to
		 * the scanout BO -> an R/G/B-interpolated triangle over magenta on HDMI. This is
		 * the first user-shader GPU render through Vulkan on Phoenix. */
		VkClearValue cv = { .color = { .float32 = { 1.0f, 0.0f, 0.5f, 1.0f } } }; /* magenta */
		VkRenderPassBeginInfo rpbi = {
			.sType = VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO,
			.renderPass = rpass,
			.framebuffer = fbobj,
			.renderArea = { { 0, 0 }, { fbmode.width, fbmode.height } },
			.clearValueCount = 1,
			.pClearValues = &cv,
		};
		VkSubpassBeginInfo sbi = {
			.sType = VK_STRUCTURE_TYPE_SUBPASS_BEGIN_INFO,
			.contents = VK_SUBPASS_CONTENTS_INLINE,
		};
		VkSubpassEndInfo sei = { .sType = VK_STRUCTURE_TYPE_SUBPASS_END_INFO };
		v3dv_CmdBeginRenderPass2(cmd, &rpbi, &sbi);
		v3dv_CmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, pipeline);
		v3dv_CmdDraw(cmd, 3, 1, 0, 0); /* vertexless: VS builds 3 verts from gl_VertexIndex */
		v3dv_CmdEndRenderPass2(cmd, &sei);
		printf("v3dv-harness: recorded render pass + vertexless triangle draw (user VS+FS)\n");
	}
	else if (scimg != VK_NULL_HANDLE) {
		/* Fallback (pipeline build failed): plain scanout clear so HDMI still shows a
		 * deterministic Tier-4a result instead of a blank/garbage frame. */
		VkClearColorValue scColor = { .float32 = { 1.0f, 0.0f, 0.5f, 1.0f } }; /* magenta */
		v3dv_CmdClearColorImage(cmd, scimg, VK_IMAGE_LAYOUT_GENERAL, &scColor, 1, &range);
		printf("v3dv-harness: triangle pipeline not ready -> fallback magenta clear\n");
	}
	r = pEnd(cmd);
	printf("v3dv-harness: record clear cmd buffer -> %d\n", (int)r);
	if (r != VK_SUCCESS)
		return 9;

	VkSubmitInfo si = {
		.sType = VK_STRUCTURE_TYPE_SUBMIT_INFO,
		.commandBufferCount = 1,
		.pCommandBuffers = &cmd,
	};
	r = pSubmit(queue, 1, &si, VK_NULL_HANDLE);
	printf("v3dv-harness: vkQueueSubmit -> %d\n", (int)r);
	if (r != VK_SUCCESS)
		return 10;

	r = pWaitIdle(queue);
	printf("v3dv-harness: vkQueueWaitIdle -> %d\n", (int)r);
	if (r != VK_SUCCESS)
		return 11;

	/* Tier 3 verification: the image memory (type 0) is HOST_VISIBLE + the winsys BO is uncached,
	 * so map it and read pixel 0 — it must hold the clear color. R8G8B8A8_UNORM {0,0.5,1,1} stores
	 * bytes ~00 80 ff ff (or bgra ff 80 00 ff). A non-trivial pattern proves the GPU actually wrote
	 * the clear (not just executed without fault). */
	extern VkResult v3dv_MapMemory(VkDevice, VkDeviceMemory, VkDeviceSize, VkDeviceSize, VkMemoryMapFlags, void **);
	void *mapped = NULL;
	r = v3dv_MapMemory(dev, mem, 0, VK_WHOLE_SIZE, 0, &mapped);
	if (r == VK_SUCCESS && mapped != NULL) {
		const unsigned char *px = (const unsigned char *)mapped;
		printf("v3dv-harness: clear readback px0 = %02x %02x %02x %02x (expect ~00 80 ff ff / bgra ff 80 00 ff)\n",
		       px[0], px[1], px[2], px[3]);
	}
	else {
		printf("v3dv-harness: clear readback skipped (vkMapMemory -> %d)\n", (int)r);
	}

	/* Tier 4a verification (deterministic, independent of fbcon overdraw / snapshot timing): read the
	 * LIVE scanout framebuffer's physical memory. If the GPU's scanout clear landed, pixel 0 holds the
	 * magenta clear {1,0,0.5,1} = bytes ff 00 80 ff (R8G8B8A8). The HDMI auto-snapshot may also show it. */
	if (scimg != VK_NULL_HANDLE && fbmode.framebuffer != 0) {
		volatile unsigned char *fb = mmap(NULL, 4096, PROT_READ,
			MAP_PHYSMEM | MAP_UNCACHED | MAP_ANONYMOUS, -1, (off_t)fbmode.framebuffer);
		if (fb != MAP_FAILED) {
			/* px0 is the top-left CORNER, outside the centered triangle -> it holds the
			 * magenta clear (ff 00 80 ff) whether or not the triangle drew. The triangle
			 * itself (R/G/B interpolated, center screen) is verified via the HDMI snapshot;
			 * the vkCreateGraphicsPipelines/QueueSubmit/WaitIdle return codes above prove the
			 * shader compiled + the render pass executed without fault. */
			printf("v3dv-harness: scanout fb px0(corner) = %02x %02x %02x %02x (expect magenta ff 00 80 ff = clear; "
			       "triangle is center-screen -> check HDMI snapshot)\n",
			       fb[0], fb[1], fb[2], fb[3]);
			munmap((void *)fb, 4096);
		}
		else {
			printf("v3dv-harness: scanout fb readback mmap failed\n");
		}
	}

	printf("v3dv-harness: PASS (clear+readback; render-pass+triangle draw if fb0; fb readback) -- Tier 3/4a/4b\n");
	return 0;
}
