#!/usr/bin/env bash
#
# Phoenix-RTOS X11 — generate the compiled-in fallback keymap for Xphoenix.
#
# The kdrive server's XKB init forks `xkbcomp` to compile a keymap; the Pi has
# neither xkbcomp nor xkeyboard-config, so that fork fails and the server aborts
# ("XKB: Failed to compile keymap" -> "Failed to activate virtual core keyboard").
#
# This script precompiles a US/pc105 keymap to a .xkm on the host (where xkbcomp
# IS available) and emits it as a C byte array. The patched ddxLoad.c materializes
# those bytes to the path the server's LoadXKM() reads, so no on-device xkbcomp is
# needed. See builtin_keymap.h and the __phoenix__ block in ../ddx/ddxLoad.c.
#
# The .xkm format carries XkmFileVersion (currently 15) in its header; the in-tree
# xorg-server xkmread.c and libxkbfile both expect 15, and host xkbcomp 1.4.x emits
# 15 — verified below. If the host xkbcomp ever emits a different version this
# script FAILS LOUDLY rather than shipping a silently-unloadable keymap.
#
# Host-side only. Idempotent. Re-run after changing the layout below.
#
# Copyright 2026 Phoenix Systems
# Author: Witold Bołt
set -eu

# Repo root derived from this script's own location (portable across checkouts).
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")/../../.." && pwd)"

HERE=${ROOT}/tools/x11-port/xkb
RULES=evdev
MODEL=pc105
LAYOUT=us

XKM="$HERE/default.xkm"
HDR="$HERE/builtin_keymap.h"
KEYMAP="$HERE/$LAYOUT-$MODEL.keymap"

command -v setxkbmap >/dev/null || { echo "FAIL: setxkbmap not found on host"; exit 1; }
command -v xkbcomp   >/dev/null || { echo "FAIL: xkbcomp not found on host"; exit 1; }

echo "=== generating $LAYOUT/$MODEL RMLVO keymap text ==="
setxkbmap -rules "$RULES" -model "$MODEL" -layout "$LAYOUT" -print > "$KEYMAP"

echo "=== compiling to $XKM (xkbcomp) ==="
xkbcomp -w 0 -xkm "$KEYMAP" "$XKM" 2> "$HERE/xkbcomp.warn" || { echo "FAIL: xkbcomp"; cat "$HERE/xkbcomp.warn"; exit 1; }

# Verify the .xkm version byte == XkmFileVersion the server expects (15).
# .xkm header word is ('x'<<24)|('k'<<16)|('m'<<8)|ver, stored little-endian,
# so byte 0 of the file == ver. Read it portably with od.
VER=$(od -An -tu1 -N1 "$XKM" | tr -d ' ')
EXPECT=$(grep -hoE 'define[[:space:]]+XkmFileVersion[[:space:]]+[0-9]+' \
    ${ROOT}/tools/x11-port/src/libxkbfile-1.1.3/include/X11/extensions/XKM.h \
    | grep -oE '[0-9]+$' | head -1)
echo "xkm version byte = $VER ; server expects XkmFileVersion = $EXPECT"
if [ "$VER" != "$EXPECT" ]; then
    echo "FAIL: host xkbcomp emitted XKM version $VER but the server reads $EXPECT."
    echo "      Shipping this would give 'Error loading keymap' on HW, not a paint."
    exit 1
fi

# Round-trip sanity: the server needs symbols+types+compat+keycodes present.
echo "=== round-trip section check ==="
xkbcomp -xkb "$XKM" "$HERE/.roundtrip.xkb" 2>/dev/null
for sec in xkb_keycodes xkb_types xkb_compat xkb_symbols; do
    grep -q "$sec" "$HERE/.roundtrip.xkb" || { echo "FAIL: $sec missing from compiled keymap"; exit 1; }
done
rm -f "$HERE/.roundtrip.xkb"
echo "all required sections present."

echo "=== emitting C array -> $HDR ==="
{
    echo "/* Auto-generated by gen-builtin-keymap.sh — DO NOT EDIT BY HAND."
    echo " * Precompiled $LAYOUT/$MODEL XKB keymap (.xkm, XkmFileVersion $EXPECT),"
    echo " * embedded so Xphoenix needs no on-device xkbcomp/xkeyboard-config."
    echo " */"
    echo "#ifndef PHOENIX_BUILTIN_KEYMAP_H"
    echo "#define PHOENIX_BUILTIN_KEYMAP_H"
    echo "static const unsigned char phoenix_builtin_xkm[] = {"
    od -An -v -tu1 "$XKM" | awk '{for(i=1;i<=NF;i++)printf "%s,",$i; print ""}'
    echo "};"
    echo "static const unsigned int phoenix_builtin_xkm_len = sizeof(phoenix_builtin_xkm);"
    echo "#endif /* PHOENIX_BUILTIN_KEYMAP_H */"
} > "$HDR"

echo "=== OK ==="
ls -l "$XKM" "$HDR"
