#!/usr/bin/env bash
#
# Generate sources/phoenix-rtos-lwip/port/wifi-fw-43455.{c,h} from
# .firmware/brcmfmac43455-sdio.bin. The .c emits the Cypress firmware
# blob as `const uint8_t wifi_fw_43455[]` for the WiFi P3 firmware
# loader (diag-udp 'I' sub-command).
#
# The generated files are gitignored:
#   - the firmware itself is under Cypress EULA (not BSD), see
#     docs/wifi-firmware-blobs.md
#   - regenerating is fast and deterministic from the staged blob
#
# Idempotent: skips work if the .c is newer than the .bin.
#
# Copyright 2026 Phoenix Systems
# SPDX-License-Identifier: BSD-3-Clause

set -euo pipefail

repo="${PHOENIX_RPI_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}"
src="$repo/.firmware/brcmfmac43455-sdio.bin"
port_dir="$repo/sources/phoenix-rtos-lwip/port"
out_c="$port_dir/wifi-fw-43455.c"
out_h="$port_dir/wifi-fw-43455.h"

if [ ! -d "$port_dir" ]; then
    printf 'error: missing %s\n' "$port_dir" >&2
    exit 1
fi

if [ -f "$src" ]; then
    have_blob=1
    src_bytes=$(stat -c %s "$src")
    if [ -f "$out_c" ] && [ "$out_c" -nt "$src" ]; then
        exit 0
    fi
else
    have_blob=0
    src_bytes=0
    # If a stub is already present and there's no blob to upgrade from,
    # leave it alone; otherwise emit one.
    if [ -f "$out_c" ] && grep -q 'wifi_fw_43455_len = 0u' "$out_c" 2>/dev/null; then
        exit 0
    fi
fi

cat > "$out_h.tmp" <<EOF
/* Generated by scripts/gen-wifi-fw-c.sh — DO NOT EDIT.
 *
 * BCM43455 SDIO firmware blob (Cypress 7.45.241+) declared for the
 * WiFi P3 firmware loader. Source artifact lives in .firmware/, which
 * is gitignored; regenerate with scripts/gen-wifi-fw-c.sh after the
 * stage-bcm43455-firmware.sh helper has populated the staging dir. */
#ifndef WIFI_FW_43455_H
#define WIFI_FW_43455_H

#include <stddef.h>
#include <stdint.h>

extern const uint8_t wifi_fw_43455[];
extern const size_t wifi_fw_43455_len;

#endif /* WIFI_FW_43455_H */
EOF
mv "$out_h.tmp" "$out_h"

if [ "$have_blob" = "1" ]; then
    {
        printf '/* Generated by scripts/gen-wifi-fw-c.sh — DO NOT EDIT. */\n'
        printf '#include "wifi-fw-43455.h"\n'
        printf '\n'
        printf 'const uint8_t wifi_fw_43455[] = {\n'
        xxd -i < "$src"
        printf '};\n'
        printf '\n'
        printf 'const size_t wifi_fw_43455_len = %uu;\n' "$src_bytes"
    } > "$out_c.tmp"
    mv "$out_c.tmp" "$out_c"
    printf 'gen-wifi-fw-c: %u bytes -> %s\n' "$src_bytes" "$out_c" >&2
else
    {
        printf '/* Generated by scripts/gen-wifi-fw-c.sh — DO NOT EDIT.\n'
        printf ' *\n'
        printf ' * .firmware/brcmfmac43455-sdio.bin not staged; emitting empty stub\n'
        printf ' * so the lwip-port build keeps working. Run\n'
        printf ' * scripts/stage-bcm43455-firmware.sh to populate the blob, then\n'
        printf ' * scripts/gen-wifi-fw-c.sh to regenerate this file. */\n'
        printf '#include "wifi-fw-43455.h"\n'
        printf '\n'
        printf 'const uint8_t wifi_fw_43455[1] = { 0 };\n'
        printf 'const size_t wifi_fw_43455_len = 0u;\n'
    } > "$out_c.tmp"
    mv "$out_c.tmp" "$out_c"
    printf 'gen-wifi-fw-c: no blob staged -> emitted stub at %s\n' "$out_c" >&2
fi
