#!/usr/bin/env python3
"""Process brcmfmac43455-sdio.txt into the chip-ready NVRAM blob and emit a
C array suitable for embedding in the lwip-port WiFi firmware loader.

The chip-side format expected by brcmfmac firmware:
  1. Each non-comment non-blank line, with NUL replacing the newline
  2. Final extra NUL terminator
  3. Padded to a 4-byte boundary
  4. 4-byte LE trailer = ((~(len_in_words)) << 16) | (len_in_words & 0xffff)
     where len_in_words = padded_data_len / 4

Total chip-side NVRAM length = padded_data_len + 4 (trailer).

The result is written to chip-internal address:
  rambase + ramsize - total_len

Usage:
  gen-wifi-nvram-py.py SRC_TXT OUT_C

SPDX-License-Identifier: BSD-3-Clause
Copyright 2026 Phoenix Systems
"""

import sys
import struct


def strip_nvram(src_text):
    out = bytearray()
    for line in src_text.splitlines():
        line = line.strip()
        if not line or line.startswith('#'):
            continue
        out.extend(line.encode('ascii', errors='strict'))
        out.append(0)
    # firmware expects a trailing extra NUL
    out.append(0)
    # pad to 4-byte boundary (brcmfmac requirement)
    while len(out) % 4 != 0:
        out.append(0)
    # Pad further so that (stripped + 4-byte trailer) is a multiple of
    # 64. This lets the diag-udp loader use a single CMD53 multi-block
    # write with block_size=64. The padding zeros land between the
    # parseable data and the trailer; firmware accepts that.
    target = ((len(out) + 4 + 63) // 64) * 64 - 4
    while len(out) < target:
        out.append(0)
    return bytes(out)


def build_blob(stripped):
    words = len(stripped) // 4
    token = ((~words) & 0xFFFF) << 16 | (words & 0xFFFF)
    trailer = struct.pack('<I', token & 0xFFFFFFFF)
    return stripped + trailer, words, token


def emit_c(out_c, blob, words, token, src_path):
    with open(out_c, 'w') as f:
        f.write('/* Generated by scripts/gen-wifi-nvram-py.py — DO NOT EDIT.\n')
        f.write(' *\n')
        f.write(' * BCM43455 SDIO NVRAM blob (chip-ready: stripped, aligned,\n')
        f.write(' * with brcmfmac length+complement trailer).\n')
        f.write(' *\n')
        f.write(' * Source artifact: %s\n' % src_path)
        f.write(' * len_in_words=%u  trailer=0x%08x  blob_len=%u bytes\n' %
                (words, token & 0xFFFFFFFF, len(blob)))
        f.write(' */\n')
        f.write('#include "wifi-nvram-43455.h"\n\n')
        f.write('const uint8_t wifi_nvram_43455[] = {\n')
        for i in range(0, len(blob), 16):
            chunk = blob[i:i+16]
            line = ', '.join('0x%02x' % b for b in chunk)
            f.write('    ' + line + ',\n')
        f.write('};\n\n')
        f.write('const size_t wifi_nvram_43455_len = %uu;\n' % len(blob))


def main(argv):
    if len(argv) != 3:
        print(__doc__, file=sys.stderr)
        return 1
    src_path = argv[1]
    out_c = argv[2]
    try:
        with open(src_path, 'r', encoding='ascii') as f:
            src_text = f.read()
    except FileNotFoundError:
        # Emit empty stub so the lwip build keeps working
        with open(out_c, 'w') as f:
            f.write('/* Generated stub — no NVRAM staged. */\n')
            f.write('#include "wifi-nvram-43455.h"\n\n')
            f.write('const uint8_t wifi_nvram_43455[1] = { 0 };\n')
            f.write('const size_t wifi_nvram_43455_len = 0u;\n')
        print('gen-wifi-nvram-py: no source -> emitted stub at %s' % out_c,
              file=sys.stderr)
        return 0
    stripped = strip_nvram(src_text)
    blob, words, token = build_blob(stripped)
    emit_c(out_c, blob, words, token, src_path)
    print('gen-wifi-nvram-py: %u src bytes -> %u chip bytes (%u words, '
          'token=0x%08x) -> %s' %
          (len(src_text), len(blob), words, token & 0xFFFFFFFF, out_c),
          file=sys.stderr)
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv))
