#!/usr/bin/env bash
#
# Pi 4 netboot server worker (Linux host). Manages a dnsmasq DHCP+TFTP server
# on the dedicated USB-Ethernet NIC so a Pi 4 on the other end of a crossover
# cable can netboot the latest build. No VM, no bridge — dnsmasq runs directly
# on this host.
#
# Invoked by the wrappers scripts/netboot-server-{up,down}.sh and
# scripts/netboot-server-restart.sh, which set the RPI4B_NETBOOT_* env.
#
# Subcommands:
#   up     start (or restart) dnsmasq fresh, regenerate config, verify it serves
#   down   stop dnsmasq
#   status print pid, lease, log paths
#

set -euo pipefail

iface="${RPI4B_NETBOOT_IFACE:-eth1}"
host_ip="${RPI4B_NETBOOT_HOST_IP:-10.42.0.1}"
netmask="${RPI4B_NETBOOT_NETMASK:-255.255.255.0}"
dhcp_lo="${RPI4B_NETBOOT_DHCP_LO:-10.42.0.10}"
dhcp_hi="${RPI4B_NETBOOT_DHCP_HI:-10.42.0.20}"
buildroot="${PHOENIX_BUILDROOT:-$(cd "$(dirname "$0")/.." && pwd)/.buildroot}"
tftp_root="${RPI4B_NETBOOT_TFTPROOT:-$buildroot/_boot/aarch64a72-generic-rpi4b/rpi4b-bootfs}"
state_dir="${RPI4B_NETBOOT_STATE_DIR:-$(cd "$(dirname "$0")/.." && pwd)/artifacts/netboot}"
# dnsmasq drops to this user after binding privileged ports. The state dir is
# owned by the invoking user, so this is the only user that can write the
# log/lease files. Override via $RPI4B_NETBOOT_DNSMASQ_USER if needed.
dnsmasq_user="${RPI4B_NETBOOT_DNSMASQ_USER:-$(id -un)}"
dnsmasq_group="${RPI4B_NETBOOT_DNSMASQ_GROUP:-$(id -gn)}"

conf_path="$state_dir/dnsmasq.conf"
pid_path="$state_dir/dnsmasq.pid"
log_path="$state_dir/dnsmasq.log"
lease_path="$state_dir/dnsmasq.leases"

usage() {
	cat <<EOF
Usage: netboot-server.sh {up|down|status}

Runs dnsmasq on iface=$iface, host_ip=$host_ip/$netmask,
dhcp=$dhcp_lo..$dhcp_hi, tftp-root=$tftp_root.
EOF
}

require_iface() {
	if ! ip link show "$iface" >/dev/null 2>&1; then
		printf 'iface %s not present\n' "$iface" >&2
		printf 'check the USB-Ethernet NIC is plugged in and RPI4B_NETBOOT_IFACE is correct (.env.local)\n' >&2
		exit 1
	fi
}

ensure_iface_ip() {
	# Pin the netboot IP on the NIC. The link shows NO-CARRIER while the Pi is
	# off; carrier comes up when the Pi powers on. dnsmasq binds the address
	# regardless, so this is safe to do up front.
	local cur
	cur=$(ip -4 -br addr show "$iface" 2>/dev/null | awk '{print $3}')
	if [ "${cur:-}" != "$host_ip/24" ]; then
		printf 'configuring %s -> %s/24\n' "$iface" "$host_ip"
		sudo ip addr flush dev "$iface" || true
		sudo ip addr add "$host_ip/24" dev "$iface"
	fi
	sudo ip link set "$iface" up
}

write_conf() {
	mkdir -p "$state_dir"
	cat > "$conf_path" <<EOF
# generated by netboot-server.sh — do not edit by hand
interface=$iface
bind-interfaces
listen-address=$host_ip
port=0
domain-needed
bogus-priv

# DHCP on the lab subnet only.
dhcp-range=$dhcp_lo,$dhcp_hi,12h
dhcp-option=3            # no router
dhcp-option=6            # no DNS server
dhcp-option=66,$host_ip  # TFTP server name (Pi 4 uses this)
log-dhcp

# TFTP serving the rpi4b bootfs tree directly from the buildroot.
enable-tftp
tftp-root=$tftp_root
tftp-no-blocksize        # some Pi 4 firmware revs dislike RFC 2348 negotiation

# Runtime files under the repo artifacts dir (owned by the invoking user).
log-facility=$log_path
pid-file=$pid_path
dhcp-leasefile=$lease_path

# Drop to the invoking user after binding privileged ports — the state dir is
# owned by that user, so "nobody" (the default) would fail to write here.
user=$dnsmasq_user
group=$dnsmasq_group
EOF
}

stop_existing() {
	if [ -f "$pid_path" ]; then
		local pid
		pid=$(cat "$pid_path" 2>/dev/null || true)
		if [ -n "${pid:-}" ] && sudo kill -0 "$pid" 2>/dev/null; then
			sudo kill "$pid" 2>/dev/null || true
			for _ in 1 2 3 4 5 6 7 8 9 10; do
				sudo kill -0 "$pid" 2>/dev/null || break
				sleep 0.2
			done
		fi
		sudo rm -f "$pid_path"
	fi
}

cmd_up() {
	if ! command -v dnsmasq >/dev/null 2>&1; then
		printf 'dnsmasq not installed\n' >&2
		printf 'install with: sudo apt-get install -y dnsmasq\n' >&2
		exit 1
	fi
	require_iface
	ensure_iface_ip
	if [ ! -d "$tftp_root" ]; then
		printf 'WARNING: tftp-root does not exist: %s\n' "$tftp_root" >&2
		printf '         run scripts/rebuild-rpi4b-fast.sh first\n' >&2
	fi
	mkdir -p "$state_dir"
	write_conf
	stop_existing
	sudo dnsmasq -C "$conf_path"
	sleep 0.4
	# Verify the process is alive...
	if [ ! -f "$pid_path" ] || ! sudo kill -0 "$(cat "$pid_path")" 2>/dev/null; then
		printf 'dnsmasq failed to start; tail of %s:\n' "$log_path" >&2
		sudo tail -n 40 "$log_path" 2>/dev/null >&2 || true
		exit 1
	fi
	# ...and that it actually came up serving DHCP (not just spawned and died
	# on a bind/config error). dnsmasq logs "DHCP, IP range ..." once the DHCP
	# socket is configured; treat its absence as a failed start.
	local waited=0
	while [ "$waited" -lt 20 ]; do
		if sudo grep -q "DHCP, IP range" "$log_path" 2>/dev/null; then
			break
		fi
		if sudo grep -qiE "FAILED to|cannot|address already in use" "$log_path" 2>/dev/null; then
			printf 'dnsmasq reported a startup error; tail of %s:\n' "$log_path" >&2
			sudo tail -n 20 "$log_path" 2>/dev/null >&2 || true
			exit 1
		fi
		sleep 0.2
		waited=$(( waited + 1 ))
	done
	printf '\n=== netboot server up ===\n'
	printf 'iface:     %s (%s/%s)\n' "$iface" "$host_ip" "$netmask"
	printf 'dhcp:      %s..%s\n' "$dhcp_lo" "$dhcp_hi"
	printf 'tftproot:  %s\n' "$tftp_root"
	printf 'pid:       %s\n' "$(cat "$pid_path")"
	printf 'log:       %s\n' "$log_path"
	printf 'leases:    %s\n' "$lease_path"
}

cmd_down() {
	stop_existing
	printf 'dnsmasq stopped (state dir: %s)\n' "$state_dir"
}

cmd_status() {
	if [ -f "$pid_path" ] && sudo kill -0 "$(cat "$pid_path")" 2>/dev/null; then
		printf 'dnsmasq running, pid=%s\n' "$(cat "$pid_path")"
	else
		printf 'dnsmasq not running\n'
	fi
	printf 'iface:     %s\n' "$iface"
	ip -br addr show "$iface" 2>/dev/null || true
	printf 'tftproot:  %s\n' "$tftp_root"
	printf 'log:       %s\n' "$log_path"
	printf 'leases:    %s\n' "$lease_path"
}

case "${1:-}" in
	up)     cmd_up ;;
	down)   cmd_down ;;
	status) cmd_status ;;
	-h|--help|help|"") usage ;;
	*) printf 'unknown subcommand: %s\n' "$1" >&2; usage >&2; exit 1 ;;
esac
