#!/usr/bin/env bash
#
# run-showcase-gate-drm.sh — the showcase gate on the DEFAULT GPU stack (GPU
# migration P1, docs/gpu-new-lane/MIGRATION.md §5 + §7): the six apps plus the
# XFCE desktop, one Pi cycle per app, with the servers (rpi4-v3d-async, rpi4-kms,
# shmsrv) started AT BOOT by the plo script -- no server prelude in the commands.
#
# A copy of run-showcase-gate.sh (never edit that one while a gate might run: see
# its header), changed in four places only:
#   * the app table: the plain command names the P1 image installs (copies of the
#     *-drm programs, TD-26) and an `xfce` row; an entry may hold several psh
#     commands separated by " ;; " (psh has no `;`) and its own max_cmd_secs;
#   * a `boot` column per cycle: the three servers' ready lines and rpi4-kms's
#     render-server connection (`v3d connect=1`) must be in the log -- a cycle whose
#     boot did not bring the stack up is not a result for its app;
#   * `frames` is exempt for `x` and `xfce` (Xorg/labwc print no `flipstat … (total N)`);
#   * the X and XFCE rows set HOLD first, so their launchers tear down by
#     themselves inside max_cmd_secs (the /bin/startx wrapper defaults to HOLD=0,
#     "until Window Maker exits", like the old xlaunch).
#
# Boot image: the default image on netboot/nfsroot, the
# export synced from it, ideally a pristine one (scripts/make-pristine-nfs-export.sh):
# the live export still holds hand-staged -g7/-g8/-low servers and old launchers
# that would mask a missing port install. Check it first with
# scripts/check-gpu-stack-image.sh --root <export>.
#
# The rest of this header is run-showcase-gate.sh's and applies unchanged.
#
# run-showcase-gate.sh — run the six-app showcase gate, one Pi cycle per app,
# and print the result table.
#
# This is the gate the weekly log quotes as "6/6, 0 faults each". It existed only
# as six hand-typed test-cycle-psh-interact.sh invocations, which meant the drive
# commands had to be recovered from old UART logs every time somebody re-ran it,
# and the per-app timings were re-guessed. Both are now recorded here.
#
# ⚠ ABSOLUTE PATHS for the ram-stage launchers, on purpose. Bare `quake2` was
# echoed by psh and then produced NOT ONE BYTE -- no error, no prompt-level
# complaint -- while `/usr/bin/quake2` on the very next cycle loaded baseq2 and
# rendered demo1 at 38.86 fps off the same tree. Bare `quake3` did resolve, so
# this is not a simple PATH story and the single silent run stayed unexplained;
# the absolute form is the one with repeated successes (it is also what the
# known-good 2026-09-10 logs used), so use it and do not "simplify" it back.
#
# ⚠ DO NOT EDIT THIS FILE WHILE A RUN IS IN FLIGHT. bash re-reads a running
# script from a byte OFFSET, so inserting or removing text shifts everything the
# still-executing shell has not read yet and it resumes mid-token. Done here
# 2026-09-10: an edit to the app list mid-gate made the summary come back as
# `line 159: unexpected EOF while looking for matching '`. All six Pi cycles had
# already run and every artifact survived, so only the summary was lost -- but it
# is a silent way to lose a 40-minute run. Copy the script, or wait.
#
# ⚠ THE PI LOCK: the UART is exclusive, so the cycles run STRICTLY SEQUENTIALLY.
# A second concurrent cycle gets an empty log. Do not background individual apps.
# The whole script takes ~35-50 min for six apps, which is longer than a single
# foreground tool call should hold, so run IT in the background and watch the
# summary file:
#
#     nohup ./scripts/run-showcase-gate.sh --label mygate > gate.log 2>&1 &
#
# ⚠ WHAT THIS SCRIPT CANNOT TELL YOU: whether the app actually RENDERED. A game
# that reaches its main loop and draws nothing still exits 0 with a clean UART
# log. The verdict per app is a HUMAN look at the HDMI frames listed in the
# summary -- see docs/inprogress for what each app should look like. What this
# does check is the mechanical part that is easy to get wrong: the app was
# launched, the boot reached psh, and no fault or mid-print stop appeared.
#
# Boot mode is netboot/nfsroot (the export must be in sync with what you want to
# test -- scripts/sync-netboot-tree.sh), so the SD card must be OUT of the Pi.
#
# Copyright 2026 Phoenix Systems
# SPDX-License-Identifier: BSD-3-Clause

set -uo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "${script_dir}/.." && pwd)"
cd "${repo_root}"

# The six drive commands, recovered from the logs of the passing 2026-09-10 gate.
#
# Bare launches are deliberate for Quake 1/2/vkQuake: each auto-plays a demo, and
# their `+commands` are silently ignored on shareware data (the `cmdline` cvar is
# only set on the REGISTERED path), so a `+map` there buys nothing.
#
# ⚠ LAUNCH THE ram-stage LAUNCHER, NOT THE GAME ELF. /usr/bin/quake2 and
# /usr/bin/quake3 are ~730 KB ram-stage-play launchers that copy
# /usr/share/<game> to /tmp (a ramdisk) and then exec the real multi-MB ELF.
# Run the game ELF directly over NFS root and it never finds its data: yquake2
# invoked straight prints "Couldn't determine executable path", writes to
# `//baseq2`, logs no "Added packfile", and dies on
# `GetPCXPalette: Couldn't load pics/colormap.pcx`. Recovering these commands
# from a UART log is where this bites -- the passing log's line 146 reads
# `ram-stage: exec /usr/bin/yquake2`, which is the EXEC TARGET, not what was
# typed. What was typed is on line 139: `/usr/bin/quake2`.
#
# ⚠ Quake III is the EXCEPTION and needs `+map q3dm1`. It ships real pak0/pak1 +
# q3key, so it does honour `+map` -- and launched bare it sits on the MAIN MENU
# forever, which still renders (the GL logo spins) and so still passes every
# mechanical check while testing almost nothing. That is exactly what happened on
# the first run of this script: two of last night's q3 logs exist, the bare one
# never reached a map and the `+map q3dm1` one did, and this list was first
# written from the wrong one.
# The default GPU stack's drive commands (MIGRATION §5 table, with the plain names
# of the P1 image). "key:max_cmd_secs:cmd1 ;; cmd2 ..." -- an empty max_cmd_secs
# is the script default. Absolute paths, for the reason in the header above.
# x:    the old gate's `action` scene on Xorg-drm (Window Maker, the GL window, the
#       two xterms, xbill, xclock); HOLD=200 = startx-drm's own default, so the
#       launcher's clean teardown lands inside 300 s (MIGRATION §6.6).
#       `/bin/bash` in front: bare shebang exec from psh is a bench item (§7).
# vkq:  /usr/bin/vkquake = vkq-drm: the start map (+map start), the #67 torch
#       viewpoint, so the ROI check below applies unchanged.
# xfce: XFCE 4.20 on labwc (GLES2 composition on the V3D), HOLD=60 then the
#       panel's Log Out path, as m7i/m7l; 420 s as those cycles.
apps_default=(
	"x::export HOLD=200 ;; /bin/bash /bin/startx action"
	"qspasm::/usr/bin/quakespasm"
	"q3::/usr/bin/quake3 +map q3dm1"
	"q2::/usr/bin/quake2"
	"vkq::/usr/bin/vkquake"
	"stk::/bin/stk --track=hacienda --numkarts=4 --profile-laps=2"
	"xfce:420:export HOLD=60 ;; /bin/bash /bin/xfce-session"
)

label="gate"
# 150 s was not enough for the FIRST cycle of a session: twice on 2026-09-14 a
# cold first boot missed the `(psh)%` deadline, the app scored rc=2 with "(no
# log)", and a retry at 220 s passed with 0 faults and a normally-rendering
# desktop. A first-cycle miss reads exactly like the app being broken, so give
# the deadline enough room rather than teaching the reader to discount failures.
wait_secs=220
idle_secs=240
max_cmd_secs=300
# Wait this long after the psh prompt before typing the launch command.
#
# NOT cosmetic: the NFS root is not usable the moment the prompt appears.
# rpi4-sysinfo measures it and says so -- "/etc/build-versions appeared after
# 5000 ms (root filesystem mounted late)" -- so for ~5 s after the nfs-fs root
# takeover a large NFS-resident binary can be exec'd before the root is settled.
# It then HANGS BEFORE main() rather than failing: no output at all after the
# command echo, and psh never gets its prompt back.
#
# Measured 2026-09-10 on QuakeSpasm. The gate used to inherit
# test-cycle-psh-interact.sh's 3 s default and lost one app that way; every
# trial that waited 8 s (test-cycle-bench.sh hardcodes 8) reached main(). The
# correlation is exact in the logs: 1 line between "registered / (takeover)"
# and the command echo => hung, 23 lines => ran.
#
# 8 clears the measured 5 s window. The underlying hang is a real libphoenix or
# nfs-fs defect -- an exec that races the root should fail, not wedge -- and this
# only avoids it; see docs/inprogress for the open item.
inter_cmd_secs=8
only=""

usage() {
	cat <<EOF
Usage: $(basename "$0") [options]

  --label TEXT     label prefix for the UART logs (default: $label)
  --only a,b,c     run only these app keys (default: all)
                   keys: $(printf '%s ' "${apps_default[@]%%:*}")
  --wait-secs N    seconds to wait for the psh prompt (default $wait_secs)
  --idle-secs N    capture window after the launch command (default $idle_secs)
  --sd-boot        grade the SD CARD image instead of the netboot tree: every
                   cycle runs with --skip-server-up, and dnsmasq must already be
                   DOWN (scripts/netboot-server-down.sh) so the firmware boots
                   from the card. Restore it afterwards -- netboot is the only
                   other lane. Requires a card holding a bootable image; a BLANK
                   card stops the Pi booting entirely (measured 2026-09-16).
  -h, --help       this
EOF
}

sd_boot=0
while [ $# -gt 0 ]; do
	case "$1" in
		--label)        label="$2"; shift 2 ;;
		--sd-boot)      sd_boot=1; shift ;;
		--only)         only="$2"; shift 2 ;;
		--wait-secs)    wait_secs="$2"; shift 2 ;;
		--idle-secs)    idle_secs="$2"; shift 2 ;;
		--inter-cmd-secs) inter_cmd_secs="$2"; shift 2 ;;
		--max-cmd-secs) max_cmd_secs="$2"; shift 2 ;;
		-h|--help)      usage; exit 0 ;;
		*)              echo "unknown option: $1" >&2; usage >&2; exit 2 ;;
	esac
done

apps=()
for entry in "${apps_default[@]}"; do
	key="${entry%%:*}"
	if [ -n "${only}" ]; then
		case ",${only}," in *",${key},"*) ;; *) continue ;; esac
	fi
	apps+=("${entry}")
done
[ "${#apps[@]}" -gt 0 ] || { echo "no apps selected (--only '${only}')" >&2; exit 2; }

echo "=== showcase gate (default GPU stack, servers at boot): ${#apps[@]} app(s), one Pi cycle each, sequential ==="
if [ "${sd_boot}" = 1 ]; then
	echo "    lane         : SD CARD (dnsmasq must be DOWN; --skip-server-up per cycle)"
fi
echo "    label prefix : ${label}"
echo "    per-app budget: wait ${wait_secs}s + idle ${idle_secs}s"
echo

# A label reused from an earlier gate leaves BOTH runs matching the same
# `*-<label>-*.log` and `artifacts/hdmi/*<label>*` globs. The per-app log pick
# below is already protected (it compares against `${marker}`'s mtime), but the
# HDMI frames are NOT: `check-torch-rois.py --label <label>-vkq` reported
# "114 older frame(s) ... were NOT scored" on 2026-09-22, i.e. it silently found
# a mixed set and had to exclude most of it. Warn, do not refuse -- re-running a
# label deliberately is legitimate, the reader just has to know which frames are
# whose.
prior_logs=$(ls -1 "${repo_root}/artifacts/rpi4b-uart"/rpi4b-uart-*-"${label}"-*.log 2>/dev/null | wc -l)
prior_frames=$(ls -1 "${repo_root}"/artifacts/hdmi/*"${label}"-*.png 2>/dev/null | wc -l)
if [ "${prior_logs}" -gt 0 ] || [ "${prior_frames}" -gt 0 ]; then
	printf '\n!! LABEL REUSED: %d existing log(s) and %d existing frame(s) already match "%s-*".\n' \
		"${prior_logs}" "${prior_frames}" "${label}" >&2
	printf '!! Per-app logs are picked by mtime so they are safe, but scope every later\n' >&2
	printf '!! frame grep by date (artifacts/hdmi/%s-*-%s-*.png) or you will be looking\n' \
		"$(date +%Y%m%d)" "${label}" >&2
	printf '!! at an earlier run.\n\n' >&2
fi

sd_flag=""
[ "${sd_boot}" = 1 ] && sd_flag="--skip-server-up"

declare -a rows=()
rc_all=0
# Timestamp reference for "was this log written by the cycle I just ran?".
marker="$(mktemp)"
trap 'rm -f "${marker}"' EXIT

for entry in "${apps[@]}"; do
	key="${entry%%:*}"
	rest="${entry#*:}"
	app_max="${rest%%:*}"
	[ -n "${app_max}" ] || app_max="${max_cmd_secs}"
	cmdline="${rest#*:}"
	# " ;; "-separated psh commands; the LAST one is the app (the others set env).
	cmds=()
	while [ -n "${cmdline}" ]; do
		case "${cmdline}" in
			*" ;; "*) cmds+=("${cmdline%% ;; *}"); cmdline="${cmdline#* ;; }" ;;
			*) cmds+=("${cmdline}"); cmdline="" ;;
		esac
	done
	cmd="${cmds[${#cmds[@]}-1]}"
	lbl="${label}-${key}"

	echo "--- [${key}] $(printf '%s | ' "${cmds[@]}" | sed 's/ | $//') (max ${app_max}s)"
	touch "${marker}"
	./scripts/test-cycle-psh-interact.sh ${sd_flag} \
		--label "${lbl}" \
		--wait-secs "${wait_secs}" \
		--idle-secs "${idle_secs}" \
		--max-cmd-secs "${app_max}" \
		--inter-cmd-secs "${inter_cmd_secs}" \
		-- "${cmds[@]}"
	cycle_rc=$?

	# Newest log carrying this label AND written by THIS cycle. Without the
	# time bound (the state before 2026-09-17), a cycle that produced no log --
	# which this file's own header records happening -- graded the PREVIOUS run's
	# log for the same label and reported prompt=yes faults=0.
	log="$(find artifacts/rpi4b-uart -maxdepth 1 -name "*${lbl}*.log" -newer "${marker}" \
		-printf '%T@ %p\n' 2>/dev/null | sort -rn | head -1 | cut -d' ' -f2-)"

	prompt="?" faults="?" launched="?" boot="?"
	if [ -n "${log}" ] && [ -s "${log}" ]; then
		# The GPU stack at boot (user.plo.yaml, -f): three ready lines + kms's
		# connection to the render server. All servers are spawned together with
		# psh, so their lines may follow the first prompt; that is not a failure.
		# boot = "ok" or the list of what is missing.
		b_v3d=$(grep -ac 'V3DA srv ready dev=/dev/v3d-async' "${log}" || true)
		b_kms=$(grep -ac 'KMS srv ready dev=/dev/kms' "${log}" || true)
		b_shm=$(grep -ac 'SHMSRV srv ready ns=/shm' "${log}" || true)
		b_con=$(grep -ac 'KMS v3d connect=1' "${log}" || true)
		boot=""
		[ "${b_v3d:-0}" -ge 1 ] || boot="${boot}-v3d"
		[ "${b_kms:-0}" -ge 1 ] || boot="${boot}-kms"
		[ "${b_shm:-0}" -ge 1 ] || boot="${boot}-shm"
		[ "${b_con:-0}" -ge 1 ] || boot="${boot}-connect"
		[ -n "${boot}" ] || boot="ok"
		grep -qa 'psh)%' "${log}" && prompt="yes" || prompt="NO"
		# ⚠ This used to carry its OWN copy of the fault regex, frozen at the
		# 2026-09-10 shape: no allocator patterns (Double free detected, corrupt
		# chunk header, handed out twice, stopping coalesce, not a plausible
		# chunk), no truncated-kernel-message class, and no ends_mid_line. A run
		# uart-summary.sh flagged could be certified "faults 0" here. Ask the
		# script that OWNS the fault set instead of re-implementing it.
		summary="$(./scripts/uart-summary.sh "${log}" 2>/dev/null)"
		faults="$(printf '%s\n' "${summary}" | sed -n 's/^fault_pattern_matches: //p' | head -1)"
		[ -n "${faults}" ] || faults="?"
		midline="$(printf '%s\n' "${summary}" | sed -n 's/^ends_mid_line: //p' | head -1)"
		case "${midline}" in SUSPECT*) faults="${faults}+mid" ;; esac
		# The command echo proves the launch was issued; the app's own output
		# proves it started. Both matter -- a log that stops AT the echo is the
		# signature of a target that took the command and died.
		# ⚠ This is "the command string appears in the log", and psh ECHOES every
		# command it is given — so it cannot fail once the command was sent, and it
		# says nothing about the app starting. Proven twice: this file's own header
		# records a bare `quake2` that was echoed and then "produced NOT ONE BYTE",
		# and on 2026-09-17 it scored yes for a Quake II that hung in SDL_OpenAudio
		# and rendered zero frames (KNOWN-ISSUES q2-sdl-openaudio-hang). Column
		# renamed to say what it measures; the real evidence for a GPU app is the
		# `frames` column, which since 2026-09-17 really is the flipstat counter
		# (it counted HDMI snapshots when this comment was written).
		# Not tightened to "appears more than once": Quake II never echoes its own
		# absolute path, so that test false-negatives on a perfectly good run
		# (measured: 1 occurrence, 8229 frames, correct HDMI).
		# The program, not the interpreter: `/bin/bash /bin/startx action` -> /bin/startx.
		echo_key="${cmd#/bin/bash }"
		echo_key="${echo_key%% *}"
		grep -qaF "${echo_key}" "${log}" && launched="yes" || launched="NO"
	else
		log="(no log)"
	fi

	# ⚠ The column named `frames` counted HDMI SNAPSHOTS until 2026-09-17 -- the
	# capture card grabs one every ~25 s whether or not the Pi drew anything, so
	# the one column this file's own comment calls "the real evidence for a GPU
	# app, 0 for a hung app" could never be 0. Two columns now: `snaps` for the
	# grabs, `frames` for the winsys page-flip counter, which IS the evidence.
	snaps=$(ls -1 artifacts/hdmi/*"${lbl}"* 2>/dev/null | wc -l | tr -d ' ')
	frames="-"
	if [ -n "${log}" ] && [ -s "${log}" ]; then
		frames="$(grep -a 'flipstat' "${log}" | sed -n 's/.*(total \([0-9]*\)).*/\1/p' \
			| sort -n | tail -1)"
		[ -n "${frames}" ] || frames="-"
	fi

	rows+=("${key}|${cycle_rc}|${prompt}|${boot}|${faults}|${launched}|${frames}|${snaps}|${log}")
	[ "${cycle_rc}" = 0 ] || rc_all=1
	if [ "${boot}" != "ok" ]; then
		echo "    ⚠ ${key}: the GPU stack did not come up at boot (${boot}) -- not a result for the app."
		rc_all=1
	fi
	[ "${prompt}" = "yes" ] || rc_all=1
	[ "${faults}" = "0" ] || rc_all=1
	# The GPU apps must have flipped at least one frame. `x` and `xfce` are exempt:
	# Xorg-drm and labwc print no `flipstat … (total N)` line, so they have no
	# frames figure to gate on -- judge them from the HDMI snapshots (and, for x,
	# the XDEMO fps= lines of its GL window).
	if [ "${key}" != "x" ] && [ "${key}" != "xfce" ] && { [ "${frames}" = "-" ] || [ "${frames}" = "0" ]; }; then
		echo "    ⚠ ${key}: ZERO flipstat frames — nothing was drawn."
		rc_all=1
	fi
	echo
done

echo "=== showcase gate summary (default GPU stack) ==="
printf '%-8s %-4s %-7s %-8s %-7s %-9s %-8s %-6s %s\n' app rc prompt boot faults cmd-echo frames snaps log
for r in "${rows[@]}"; do
	IFS='|' read -r a rc p b f l fr sn lg <<<"${r}"
	printf '%-8s %-4s %-7s %-8s %-7s %-9s %-8s %-6s %s\n' "$a" "$rc" "$p" "$b" "$f" "$l" "$fr" "$sn" "$lg"
done
echo

# One pixel-level check runs automatically, because #67's entire history is false
# closures from not measuring: the vkQuake wall torches were declared fixed five
# times on single screenshots, once on a moving lavaball mistaken for a torch.
# vkQuake now boots `map start` (its boot map comes from id1/phoenix-map.cfg --
# this port has no argv path), so every gate cycle lands on the SAME viewpoint and
# the torch ROIs are scoreable without any extra Pi time.
# Only when vkQuake actually ran: with --only qspasm there are no vkq frames, and
# scoring a label that has none would fail a gate that never asked for it. (It
# did exactly that on the first run after the verdict was folded into rc_all.)
ran_vkq=0
for entry in "${apps[@]}"; do
	[ "${entry%%:*}" = "vkq" ] && ran_vkq=1
done
if [ "${ran_vkq}" = 1 ] && [ -x "${repo_root}/scripts/check-torch-rois.py" ]; then
	printf -- '--- #67 vkQuake wall torches (ROI score, %s-vkq) ---\n' "${label}"
	if "${repo_root}/scripts/check-torch-rois.py" --label "${label}-vkq"; then
		printf 'torches: PRESENT\n'
	else
		# Folded into the exit status 2026-09-17: it printed NOT CONFIRMED and
		# still exited 0, so anything gating on this script's rc saw a pass.
		rc_all=1
		printf 'torches: NOT CONFIRMED -- see the ROI output above.\n'
		printf '  A single dark frame is not a failure (the flame animates); this needs\n'
		printf '  >=2 frames with both ROIs lit. If it says 0 at-viewpoint frames, vkQuake\n'
		printf '  did not reach the start map -- check the vkq-drm command line (+map start).\n'
	fi
	echo
fi

echo "⚠ MECHANICAL RESULT ONLY. Now LOOK at the HDMI frames for each app"
echo "  (artifacts/hdmi/*<label>*) before recording a pass -- a clean log does not"
echo "  mean anything was drawn."
exit "${rc_all}"
