#!/usr/bin/env bash
#
# Run from inside the phoenix-dev VM. Manage a dnsmasq DHCP+TFTP server
# on the bridged interface (default: lima1) so a Pi 4 hanging off the
# host's en7 USB-C ethernet (bridged into the VM via socket_vmnet) can
# netboot from the latest build.
#
# This is the in-guest counterpart to the host-side wrappers
# scripts/netboot-server-{up,down}.sh. It is invoked via
# `limactl shell phoenix-dev -- ...`.
#
# Subcommands:
#   up     start (or restart) dnsmasq, regenerate config
#   down   stop dnsmasq
#   status print pid, lease, log paths
#

set -euo pipefail

iface="${RPI4B_NETBOOT_IFACE:-lima1}"
host_ip="${RPI4B_NETBOOT_HOST_IP:-10.42.0.1}"
netmask="${RPI4B_NETBOOT_NETMASK:-255.255.255.0}"
dhcp_lo="${RPI4B_NETBOOT_DHCP_LO:-10.42.0.10}"
dhcp_hi="${RPI4B_NETBOOT_DHCP_HI:-10.42.0.20}"
buildroot="${PHOENIX_BUILDROOT:-/home/witoldbolt.guest/phoenix-buildroots/phoenix-rtos-project-copy}"
tftp_root="${RPI4B_NETBOOT_TFTPROOT:-$buildroot/_boot/aarch64a72-generic-rpi4b/rpi4b-bootfs}"
state_dir="${RPI4B_NETBOOT_STATE_DIR:-/Users/witoldbolt/phoenix-rpi/artifacts/netboot}"

conf_path="$state_dir/dnsmasq.conf"
pid_path="$state_dir/dnsmasq.pid"
log_path="$state_dir/dnsmasq.log"
lease_path="$state_dir/dnsmasq.leases"

usage() {
	cat <<EOF
Usage: vm-netboot-server.sh {up|down|status}

Run inside the phoenix-dev VM. Operates on iface=$iface,
host_ip=$host_ip/$netmask, dhcp=$dhcp_lo..$dhcp_hi,
tftp-root=$tftp_root.
EOF
}

require_iface() {
	if ! ip link show "$iface" >/dev/null 2>&1; then
		printf 'iface %s not present in VM\n' "$iface" >&2
		printf 'check that bridged_en7 is configured in lima.yaml\n' >&2
		exit 1
	fi
}

ensure_iface_ip() {
	# We pin the IP via netplan, but if a fresh boot or apply is in
	# flight, set it manually as a belt-and-braces.
	local cur
	cur=$(ip -4 -br addr show "$iface" 2>/dev/null | awk '{print $3}')
	if [ "${cur:-}" != "$host_ip/24" ]; then
		printf 'configuring %s -> %s/24\n' "$iface" "$host_ip"
		sudo ip addr flush dev "$iface" || true
		sudo ip addr add "$host_ip/24" dev "$iface"
		sudo ip link set "$iface" up
	fi
}

write_conf() {
	mkdir -p "$state_dir"
	cat > "$conf_path" <<EOF
# generated by vm-netboot-server.sh — do not edit by hand
interface=$iface
bind-interfaces
listen-address=$host_ip
port=0
domain-needed
bogus-priv

# DHCP on the lab subnet only.
dhcp-range=$dhcp_lo,$dhcp_hi,12h
dhcp-option=3            # no router
dhcp-option=6            # no DNS server
dhcp-option=66,$host_ip  # TFTP server name (Pi 4 uses this)
log-dhcp

# TFTP serving the rpi4b bootfs tree directly from the buildroot.
enable-tftp
tftp-root=$tftp_root
tftp-no-blocksize        # some Pi 4 firmware revs dislike RFC 2348 negotiation

# Runtime files. Live under the host-mounted artifacts dir so logs and
# leases are visible from macOS without limactl shell.
log-facility=$log_path
pid-file=$pid_path
dhcp-leasefile=$lease_path

# Drop to the human user after binding privileged ports. virtiofs in
# vz only lets that one UID write to the host-mounted state dir; "nobody"
# (the default) and even root fail with EPERM.
user=witoldbolt
group=witoldbolt
EOF
}

stop_existing() {
	if [ -f "$pid_path" ]; then
		local pid
		pid=$(cat "$pid_path" 2>/dev/null || true)
		if [ -n "${pid:-}" ] && sudo kill -0 "$pid" 2>/dev/null; then
			sudo kill "$pid" 2>/dev/null || true
			for _ in 1 2 3 4 5 6 7 8 9 10; do
				sudo kill -0 "$pid" 2>/dev/null || break
				sleep 0.2
			done
		fi
		sudo rm -f "$pid_path"
	fi
}

cmd_up() {
	if ! command -v dnsmasq >/dev/null 2>&1; then
		printf 'dnsmasq not installed in VM\n' >&2
		printf 'install with: sudo apt-get install -y dnsmasq\n' >&2
		exit 1
	fi
	require_iface
	ensure_iface_ip
	if [ ! -d "$tftp_root" ]; then
		printf 'WARNING: tftp-root does not exist: %s\n' "$tftp_root" >&2
		printf '         run scripts/rebuild-rpi4b-fast.sh first\n' >&2
	fi
	mkdir -p "$state_dir"
	write_conf
	stop_existing
	sudo dnsmasq -C "$conf_path"
	sleep 0.4
	if [ ! -f "$pid_path" ] || ! sudo kill -0 "$(cat "$pid_path")" 2>/dev/null; then
		printf 'dnsmasq failed to start; tail of %s:\n' "$log_path" >&2
		sudo tail -n 40 "$log_path" 2>/dev/null >&2 || true
		exit 1
	fi
	printf '\n=== netboot server up (in-VM) ===\n'
	printf 'iface:     %s (%s/%s)\n' "$iface" "$host_ip" "$netmask"
	printf 'dhcp:      %s..%s\n' "$dhcp_lo" "$dhcp_hi"
	printf 'tftproot:  %s\n' "$tftp_root"
	printf 'pid:       %s\n' "$(cat "$pid_path")"
	printf 'log:       %s\n' "$log_path"
	printf 'leases:    %s\n' "$lease_path"
}

cmd_down() {
	stop_existing
	printf 'dnsmasq stopped (state dir: %s)\n' "$state_dir"
}

cmd_status() {
	if [ -f "$pid_path" ] && sudo kill -0 "$(cat "$pid_path")" 2>/dev/null; then
		printf 'dnsmasq running, pid=%s\n' "$(cat "$pid_path")"
	else
		printf 'dnsmasq not running\n'
	fi
	printf 'iface:     %s\n' "$iface"
	ip -br addr show "$iface" 2>/dev/null || true
	printf 'tftproot:  %s\n' "$tftp_root"
	printf 'log:       %s\n' "$log_path"
	printf 'leases:    %s\n' "$lease_path"
}

case "${1:-}" in
	up)     cmd_up ;;
	down)   cmd_down ;;
	status) cmd_status ;;
	-h|--help|help|"") usage ;;
	*) printf 'unknown subcommand: %s\n' "$1" >&2; usage >&2; exit 1 ;;
esac
