#!/usr/bin/env python3
# Generate an M2 frame header (params + slice NAL + NV12 golden reference) from a
# single-IDR HEVC test vector produced by:
#   ffmpeg -f lavfi -i <src>:s=WxH:d=1 -frames:v 1 -pix_fmt yuv420p -c:v libx265 \
#     -x265-params "log-level=none:no-temporal-mvp=1:sao=0:no-open-gop=1:keyint=1" out.265
# Those x265 settings fix the SPS/PPS shape (single-slice, single-tile, no WPP, no
# temporal-mvp, no SAO, 8-bit 4:2:0, CTB 64, the PPS flags below) so only geometry
# + slice data + golden reference vary. Verify with trace_headers if you change them.
#
# Usage: gen-frame-header.py <in.265> <W> <H> <GUARD> > out_frame.h
# SPDX-License-Identifier: BSD-3-Clause
import sys, subprocess, os

f265, W, H, guard = sys.argv[1], int(sys.argv[2]), int(sys.argv[3]), sys.argv[4]
d = open(f265, 'rb').read()

# Locate the last IDR (type 19/20) NAL; payload runs to EOF (single-frame stream).
nals = []
i = 0
while i < len(d) - 3:
    if d[i:i+3] == b'\x00\x00\x01':
        start = i + 3
    elif d[i:i+4] == b'\x00\x00\x00\x01':
        start = i + 4
    else:
        i += 1; continue
    nals.append(start); i = start
idr = [s for s in nals if ((d[s] >> 1) & 0x3f) in (19, 20)][-1]
nal = d[idr:]                      # whole slice NAL, start code stripped
DATA_BYTE_OFFSET = 4               # 2B NAL hdr + 2B slice hdr (first-slice IDR, these params)
BFNUM = len(nal) - DATA_BYTE_OFFSET

# Golden reference in NV12 (interleaved chroma) to match the HW output order.
ref_path = f265 + '.nv12'
subprocess.run(['ffmpeg', '-hide_banner', '-loglevel', 'error', '-i', f265,
                '-f', 'rawvideo', '-pix_fmt', 'nv12', '-y', ref_path], check=True)
ref = open(ref_path, 'rb').read()
os.unlink(ref_path)
Y = ref[:W*H]
C = ref[W*H:W*H + W*H//2]

ctb_w = (W + 63) // 64
ctb_h = (H + 63) // 64

def carr(name, b):
    out = ["static const unsigned char %s[%d] = {" % (name, len(b))]
    for j in range(0, len(b), 16):
        out.append("\t" + ",".join("0x%02x" % x for x in b[j:j+16]) + ",")
    out.append("};")
    return "\n".join(out)

print("/* %s — generated by gen-frame-header.py from a single-IDR HEVC vector." % guard.lower())
print(" * %dx%d, 8-bit 4:2:0, single-slice/tile, CTB 64 (%dx%d CTBs), I-slice." % (W, H, ctb_w, ctb_h))
print(" * SPDX-License-Identifier: BSD-3-Clause */")
print("#ifndef %s\n#define %s" % (guard, guard))
print("#define FRAME_WIDTH %du" % W)
print("#define FRAME_HEIGHT %du" % H)
print("#define FRAME_LOG2_CTB 6u")
print("#define FRAME_CTB_WIDTH %du" % ctb_w)
print("#define FRAME_CTB_HEIGHT %du" % ctb_h)
print("#define FRAME_LOG2_MIN_CB 3u")
print("#define FRAME_LOG2_MIN_TB 2u")
print("#define FRAME_LOG2_MAX_TB 5u")
print("#define FRAME_MAX_TRAFO_INTRA 0u")
print("#define FRAME_MAX_TRAFO_INTER 0u")
print("#define FRAME_CHROMA_FORMAT_IDC 1u")
print("#define FRAME_STRONG_INTRA_SMOOTH 1u")
print("#define FRAME_BIT_DEPTH_LUMA_MINUS8 0u")
print("#define FRAME_DIFF_CU_QP_DELTA_DEPTH 1u")
print("#define FRAME_CU_QP_DELTA_ENABLED 1u")
print("#define FRAME_TRANSFORM_SKIP 0u")
print("#define FRAME_SIGN_DATA_HIDING 1u")
print("#define FRAME_CONSTRAINED_INTRA_PRED 0u")
print("#define FRAME_PPS_CB_QP_OFFSET 0")
print("#define FRAME_PPS_CR_QP_OFFSET 0")
print("#define FRAME_SLICE_CB_QP_OFFSET 0")
print("#define FRAME_SLICE_CR_QP_OFFSET 0")
print("#define FRAME_SLICE_TYPE 2u")
print("#define FRAME_SLICE_QP 25")
print("#define FRAME_CONFIG2 0x25888u")
print("#define FRAME_DATA_BYTE_OFFSET %du" % DATA_BYTE_OFFSET)
print("#define FRAME_DATA_LEN %du" % BFNUM)
print("#define FRAME_HAVE_REF_ARRAYS 1")
print(carr("slice_data", nal))
print(carr("ref_luma", Y))
print(carr("ref_chroma", C))
print("#define EXPECTED_Y(x, y) ref_luma[(y)*FRAME_WIDTH + (x)]")
print("#define EXPECTED_C(x, y) ref_chroma[(y)*FRAME_WIDTH + (x)]")
print("#endif")
