#!/usr/bin/env python3
# Generate a multi-frame CLIP header from an ALL-INTRA HEVC stream (every frame an
# independent IDR I-slice, e.g. x265 keyint=1). The player decodes each frame with
# the single-IDR path and displays them in sequence = all-intra video playback.
# Shares the fixed SPS/PPS shape (single-slice/tile, no-WPP/tmvp/SAO, 8-bit 4:2:0,
# CTB 64) with gen-frame-header.py — verify with trace_headers if params change.
#
# Usage: gen-clip-header.py <in.265> <W> <H> <GUARD> > out_clip.h
# SPDX-License-Identifier: BSD-3-Clause
import sys, subprocess, re
f265, W, H, guard = sys.argv[1], int(sys.argv[2]), int(sys.argv[3]), sys.argv[4]
d = open(f265, 'rb').read()

# Per-frame slice_qp: x265 rate-control varies QP per frame, and a wrong QP feeds
# the wrong CABAC init -> entropy desync -> decode stall. Extract slice_qp_delta
# per frame (in order) via ffmpeg trace_headers; slice_qp = 26 + slice_qp_delta
# (init_qp_minus26 = 0 for these vectors).
tr = subprocess.run(['ffmpeg', '-hide_banner', '-v', 'trace', '-i', f265,
                     '-c', 'copy', '-bsf:v', 'trace_headers', '-f', 'null', '-'],
                    capture_output=True, text=True).stderr
qp_deltas = [int(m) for m in re.findall(r'slice_qp_delta\s+[01]+ = (-?\d+)', tr)]
# trace_headers parses the stream once (the hevc decoder pass); take those in order.
slice_qps = [26 + q for q in qp_deltas]

# Split into NAL start-code boundaries; keep only IDR (type 19/20) NAL payloads.
starts = []
i = 0
while i < len(d) - 3:
    if d[i:i+3] == b'\x00\x00\x01':
        starts.append((i, i+3))
    elif d[i:i+4] == b'\x00\x00\x00\x01':
        starts.append((i, i+4))
    i += 1
frames = []
for k, (sc, s) in enumerate(starts):
    ntype = (d[s] >> 1) & 0x3f
    end = starts[k+1][0] if k+1 < len(starts) else len(d)
    if ntype in (19, 20):
        frames.append(d[s:end])           # slice NAL, start code stripped

DATA_BYTE_OFFSET = 4
blob = b''.join(frames)
# per-frame (offset into blob, full NAL len, BFNUM = data bytes)
idx = []
off = 0
for nal in frames:
    idx.append((off, len(nal), len(nal) - DATA_BYTE_OFFSET))
    off += len(nal)

ctb_w, ctb_h = (W + 63)//64, (H + 63)//64
print("/* %s — %d-frame ALL-INTRA %dx%d clip (generated by gen-clip-header.py)." %
      (guard.lower(), len(frames), W, H))
print(" * SPDX-License-Identifier: BSD-3-Clause */")
print("#ifndef %s\n#define %s" % (guard, guard))
for name, val in [("FRAME_WIDTH", W), ("FRAME_HEIGHT", H), ("FRAME_LOG2_CTB", 6),
                  ("FRAME_CTB_WIDTH", ctb_w), ("FRAME_CTB_HEIGHT", ctb_h),
                  ("FRAME_LOG2_MIN_CB", 3), ("FRAME_LOG2_MIN_TB", 2), ("FRAME_LOG2_MAX_TB", 5),
                  ("FRAME_MAX_TRAFO_INTRA", 0), ("FRAME_MAX_TRAFO_INTER", 0),
                  ("FRAME_CHROMA_FORMAT_IDC", 1), ("FRAME_STRONG_INTRA_SMOOTH", 1),
                  ("FRAME_BIT_DEPTH_LUMA_MINUS8", 0), ("FRAME_DIFF_CU_QP_DELTA_DEPTH", 1),
                  ("FRAME_CU_QP_DELTA_ENABLED", 1), ("FRAME_TRANSFORM_SKIP", 0),
                  ("FRAME_SIGN_DATA_HIDING", 1), ("FRAME_CONSTRAINED_INTRA_PRED", 0),
                  ("FRAME_SLICE_TYPE", 2), ("FRAME_DATA_BYTE_OFFSET", DATA_BYTE_OFFSET)]:
    print("#define %s %du" % (name, val))
for name in ["FRAME_PPS_CB_QP_OFFSET", "FRAME_PPS_CR_QP_OFFSET",
             "FRAME_SLICE_CB_QP_OFFSET", "FRAME_SLICE_CR_QP_OFFSET"]:
    print("#define %s 0" % name)
print("#define FRAME_SLICE_QP 25")
print("#define FRAME_CONFIG2 0x25888u")
print("#define FRAME_DATA_LEN %du" % idx[0][2])          # frame 0 (single-frame path compat)
print("#define CLIP_NFRAMES %d" % len(frames))
# frame 0's slice_data alias so the single-frame decls still resolve
print("static const unsigned char clip_data[%d] = {" % len(blob))
for j in range(0, len(blob), 20):
    print("\t" + ",".join("0x%02x" % b for b in blob[j:j+20]) + ",")
print("};")
# Align the QP list to the frame list (trace may emit one pass; if it emitted two,
# take the trailing set). Fall back to 26 if counts still mismatch.
if len(slice_qps) >= 2 * len(idx):
    slice_qps = slice_qps[-len(idx):]
if len(slice_qps) != len(idx):
    slice_qps = (slice_qps + [26] * len(idx))[:len(idx)]
print("static const struct { unsigned int off, nal_len, bfnum; int qp; } clip_frames[%d] = {" % len(idx))
for i, (o, nl, bf) in enumerate(idx):
    print("\t{%du,%du,%du,%d}," % (o, nl, bf, slice_qps[i]))
print("};")
print("#define slice_data (clip_data + clip_frames[0].off)")
print("#define EXPECTED_Y(x, y) 0  /* unused in clip mode */")
print("#define EXPECTED_C(x, y) 0")
print("#endif")
