#!/usr/bin/env bash
#
# FRAMEWORK PORT: sources/phoenix-rtos-ports libdrm_phoenix,
# opt-in, not in the default image (docs/gpu-new-lane/MIGRATION.md section 4, "Ports (graphics)").
# Every patch/glue file this script uses is also a file of the port; the copies are kept
# identical by scripts/check-gpu-lane-ports-sync.sh -- a change here must be copied there.
#
# libdrm-phoenix (new GPU lane, M3 part 1): upstream libdrm + the Phoenix backend,
# cross-built static for aarch64-phoenix with meson (the E7 recipe), plus the
# drmprobe test program.
#
#   <out>/src/                 a `git clone -s` of external/libdrm at $BASE with
#                              patches/*.patch applied and the backend copied to
#                              src/phoenix/ (external/libdrm itself is never touched)
#   <out>/build/               the meson build directory
#   <out>/prefix/lib/libdrm.a  the static library (+ prefix/include/{xf86drm*.h,libdrm/})
#   <out>/drmprobe             the probe (static, linked with -Wl,--wrap=mmap -Wl,--wrap=ioctl)
#   <out>/libdrm-phoenix-full.patch  everything above as one diff against $BASE
#
# Writes only into <out> (default: build-out/, gitignored). Reads the tree sysroot
# (.buildroot/_build/aarch64a72-generic-rpi4b/sysroot), the toolchain, the E7
# compiler wrapper (drops -pthread, which the Phoenix gcc rejects) and, read-only,
# the servers' wire headers (tools/gpu-lane/v3d-async/v3da_proto.h,
# tools/gpu-lane/kms/kms_proto.h) and the CL generator (v3da_clgen.c).
# No Pi, no rebuild-rpi4b-fast.sh, no /srv.
#
# Usage: tools/gpu-lane/libdrm-phoenix/build.sh [--clean] [--out <dir>] [--lib-only]
# Stage (coordinator only):
#   sudo cp tools/gpu-lane/libdrm-phoenix/build-out/drmprobe <live NFS export>/bin/
#
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
root="$(cd "${here}/../../.." && pwd)"
out="${here}/build-out"
clean=0
lib_only=0
while [ $# -gt 0 ]; do
	case "$1" in
		--clean) clean=1 ;;
		--lib-only) lib_only=1 ;;
		--out) shift; out="${1:?--out needs a directory}" ;;
		--out=*) out="${1#--out=}" ;;
		*) echo "build.sh: unknown argument $1" >&2; exit 2 ;;
	esac
	shift
done
case "${out}" in
	/*) ;;
	*) out="${PWD}/${out}" ;;
esac

BASE=b97cbde                                # upstream libdrm 2.4.134-16 (external/libdrm HEAD at E7)
UPSTREAM="${root}/external/libdrm"
S="${root}/.buildroot/_build/aarch64a72-generic-rpi4b/sysroot"
TC="${root}/.toolchain/aarch64-phoenix/bin/aarch64-phoenix"
PHXCC="${root}/tools/gpu-lane/e7-drm-build/bin/phx-gcc"
V3DA="${root}/tools/gpu-lane/v3d-async"
KMS="${root}/tools/gpu-lane/kms"

if [ "${clean}" = 1 ]; then
	rm -rf "${out}"
	echo "cleaned ${out}"
	exit 0
fi

for p in "${UPSTREAM}/.git" "${S}/lib/libphoenix.a" "${TC}-gcc" "${TC}-gcc-ar" "${PHXCC}" \
		"${V3DA}/v3da_proto.h" "${V3DA}/v3da_clgen.c" "${KMS}/kms_proto.h"; do
	[ -e "${p}" ] || { echo "build.sh: missing ${p}" >&2; exit 1; }
done
# sys_fdpath/memExport live in the TREE sysroot's libphoenix; the toolchain's copy lags.
# (No `nm | grep -q` under pipefail: grep's early exit SIGPIPEs nm and fails the test.)
syms="$("${TC}-nm" "${S}/lib/libphoenix.a" 2>/dev/null || true)"
if ! grep -qw 'T sys_fdpath' <<< "${syms}"; then
	echo "build.sh: ${S}/lib/libphoenix.a has no sys_fdpath" >&2
	exit 1
fi

mkdir -p "${out}"
src="${out}/src"

echo "== libdrm source (${BASE} + patches)"
if [ ! -d "${src}/.git" ]; then
	git clone -q -s "${UPSTREAM}" "${src}"
fi
git -C "${src}" checkout -q -f "${BASE}"
git -C "${src}" clean -qfdx
for p in "${here}"/patches/*.patch; do
	echo "  apply $(basename "${p}")"
	git -C "${src}" apply --whitespace=nowarn "${p}"
done
mkdir -p "${src}/phoenix"
cp "${here}"/src/*.c "${here}"/src/*.h "${here}"/include/*.h "${V3DA}/v3da_proto.h" "${KMS}/kms_proto.h" "${src}/phoenix/"
git -C "${src}" add -A
git -C "${src}" diff --cached "${BASE}" > "${out}/libdrm-phoenix-full.patch"

echo "== meson cross file"
cross="${out}/phoenix-aarch64.cross"
pkgc="${out}/pkg-config-phoenix"
cat > "${pkgc}" <<EOF
#!/bin/sh
# pkg-config restricted to the Phoenix port prefix (never the host's .pc files).
export PKG_CONFIG_LIBDIR=${root}/.buildroot/_build/aarch64a72-generic-rpi4b/lib/pkgconfig
unset PKG_CONFIG_PATH
exec /usr/bin/pkg-config --static "\$@"
EOF
chmod +x "${pkgc}"
flags="'--sysroot=${S}/', '-B${S}/lib/', '-mcpu=cortex-a72', '-mtune=cortex-a72', '-mstrict-align', '-mno-outline-atomics', '-ffunction-sections', '-fdata-sections'"
cat > "${cross}" <<EOF
# Generated by tools/gpu-lane/libdrm-phoenix/build.sh (aarch64-phoenix, Pi 4).
[binaries]
c = '${PHXCC}'
ar = '${TC}-gcc-ar'
nm = '${TC}-nm'
strip = '${TC}-strip'
objcopy = '${TC}-objcopy'
pkg-config = '${pkgc}'

[host_machine]
system = 'phoenix'
cpu_family = 'aarch64'
cpu = 'cortex-a72'
endian = 'little'

[properties]
needs_exe_wrapper = true

[built-in options]
c_args = [${flags}]
c_link_args = ['--sysroot=${S}/', '-B${S}/lib/', '-Wl,-z,max-page-size=0x1000']
default_library = 'static'
EOF

echo "== meson setup + build"
if [ ! -f "${out}/build/build.ninja" ]; then
	meson setup "${out}/build" "${src}" --cross-file "${cross}" --prefix "${out}/prefix" --buildtype=debugoptimized \
		-Dintel=disabled -Dradeon=disabled -Damdgpu=disabled -Dnouveau=disabled -Dvmwgfx=disabled \
		-Domap=disabled -Dexynos=disabled -Dtegra=disabled -Dvc4=enabled -Detnaviv=disabled \
		-Dcairo-tests=disabled -Dman-pages=disabled -Dvalgrind=disabled -Dudev=false -Dtests=false \
		-Dinstall-test-programs=false > "${out}/meson-setup.log" 2>&1 || { tail -30 "${out}/meson-setup.log"; exit 1; }
fi
ninja -C "${out}/build" > "${out}/ninja.log" 2>&1 || { grep -E 'error|Error' "${out}/ninja.log" | head -40; exit 1; }
ninja -C "${out}/build" install > "${out}/install.log" 2>&1 || { tail -20 "${out}/install.log"; exit 1; }
nwarn=$(grep -c 'warning:' "${out}/ninja.log" || true)
echo "  libdrm.a: $(stat -c %s "${out}/prefix/lib/libdrm.a") bytes, ${nwarn} compiler warning(s) (${out}/ninja.log)"
grep 'phoenix/.*warning:' "${out}/ninja.log" | sed 's/^/  /' | head -20 || true
"${TC}-nm" "${out}/prefix/lib/libdrm.a" 2>/dev/null | grep -E ' T (drmIoctl|drm_phoenix_ioctl|drmPhoenixMmap|__wrap_mmap)$' | sed 's/^/  /'

[ "${lib_only}" = 1 ] && exit 0

echo "== drmprobe"
CFLAGS=(-O2 -g -std=gnu11 -Wall -Wextra -Werror -mcpu=cortex-a72 -mtune=cortex-a72 -mstrict-align
	-mno-outline-atomics -ffunction-sections -fdata-sections --sysroot="${S}/" -B"${S}/lib/"
	-I"${here}/include" -I"${out}/prefix/include" -I"${out}/prefix/include/libdrm" -I"${V3DA}")
mkdir -p "${out}/obj"
"${TC}-gcc" "${CFLAGS[@]}" -c "${here}/drmprobe/drmprobe.c" -o "${out}/obj/drmprobe.o"
"${TC}-gcc" "${CFLAGS[@]}" -c "${V3DA}/v3da_clgen.c" -o "${out}/obj/v3da_clgen.o"
"${TC}-gcc" --sysroot="${S}/" -B"${S}/lib/" -static -Wl,--gc-sections -Wl,-z,max-page-size=0x1000 \
	-Wl,--wrap=mmap -Wl,--wrap=ioctl -o "${out}/drmprobe" "${out}/obj/drmprobe.o" "${out}/obj/v3da_clgen.o" \
	"${out}/prefix/lib/libdrm.a"
echo "  ${out}/drmprobe: $(stat -c %s "${out}/drmprobe") bytes"
"${TC}-nm" "${out}/drmprobe" | grep -E ' T (__wrap_mmap|drmPhoenixMmap|drm_phoenix_ioctl)$' | sed 's/^/  /'
