#!/usr/bin/env python3
"""Generate the public vk* link symbols a program calls directly, for a loader-less static ICD.

vkQuake includes <vulkan/vulkan_core.h> with prototypes and calls ~75 core commands
(vkCreateInstance, vkCmdDraw, vkQueueSubmit, ...) as ordinary link symbols; libvulkan (the
loader) would export them. Mesa's ICD does not, so each one is emitted here as a trampoline
that resolves the command once through vkqdrm_GetInstanceProcAddr (vkqdrm_hooks.c -> phxvk ->
Mesa's vk_icdGetInstanceProcAddr) and forwards the call:

  * global commands (vkCreateInstance, vkEnumerateInstance*) resolve with a NULL instance;
  * vkCreateInstance records the instance it created;
  * every other command resolves against that instance. For device-level commands Mesa's
    vk_instance_get_proc_addr() then returns its vk_device_trampolines entry, which dispatches
    through the object's own table (VkDevice / VkQueue / VkCommandBuffer), so no VkDevice has to
    be captured and any number of devices works.

The command set is not hand-kept: the build passes the vk* names that the engine's objects
leave undefined (nm), and the prototypes come from the same vulkan_core.h the engine was
compiled against. A name with no prototype there is an error.

Usage: gen-vk-trampolines.py <vulkan_core.h> <names.txt> <out.c>

Copyright 2026 Phoenix Systems
SPDX-License-Identifier: BSD-3-Clause
"""
import re
import sys

GLOBAL = {"vkCreateInstance", "vkEnumerateInstanceExtensionProperties",
          "vkEnumerateInstanceLayerProperties", "vkEnumerateInstanceVersion"}


def split_params(params):
    out, depth, cur = [], 0, ""
    for ch in params:
        if ch == "," and depth == 0:
            out.append(cur.strip())
            cur = ""
            continue
        depth += ch in "([" and 1 or 0
        depth -= ch in ")]" and 1 or 0
        cur += ch
    if cur.strip():
        out.append(cur.strip())
    return out


def param_name(p):
    p = re.sub(r"\[[^\]]*\]", "", p).strip()
    m = re.search(r"([A-Za-z_][A-Za-z0-9_]*)\s*$", p)
    if not m:
        raise SystemExit(f"cannot parse parameter '{p}'")
    return m.group(1)


def main():
    if len(sys.argv) != 4:
        raise SystemExit(__doc__)
    header, names_file, out = sys.argv[1:]
    text = open(header).read()
    protos = {}
    for m in re.finditer(r"VKAPI_ATTR\s+(.+?)\s+VKAPI_CALL\s+(vk\w+)\s*\((.*?)\)\s*;", text, re.S):
        ret, name, params = " ".join(m.group(1).split()), m.group(2), " ".join(m.group(3).split())
        protos.setdefault(name, (ret, params))
    names = sorted({n.strip() for n in open(names_file) if n.strip()})
    missing = [n for n in names if n not in protos]
    if missing:
        raise SystemExit("no prototype in %s for: %s" % (header, " ".join(missing)))

    o = []
    o.append("/*\n * GENERATED by tools/gpu-lane/sdl2-drm/vkqdrm/gen-vk-trampolines.py -- do not edit.\n"
             " * %d vk* commands the engine calls as link symbols, forwarded to the static v3dv ICD\n"
             " * through vkqdrm_GetInstanceProcAddr (see the generator's docstring).\n */\n" % len(names))
    o.append("#include <stddef.h>\n#include <string.h>\n#include <unistd.h>\n#include <vulkan/vulkan_core.h>\n\n")
    o.append("VKAPI_ATTR PFN_vkVoidFunction VKAPI_CALL vkqdrm_GetInstanceProcAddr(VkInstance instance, const char *name);\n\n")
    o.append("static VkInstance vkqdrm_tramp_instance = VK_NULL_HANDLE;\n\n")
    o.append("static PFN_vkVoidFunction vkqdrm_tramp_resolve(int global, const char *name)\n{\n"
             "\tPFN_vkVoidFunction f = vkqdrm_GetInstanceProcAddr(global ? VK_NULL_HANDLE : vkqdrm_tramp_instance, name);\n\n"
             "\tif (f == NULL) {\n"
             "\t\tstatic const char msg[] = \"vkquake-drm: vk trampoline could not resolve \";\n"
             "\t\t(void)write(2, msg, sizeof(msg) - 1u);\n"
             "\t\t(void)write(2, name, strlen(name));\n"
             "\t\t(void)write(2, \"\\n\", 1u);\n"
             "\t}\n\treturn f;\n}\n")
    for n in names:
        ret, params = protos[n]
        plist = [] if params.strip() in ("", "void") else split_params(params)
        args = ", ".join(param_name(p) for p in plist)
        is_void = ret == "void"
        glob = 1 if n in GLOBAL else 0
        o.append("\nVKAPI_ATTR %s VKAPI_CALL %s(%s)\n{\n" % (ret, n, params if plist else "void"))
        o.append("\tstatic PFN_%s fp = NULL;\n" % n)
        if n == "vkCreateInstance":
            o.append("\tVkResult r;\n\n")
        else:
            o.append("\n")
        o.append("\tif (fp == NULL) {\n\t\tfp = (PFN_%s)vkqdrm_tramp_resolve(%d, \"%s\");\n" % (n, glob, n))
        if is_void:
            o.append("\t\tif (fp == NULL) {\n\t\t\treturn;\n\t\t}\n\t}\n")
        elif ret == "VkResult":
            o.append("\t\tif (fp == NULL) {\n\t\t\treturn VK_ERROR_INITIALIZATION_FAILED;\n\t\t}\n\t}\n")
        else:
            o.append("\t\tif (fp == NULL) {\n\t\t\treturn (%s)0;\n\t\t}\n\t}\n" % ret)
        if n == "vkCreateInstance":
            o.append("\tr = fp(%s);\n\tif ((r == VK_SUCCESS) && (pInstance != NULL)) {\n"
                     "\t\tvkqdrm_tramp_instance = *pInstance;\n\t}\n\treturn r;\n}\n" % args)
        elif is_void:
            o.append("\tfp(%s);\n}\n" % args)
        else:
            o.append("\treturn fp(%s);\n}\n" % args)
    open(out, "w").write("".join(o))


if __name__ == "__main__":
    main()
